// The historical corpus stays immutable. Only its seven known runtime bodies
// change for the source-template merge; every other response byte remains exact.
import { Buffer } from "node:buffer";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { compactSupportText } from "../../tools/assets.ts";

interface Variant {
  driver: number;
  deno?: boolean;
}

const variants: Readonly<Record<string, Variant>> = {
  d5d2b9ef414bc271f45dd94bf501828827c9c23342ccbf267191d7c372528fcc: {
    driver: 1,
    deno: true,
  },
  "1bc90a1dde2c7e7e5584253d795cc948613ffd52f5c8a937355d245403db58dd": {
    driver: 5,
  },
  "3e629321f9cacea80a17768df7875b3c3126ce8dd99bfe2ecaff5ef608b326e4": {
    driver: 1,
  },
  "5c8237312cb1c1a7f268130f681f3bc632717a6f49666b5a6ca56ca193c60295": {
    driver: 4,
    deno: true,
  },
  abf1f1ba518d1b15d60ec1cf8d7a798993381f90d89d70b068c6ab2ab950c059: {
    driver: 3,
  },
  "4a8f3de101484f6baec51e4843b934762b5eb2497f86fbbcffb395a350ceda6e": {
    driver: 2,
  },
  fa200bb19368504f01ed5c5c478269f478e0f498d558463d7ffcba53b0c16a63: {
    driver: 4,
  },
};
const hash = (bytes: Uint8Array) =>
  createHash("sha256").update(bytes).digest("hex");
type Field = readonly [number, Buffer];

function fields(bytes: Buffer): Field[] {
  let cursor = 0;
  const uint = () => {
    let value = 0;
    for (let shift = 0; shift < 35; shift += 7) {
      assert.ok(cursor < bytes.length, "truncated frozen response integer");
      const byte = bytes[cursor++];
      value += (byte & 127) * 2 ** shift;
      if (!(byte & 128)) {
        assert.ok(value <= 0xffffffff, "oversized frozen response integer");
        return value;
      }
    }
    throw new Error("oversized frozen response integer");
  };
  const result: Field[] = [];
  while (cursor < bytes.length) {
    const key = uint();
    assert.equal(key % 8, 2, "unexpected frozen response wire type");
    const length = uint();
    assert.ok(
      length <= bytes.length - cursor,
      "truncated frozen response field",
    );
    result.push([Math.floor(key / 8), bytes.subarray(cursor, cursor + length)]);
    cursor += length;
  }
  return result;
}
function varint(value: number): Buffer {
  const bytes: number[] = [];
  do {
    const byte = value % 128;
    value = Math.floor(value / 128);
    bytes.push(byte | (value ? 128 : 0));
  } while (value);
  return Buffer.from(bytes);
}
const encode = (data: readonly Field[]) =>
  Buffer.concat(
    data.map(([number, bytes]) =>
      Buffer.concat([varint(number * 8 + 2), varint(bytes.length), bytes])
    ),
  );
function responseFiles(response: Buffer): Field[][] {
  const files = fields(response).map(([number, bytes]) => {
    assert.equal(number, 1, "unexpected frozen response field");
    const file = fields(bytes);
    assert.deepEqual(
      file.map(([key]) => key),
      [1, 2],
      "unexpected frozen File fields",
    );
    assert.ok(encode(file).equals(bytes), "noncanonical frozen File encoding");
    return file;
  });
  assert.ok(
    encode(files.map((file) => [1, encode(file)])).equals(response),
    "noncanonical frozen response encoding",
  );
  return files;
}

// Deliberately independent of assets.ts's fragment masks and the WAT table walk.
function selectedSource(source: string, driver: number): string {
  const enabled: Record<string, boolean> = {
    sqlite: driver === 4 || driver === 5,
    server: driver >= 1 && driver <= 3,
    bonakodo: driver === 5,
    "better-sqlite3": driver === 4,
  };
  let section: string | undefined;
  const output: string[] = [];
  for (
    const line of compactSupportText(source).match(/[^\n]*\n|[^\n]+$/g) ?? []
  ) {
    const directive = line.trim();
    if (directive.startsWith("// @if ")) {
      assert.equal(section, undefined, "nested runtime section");
      section = directive.slice(7);
      assert.ok(Object.hasOwn(enabled, section), "unknown runtime section");
    } else if (directive === "// @endif") {
      assert.notEqual(section, undefined, "unmatched runtime section end");
      section = undefined;
    } else if (section === undefined || enabled[section]) output.push(line);
  }
  assert.equal(section, undefined, "unclosed runtime section");
  return output.join("");
}
function expectedRuntime(source: string, { driver, deno }: Variant): Buffer {
  let preamble = "// Code generated by sqlc. DO NOT EDIT.\n\n";
  switch (driver) {
    case 1:
      if (deno) preamble += '// @deno-types="@types/pg"\n';
      preamble +=
        'import type { QueryArrayConfig, QueryArrayResult } from "pg";\n\n' +
        "export interface Database {\n  query(config: QueryArrayConfig): Promise<QueryArrayResult>;\n}\n\n";
      break;
    case 2:
      preamble += 'import type { Sql } from "postgres";\n\n' +
        'export type Database = Pick<Sql, "unsafe">;\n' +
        'export type DriverParameters = NonNullable<Parameters<Sql["unsafe"]>[1]>;\n\n';
      break;
    case 3:
      preamble += 'import type { Connection } from "mysql2/promise";\n\n' +
        'export type Database = Pick<Connection, "execute">;\n\n';
      break;
    case 4:
      if (deno) preamble += '// @deno-types="@types/better-sqlite3"\n';
      preamble +=
        'import type { Database } from "better-sqlite3";\nexport type { Database };\n';
      break;
    case 5:
      preamble +=
        'import type { Database } from "@bonakodo/sqlite";\nexport type { Database };\n\n';
      break;
    default:
      throw new Error("unknown runtime driver");
  }
  if (driver <= 3) {
    preamble += `const jsonDriver: string = "${
      driver === 2 ? "postgres" : "generic"
    }";\n\n`;
  }
  const result = preamble + selectedSource(source, driver);
  return Buffer.from(result.endsWith("\n") ? result : result + "\n");
}
function assertBackend(contents: Buffer, { driver }: Variant) {
  const text = contents.toString();
  assert.doesNotMatch(
    text,
    /^\s*\/\/ @(?:if|endif)\b/m,
    "runtime leaked section markers",
  );
  if (driver >= 4) {
    assert.doesNotMatch(
      text,
      /from "node:buffer"|function parseArrayText|function mysqlInsertId|const jsonDriver:/,
      "SQLite output includes server support",
    );
    assert.match(text, /function lastInsertId\(/);
    assert.doesNotMatch(
      text,
      driver === 4 ? /@bonakodo\/sqlite/ : /better-sqlite3/,
      "SQLite output imports the other driver",
    );
  } else {
    assert.doesNotMatch(
      text,
      /@bonakodo\/sqlite|better-sqlite3|function dateValue|function lastInsertId|const minInt64/,
      "server output includes SQLite support",
    );
    assert.match(text, /function parseArrayText\(/);
    assert.match(text, /function mysqlInsertId\(/);
  }
}

export async function createRuntimeMigration() {
  const source = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true })
    .decode(
      await Deno.readFile(
        new URL("../../src/templates/runtime.ts", import.meta.url),
      ),
    )
    .replace(/\r\n?/g, "\n");
  const expected = new Map(
    Object.entries(variants).map(([oldHash, variant]) => {
      const body = expectedRuntime(source, variant);
      assertBackend(body, variant);
      return [oldHash, body] as const;
    }),
  );
  const current = new Map(
    [...expected].map(([oldHash, body]) => [hash(body), variants[oldHash]]),
  );
  const covered = new Set<string>();
  return {
    migrate(response: Buffer): Buffer {
      const files = responseFiles(response);
      let changed = false;
      for (const file of files) {
        if (file[0][1].toString() !== "runtime.ts") continue;
        const oldHash = hash(file[1][1]), body = expected.get(oldHash);
        assert.ok(body, `unreviewed historical runtime body ${oldHash}`);
        covered.add(oldHash);
        file[1] = [2, body];
        changed = true;
      }
      return changed
        ? encode(files.map((file) => [1, encode(file)]))
        : response;
    },
    assertCoverage() {
      assert.deepEqual(
        [...covered].sort(),
        Object.keys(variants).sort(),
        "historical runtime variants lost coverage",
      );
    },
    assertRuntimeOutput(response: Buffer) {
      for (const file of responseFiles(response)) {
        if (file[0][1].toString() !== "runtime.ts") continue;
        const variant = current.get(hash(file[1][1]));
        assert.ok(
          variant,
          "generated runtime differs from reviewed template and driver preamble",
        );
        assertBackend(file[1][1], variant);
      }
    },
  };
}
