import {
  assertEquals,
  assertRejects,
  assertStringIncludes,
  assertThrows,
} from "@std/assert";
import { toFileUrl } from "@std/path";
import {
  compactSupportText,
  generateAssets,
  renderAssets,
  renderRuntimeTemplate,
  splitRuntimeTemplate,
  type Templates,
} from "../../tools/assets.ts";

const emptyTemplates: Templates = {
  runtime: "",
  json: "",
  codec_error: "",
};

Deno.test("assets preserve UTF-8, NUL, and byte addresses", () => {
  const source = renderAssets(
    { mixed: "A\0é猫😀", empty: "", after: "Z" },
    emptyTemplates,
  );
  assertStringIncludes(
    source,
    '(data (i32.const 2686976) "\\41\\00\\c3\\a9\\e7\\8c\\ab\\f0\\9f\\98\\80")',
  );
  assertStringIncludes(
    source,
    "(func $c_mixed (result i32 i32) (i32.const 2686976) (i32.const 11))",
  );
  assertStringIncludes(
    source,
    "(func $c_empty (result i32 i32) (i32.const 2686987) (i32.const 0))",
  );
  assertStringIncludes(source, '(data (i32.const 2686987) "\\5a")');
});

Deno.test("assets omit trusted JSDoc while retaining other source bytes", () => {
  const text = [
    "/** Heading */",
    "export const text = '/** inside a literal */';",
    "  /**",
    "   * Details",
    "   */",
    "// Keep ordinary comments and indentation.",
    "  export const n = 1;",
    "/* Keep ordinary block comments. */",
    "",
  ].join("\n");
  assertEquals(
    compactSupportText(text),
    [
      "export const text = '/** inside a literal */';",
      "// Keep ordinary comments and indentation.",
      "  export const n = 1;",
      "/* Keep ordinary block comments. */",
      "",
    ].join("\n"),
  );
});

Deno.test("assets reject names that could alter WAT syntax", () => {
  for (const name of ["", "___", "a-b", "a\n(func $bad)", "猫", "a\0b"]) {
    assertThrows(
      () => renderAssets({ [name]: "text" }, emptyTemplates),
      Error,
      "Invalid constant name",
    );
  }
});

Deno.test("assets enforce fixed regions using encoded byte lengths", () => {
  const constants = "é".repeat((2899968 - 2686976) / 2);
  renderAssets({ exact: constants }, emptyTemplates);
  assertThrows(
    () => renderAssets({ overflow: constants + "x" }, emptyTemplates),
    Error,
    "Generator constants exceed their fixed memory region",
  );

  // The JSON and codec-error templates each prepend this generated-file header.
  const headers = 2 * "// Code generated by sqlc. DO NOT EDIT.\n\n".length;
  const template = "x".repeat(1024 * 1024 - headers - 12);
  renderAssets({}, { ...emptyTemplates, runtime: template });
  assertThrows(
    () => renderAssets({}, { ...emptyTemplates, runtime: template + "x" }),
    Error,
    "Support text exceeds its fixed read-only memory region",
  );
});

Deno.test("asset files normalize line endings and reject invalid UTF-8", async () => {
  const directory = await Deno.makeTempDir({ prefix: "sqlc-assets-utf8-" });
  const root = toFileUrl(`${directory}/`);
  const runtime = new URL("src/templates/runtime.ts", root);
  const constants = new URL("src/strings.json", root);
  const source =
    '\uFEFFexport const x = "猫";\r\n// Keep this line.\rexport {};\n';
  try {
    await Deno.mkdir(new URL("src/templates/", root), { recursive: true });
    await Deno.writeTextFile(constants, '{\r\n  "name": "é"\r\n}\r\n');
    for (const name of ["json", "codec_error"]) {
      await Deno.writeTextFile(new URL(`src/templates/${name}.ts`, root), "");
    }
    await Deno.writeTextFile(runtime, source);
    assertEquals(
      await generateAssets(root),
      renderAssets({ name: "é" }, {
        ...emptyTemplates,
        runtime:
          '\uFEFFexport const x = "猫";\n// Keep this line.\nexport {};\n',
      }),
    );

    await Deno.writeFile(runtime, new Uint8Array([0xc0, 0xaf]));
    await assertRejects(() => generateAssets(root), TypeError);
    await Deno.writeTextFile(runtime, source);
    await Deno.writeFile(
      constants,
      new Uint8Array([0x7b, 0x22, 0x78, 0x22, 0x3a, 0x22, 0xff, 0x22, 0x7d]),
    );
    await assertRejects(() => generateAssets(root), TypeError);
  } finally {
    await Deno.remove(directory, { recursive: true });
  }
});

Deno.test("runtime sections select drivers and preserve source order and whitespace", () => {
  const source = [
    "/**",
    "// @if unknown",
    "*/",
    "lead\t ",
    "// @if sqlite",
    "sqlite",
    "// @endif",
    "// @if server",
    "server",
    "// @endif",
    "// @if bonakodo",
    "bonakodo",
    "// @endif",
    "// @if better-sqlite3",
    "better",
    "// @endif",
    'const marker = "// @if sqlite";',
  ].join("\n");
  const tail = 'const marker = "// @if sqlite";';
  assertEquals(splitRuntimeTemplate(source), [
    { mask: 62, text: "lead\t \n" },
    { mask: 48, text: "sqlite\n" },
    { mask: 14, text: "server\n" },
    { mask: 32, text: "bonakodo\n" },
    { mask: 16, text: "better\n" },
    { mask: 62, text: tail },
  ]);
  for (const driver of [1, 2, 3]) {
    assertEquals(
      renderRuntimeTemplate(source, driver),
      `lead\t \nserver\n${tail}`,
    );
  }
  assertEquals(
    renderRuntimeTemplate(source, 4),
    `lead\t \nsqlite\nbetter\n${tail}`,
  );
  assertEquals(
    renderRuntimeTemplate(source, 5),
    `lead\t \nsqlite\nbonakodo\n${tail}`,
  );
});

Deno.test("runtime sections reject nested, unknown, and unbalanced directives", () => {
  for (
    const [source, message] of [
      ["// @if sqlite\n// @if server\n", "cannot nest"],
      ["// @if sqlit\n// @endif\n", "Unknown runtime template condition"],
      ["// @if __proto__\n// @endif\n", "Unknown runtime template condition"],
      ["// @if\n// @endif\n", "Unknown runtime template condition"],
      ["// @if sqlite\nx", "missing @endif"],
      ["// @endif\n", "unmatched @endif"],
      ["// @if server\n// @endif server\n", "takes no label"],
    ]
  ) {
    assertThrows(() => splitRuntimeTemplate(source), Error, message);
  }
  for (const driver of [-1, 0, 6, 1.5, NaN]) {
    assertThrows(() => renderRuntimeTemplate("", driver), Error, "driver");
  }
});

Deno.test("runtime descriptors point to complete UTF-8 fragments", () => {
  const source = renderAssets({}, {
    ...emptyTemplates,
    runtime: "C\n// @if sqlite\n猫\n// @endif\nZ",
  });
  const spans = new Map<number, Uint8Array>();
  for (
    const match of source.matchAll(
      /^\(data \(i32.const (\d+)\) "((?:\\[0-9a-f]{2})*)"\)$/gm,
    )
  ) {
    spans.set(
      Number(match[1]),
      Uint8Array.from(
        match[2].match(/\\[0-9a-f]{2}/g) ?? [],
        (byte) => Number.parseInt(byte.slice(1), 16),
      ),
    );
  }
  assertStringIncludes(
    source,
    "(global $asset_runtime_parts_n i32 (i32.const 3))",
  );
  assertStringIncludes(
    source,
    "(global $asset_runtime_parts_p i32 (i32.const 3145728))",
  );
  const table = spans.get(3145728)!;
  assertEquals(table.length, 36);
  const view = new DataView(table.buffer);
  const descriptors = [0, 12, 24].map((offset) => [
    view.getUint32(offset, true),
    view.getUint32(offset + 4, true),
    view.getUint32(offset + 8, true),
  ]);
  assertEquals(descriptors, [
    [62, 3145764, 2],
    [48, 3145766, 4],
    [62, 3145770, 1],
  ]);
  const decoder = new TextDecoder("utf-8", { fatal: true });
  assertEquals(
    descriptors.map(([, pointer]) => decoder.decode(spans.get(pointer))),
    ["C\n", "猫\n", "Z"],
  );
});

Deno.test("runtime selection emits each common span once in source order", () => {
  const source = "shared\n// @if sqlite\nsqlite\n// @endif\nshared\n";
  assertEquals(renderRuntimeTemplate(source, 1), "shared\nshared\n");
  assertEquals(renderRuntimeTemplate(source, 4), "shared\nsqlite\nshared\n");
  assertEquals(renderRuntimeTemplate(source, 5), "shared\nsqlite\nshared\n");
});

Deno.test("empty runtime sections produce an empty descriptor table", () => {
  for (const runtime of ["", "/** Docs */\n", "// @if sqlite\n// @endif\n"]) {
    assertEquals(splitRuntimeTemplate(runtime), []);
    assertEquals(renderRuntimeTemplate(runtime, 1), "");
    const source = renderAssets({}, { ...emptyTemplates, runtime });
    assertStringIncludes(
      source,
      "(global $asset_runtime_parts_n i32 (i32.const 0))",
    );
    assertStringIncludes(source, '(data (i32.const 3145728) "")');
    assertStringIncludes(
      source,
      "(global $asset_json_p i32 (i32.const 3145728))",
    );
  }
});
