// Package typescript generates TypeScript from sqlc plugin requests using only Go.
// SQL analysis remains the responsibility of sqlc; this package owns TypeScript
// names, driver calls, value conversions, and source emission.
package typescript

import (
	"context"
	_ "embed"
	"fmt"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bonakodo/sqlc-gen-typescript-native/internal/opts"
	"github.com/bonakodo/sqlc-gen-typescript-native/internal/tsast"
	"github.com/jinzhu/inflection"
	"github.com/sqlc-dev/plugin-sdk-go/plugin"
	"google.golang.org/protobuf/proto"
)

// runtimeSource is emitted beside query modules, keeping their only external
// runtime dependency the caller's chosen version of @bonakodo/sqlite.
//
//go:embed runtime.ts
var runtimeSource string

//go:embed server_runtime.ts
var serverRuntimeSource string

// jsonTypesSource is separate from runtime code so types_only output retains
// recursive JSON types without importing any database or Node declarations.
//
//go:embed json.ts
var jsonTypesSource string

// generatedHeader identifies files owned by sqlc rather than the application.
const generatedHeader = "// Code generated by sqlc. DO NOT EDIT.\n\n"

// generator holds immutable input and the catalog names shared by output files.
type generator struct {
	// request is the compiler's immutable generation input.
	request *plugin.GenerateRequest
	// options holds validated TypeScript generation settings.
	options opts.Options
	// models preserves deterministic catalog order for model emission.
	models []*model
	// byTable resolves a compiler table identity to its generated model.
	byTable map[string]*model
	// enums preserves schema/name order for shared enum declarations.
	enums []*catalogEnum
	// byEnum resolves SQL type identities before driver fallback mappings.
	byEnum map[enumKey]*catalogEnum
}

// model links a stable public type name to its original catalog columns.
type model struct {
	// name is the allocated TypeScript interface name.
	name string
	// table is the original catalog identity, including schema.
	table *plugin.Identifier
	// columns contains owned copies with their table identities filled in.
	columns []*plugin.Column
}

// importedName records one import's local spelling and whether it is type-only.
type importedName struct {
	// name is the named export in the source module.
	name string
	// alias avoids generated declarations and function-local bindings.
	alias string
	// typeOnly is false when emitted runtime code uses the import.
	typeOnly bool
}

// module owns declaration names and imports for one generated source file.
type module struct {
	// gen supplies shared immutable options and catalog models.
	gen *generator
	// filename is the output-root-relative path of this module.
	filename string
	// names reserves TypeScript declarations and import aliases.
	names nameSet
	// imports groups imports by module specifier and original export name.
	imports map[string]map[string]*importedName
	// body holds emitted declarations after import resolution.
	body tsast.Writer
	// compatible requests a compile-time constraint for codec-free overrides.
	compatible bool
}

// Generate returns deterministic TypeScript files for an analyzed query set.
// It never writes files or mutates the request and reports unsupported inputs
// before returning any output to sqlc's file writer.
func Generate(ctx context.Context, req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
	if req == nil || req.Catalog == nil || req.Settings == nil {
		return nil, fmt.Errorf("typescript: missing catalog or settings")
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	o, err := opts.Parse(req.PluginOptions)
	if err != nil {
		return nil, fmt.Errorf("typescript options: %w", err)
	}
	if err := o.ValidateEngine(req.Settings.Engine); err != nil {
		return nil, err
	}
	g := &generator{request: req, options: o, byTable: map[string]*model{}}
	if err := g.buildModels(); err != nil {
		return nil, err
	}
	if err := g.buildEnums(); err != nil {
		return nil, err
	}
	models := g.newModule("models.ts")
	for _, model := range g.models {
		models.names[model.name] = true
	}
	for _, model := range g.models {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if err := models.emitModel(model); err != nil {
			return nil, err
		}
	}
	response := &plugin.GenerateResponse{Files: []*plugin.File{{Name: "models.ts", Contents: []byte(models.source())}}}
	groups := map[string][]*plugin.Query{}
	for _, query := range req.Queries {
		if query == nil || query.Name == "" {
			return nil, fmt.Errorf("typescript: query has no name")
		}
		groups[query.Filename] = append(groups[query.Filename], query)
	}
	filenames := make([]string, 0, len(groups))
	for filename := range groups {
		filenames = append(filenames, filename)
	}
	sort.Strings(filenames)
	index := g.newModule("index.ts")
	// Re-exported models and query namespaces share a TypeScript export scope.
	// Reserve model names so a source file named after a table cannot hide the
	// table's interface behind a namespace with the same spelling.
	for _, model := range g.models {
		index.names[model.name] = true
	}
	index.body.Line("/** Reusable table models, independent of a database connection. */")
	index.body.Line("export type * from \"./models.ts\";")
	if len(g.enums) > 0 {
		enums := g.newModule("enums.ts")
		for _, enum := range g.enums {
			index.names[enum.name] = true
			index.names[enum.valuesName] = true
			enums.emitEnum(enum)
		}
		index.body.Line("/** Enum values and their derived types, independent of a database connection. */")
		index.body.Line("export * from \"./enums.ts\";")
		response.Files = append(response.Files, &plugin.File{Name: "enums.ts", Contents: []byte(enums.source())})
	}
	if req.Settings.Engine != "sqlite" {
		for _, name := range []string{"JsonValue", "JsonObject", "JsonArray"} {
			index.names[name] = true
		}
		index.body.Line("/** Parsed JSON types include JSON null independently of SQL nullability. */")
		index.body.Line("export type { JsonValue, JsonObject, JsonArray } from \"./json.ts\";")
		response.Files = append(response.Files, &plugin.File{Name: "json.ts", Contents: []byte(generatedHeader + jsonTypesSource)})
	}
	usedFiles := map[string]bool{"models.ts": true, "index.ts": true, "runtime.ts": true, "json.ts": true, "enums.ts": true}
	for _, filename := range filenames {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		output, err := queryFilename(filename)
		if err != nil {
			return nil, err
		}
		if usedFiles[output] {
			return nil, fmt.Errorf("typescript: output filename collision: %s", output)
		}
		usedFiles[output] = true
		m := g.newModule(output)
		queries := groups[filename]
		sort.SliceStable(queries, func(i, j int) bool { return queries[i].Name < queries[j].Name })
		plans := make([]*queryPlan, 0, len(queries))
		for _, query := range queries {
			if err := ctx.Err(); err != nil {
				return nil, err
			}
			plan, err := m.planQuery(query)
			if err != nil {
				return nil, fmt.Errorf("%s (%s): %w", query.Name, filename, err)
			}
			plans = append(plans, plan)
		}
		for _, plan := range plans {
			if err := ctx.Err(); err != nil {
				return nil, err
			}
			if err := m.emitQuery(plan); err != nil {
				return nil, fmt.Errorf("%s (%s): %w", plan.query.Name, filename, err)
			}
		}
		response.Files = append(response.Files, &plugin.File{Name: output, Contents: []byte(m.source())})
		namespace := index.names.take(declarationName(strings.TrimSuffix(filename, path.Ext(filename))))
		index.body.Line("%s", tsast.Comment([]string{namespace + " groups the queries defined in " + filename + "."}))
		kind := ""
		if o.TypesOnly {
			kind = "type "
		}
		index.body.Line("export %s* as %s from %s;", kind, namespace, tsast.Quote("./"+output))
	}
	response.Files = append(response.Files, &plugin.File{Name: "index.ts", Contents: []byte(index.source())})
	if !o.TypesOnly && len(req.Queries) != 0 {
		runtime := g.runtimeSource()
		response.Files = append(response.Files, &plugin.File{Name: "runtime.ts", Contents: []byte(runtime)})
	}
	sort.Slice(response.Files, func(i, j int) bool { return response.Files[i].Name < response.Files[j].Name })
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	return response, nil
}

// driverSpecifier returns the validated bare package specifier.
func (g *generator) driverSpecifier() string { return g.options.DriverSpecifier() }

// runtimeSource combines shared value conversion with the selected driver types.
// All source is embedded at Go build time, so WASM generation needs no file,
// network, JavaScript runtime, or TypeScript compiler access.
func (g *generator) runtimeSource() string {
	if g.request.Settings.Engine != "sqlite" {
		source := serverRuntimeSource
		if g.options.DriverName() == "postgres" {
			source = strings.Replace(source, `const jsonDriver: string = "generic";`, `const jsonDriver: string = "postgres";`, 1)
		}
		return generatedHeader + g.clientSource() + source
	}
	if g.options.DriverName() != "better-sqlite3" {
		return runtimeSource
	}
	source := strings.Replace(runtimeSource, "// This runtime targets Deno and @bonakodo/sqlite.", "// This runtime targets better-sqlite3.", 1)
	source = strings.Replace(source, `import type { Database } from "@bonakodo/sqlite";`, g.clientSource(), 1)
	// better-sqlite3 statements release with garbage collection; safeIntegers is
	// per statement, preserving caller connection settings and transaction scope.
	start := strings.Index(source, "export function lastInsertId(database: Database): bigint {")
	return source[:start] + `export function lastInsertId(database: Database): bigint {
  const row = database.prepare("SELECT last_insert_rowid()").safeIntegers().raw().get() as [SqliteValue] | undefined;
  if (row === undefined) throw new Error("SQLite did not return last_insert_rowid()");
  return integer(row[0]);
}
`
}

// clientSource uses actual driver declarations while accepting both pooled and
// transaction connections. Picking only the query method avoids requiring a
// pool or transaction to expose connection lifecycle methods it does not own.
func (g *generator) clientSource() string {
	specifier := tsast.Quote(g.driverSpecifier())
	switch g.options.DriverName() {
	case "pg":
		prefix := ""
		if g.options.Runtime == "deno" {
			prefix = "// @deno-types=\"@types/pg\"\n"
		}
		return prefix + "import type { QueryArrayConfig, QueryArrayResult } from " + specifier + ";\n\n/** Database accepts pg clients, pools, and checked-out transaction clients. */\nexport interface Database {\n  query(config: QueryArrayConfig): Promise<QueryArrayResult>;\n}\n\n"
	case "postgres":
		return "import type { Sql } from " + specifier + ";\n\n/** Database accepts postgres.js connections and transaction handles. */\nexport type Database = Pick<Sql, \"unsafe\">;\n/** Parameters is the driver's accepted positional input. */\nexport type DriverParameters = NonNullable<Parameters<Sql[\"unsafe\"]>[1]>;\n\n"
	case "mysql2":
		return "import type { Connection } from " + specifier + ";\n\n/** Database accepts mysql2 promise connections and pools. */\nexport type Database = Pick<Connection, \"execute\">;\n\n"
	case "better-sqlite3":
		prefix := ""
		if g.options.Runtime == "deno" {
			prefix = "// @deno-types=\"@types/better-sqlite3\"\n"
		}
		return prefix + "import type { Database } from " + specifier + ";\nexport type { Database };\n"
	}
	return ""
}

// queryFilename preserves query directories while preventing writes outside out.
func queryFilename(filename string) (string, error) {
	if strings.ContainsRune(filename, '\x00') {
		return "", fmt.Errorf("typescript: query filename contains a NUL byte")
	}
	if strings.ContainsAny(filename, "#?%") {
		return "", fmt.Errorf("typescript: query filename %q contains a URL-significant character (#, ?, or %%)", filename)
	}
	// The plugin can run under WASI or Unix while sqlc writes its response on
	// Windows. Normalize both separators here instead of trusting the plugin's
	// host-specific filepath rules. Drive-relative paths are unsafe as well.
	name := path.Clean(strings.ReplaceAll(filename, "\\", "/"))
	if len(name) >= 2 && name[1] == ':' && (name[0] >= 'A' && name[0] <= 'Z' || name[0] >= 'a' && name[0] <= 'z') {
		return "", fmt.Errorf("typescript: unsafe query filename %q", filename)
	}
	if name == "." || path.IsAbs(name) || name == ".." || strings.HasPrefix(name, "../") {
		return "", fmt.Errorf("typescript: unsafe query filename %q", filename)
	}
	return path.Join(path.Dir(name), strings.ReplaceAll(path.Base(name), ".", "_")+".ts"), nil
}

// tableKey resolves omitted SQLite schemas before matching catalog identities.
func (g *generator) tableKey(id *plugin.Identifier) string {
	if id == nil {
		return ""
	}
	schema := id.Schema
	if schema == "" {
		schema = g.request.Catalog.DefaultSchema
	}
	return id.Catalog + "." + schema + "." + id.Name
}

// buildModels allocates catalog-wide names without altering catalog columns.
func (g *generator) buildModels() error {
	names := newNameSet()
	if g.request.Settings.Engine != "sqlite" {
		// The index re-exports JSON helpers and models in one type namespace.
		// Reserve the helper names before allocating schema model names.
		for _, name := range []string{"JsonValue", "JsonObject", "JsonArray"} {
			names[name] = true
		}
	}
	var tables []*model
	for _, schema := range g.request.Catalog.Schemas {
		if schema == nil {
			return fmt.Errorf("typescript: missing schema metadata")
		}
		if schema.Name == "pg_catalog" || schema.Name == "information_schema" {
			continue
		}
		for _, table := range schema.Tables {
			if table == nil || table.Rel == nil || (g.request.Settings.Engine == "sqlite" && strings.HasPrefix(table.Rel.Name, "sqlite_")) {
				continue
			}
			id := proto.Clone(table.Rel).(*plugin.Identifier)
			if id.Schema == "" {
				id.Schema = schema.Name
			}
			columns := make([]*plugin.Column, 0, len(table.Columns))
			for _, original := range table.Columns {
				if original == nil {
					return fmt.Errorf("typescript: missing column in table %q", table.Rel.Name)
				}
				// EmbedTable marks grouped query results, never stored columns.
				// Rejecting it here also keeps malformed library requests from
				// recursing through a model that embeds itself or a model cycle.
				if original.EmbedTable != nil {
					return fmt.Errorf("typescript: catalog column %q in table %q cannot embed a table", original.Name, table.Rel.Name)
				}
				col := proto.Clone(original).(*plugin.Column)
				col.Table = id
				columns = append(columns, col)
			}
			tables = append(tables, &model{table: id, columns: columns})
		}
	}
	sort.Slice(tables, func(i, j int) bool { return g.tableKey(tables[i].table) < g.tableKey(tables[j].table) })
	for _, model := range tables {
		name := inflection.Singular(model.table.Name)
		if model.table.Schema != "" && model.table.Schema != g.request.Catalog.DefaultSchema {
			name = model.table.Schema + "_" + name
		}
		model.name = names.take(declarationName(name))
		g.models = append(g.models, model)
		g.byTable[g.tableKey(model.table)] = model
	}
	return nil
}

// newModule creates an independent declaration and import scope.
func (g *generator) newModule(filename string) *module {
	names := newNameSet()
	names["_sqlcCompatible"] = true
	return &module{gen: g, filename: filename, names: names, imports: map[string]map[string]*importedName{}}
}

// useImport allocates a collision-free import alias and upgrades value imports.
func (m *module) useImport(specifier, name string, typeOnly bool) string {
	if strings.HasPrefix(specifier, ".") {
		rel, _ := filepath.Rel(filepath.FromSlash(path.Dir(m.filename)), filepath.FromSlash(specifier))
		specifier = filepath.ToSlash(rel)
		if !strings.HasPrefix(specifier, ".") {
			specifier = "./" + specifier
		}
	}
	if m.imports[specifier] == nil {
		m.imports[specifier] = map[string]*importedName{}
	}
	if previous := m.imports[specifier][name]; previous != nil {
		previous.typeOnly = previous.typeOnly && typeOnly
		return previous.alias
	}
	// Function locals use _sqlcParam, _sqlcBindings, and _sqlcSQL. Keeping import
	// aliases in a distinct prefix prevents a codec named args or row from being
	// shadowed when emitted query code calls that codec.
	alias := m.names.take("_sqlcImport" + upperFirst(name))
	m.imports[specifier][name] = &importedName{name: name, alias: alias, typeOnly: typeOnly}
	return alias
}

// runtimeImport imports a shared helper only when a query actually uses it.
func (m *module) runtimeImport(name string, typeOnly bool) string {
	return m.useImport("./runtime.ts", name, typeOnly)
}

// source prints imports in stable order before the accumulated declarations.
func (m *module) source() string {
	var w tsast.Writer
	paths := make([]string, 0, len(m.imports))
	for specifier := range m.imports {
		paths = append(paths, specifier)
	}
	sort.Strings(paths)
	for _, specifier := range paths {
		items := m.imports[specifier]
		names := make([]string, 0, len(items))
		for name := range items {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, typeOnly := range []bool{true, false} {
			var declarations []string
			for _, name := range names {
				item := items[name]
				if item.typeOnly != typeOnly {
					continue
				}
				declaration := name
				if item.alias != name {
					declaration += " as " + item.alias
				}
				declarations = append(declarations, declaration)
			}
			if len(declarations) > 0 {
				prefix := ""
				if typeOnly {
					prefix = "type "
				}
				w.Line("import %s{ %s } from %s;", prefix, strings.Join(declarations, ", "), tsast.Quote(specifier))
			}
		}
	}
	if len(paths) > 0 {
		w.Line("")
	}
	if m.compatible {
		w.Line("/** _sqlcCompatible rejects type-only overrides that change values without a codec. */")
		w.Line("type _sqlcCompatible<Base, T extends Base> = T;")
		w.Line("")
	}
	return strings.TrimRight(generatedHeader+w.String()+m.body.String(), "\n") + "\n"
}
