// Code generated by go generate; DO NOT EDIT.
// Source: sqlc v1.31.1 protos/plugin/codegen.proto.
//go:generate go run ../internal/cmd/genprotocol -schema codegen.proto -out codegen.go

// Package protocol implements sqlc's Generate request/response wire format.
// It keeps only the pinned schema, without protobuf reflection or RPC code.
package protocol

import "unicode/utf8"

type File struct {
	Name          string `json:"name,omitempty"`
	Contents      []byte `json:"contents,omitempty"`
	unknownFields []byte
}

func (x *File) Reset() { *x = File{} }
func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *File) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *File) Clone() *File {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	y.Contents = cloneBytes(x.Contents)
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *File) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *File) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Name = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.Contents = cloneBytes(v)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *File) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *File) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Name) > 0 {
		if !utf8.ValidString(x.Name) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Name))
	}
	if len(x.Contents) > 0 {
		b = appendVarint(b, 18)
		b = appendBytes(b, x.Contents)
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Settings struct {
	Version       string   `json:"version,omitempty"`
	Engine        string   `json:"engine,omitempty"`
	Schema        []string `json:"schema,omitempty"`
	Queries       []string `json:"queries,omitempty"`
	Codegen       *Codegen `json:"codegen,omitempty"`
	unknownFields []byte
}

func (x *Settings) Reset() { *x = Settings{} }
func (x *Settings) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}
func (x *Settings) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}
func (x *Settings) GetSchema() []string {
	if x != nil {
		return x.Schema
	}
	return nil
}
func (x *Settings) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}
func (x *Settings) GetCodegen() *Codegen {
	if x != nil {
		return x.Codegen
	}
	return nil
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Settings) Clone() *Settings {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	if x.Schema != nil {
		y.Schema = append([]string{}, x.Schema...)
	}
	if x.Queries != nil {
		y.Queries = append([]string{}, x.Queries...)
	}
	y.Codegen = x.Codegen.Clone()
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Settings) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Settings) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Version = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Engine = string(v)
		case number == 3 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Schema = append(x.Schema, string(v))
		case number == 4 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Queries = append(x.Queries, string(v))
		case number == 12 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.Codegen == nil {
				x.Codegen = new(Codegen)
			}
			if err := x.Codegen.unmarshal(v, depth-1); err != nil {
				return err
			}
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Settings) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Settings) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Version) > 0 {
		if !utf8.ValidString(x.Version) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Version))
	}
	if len(x.Engine) > 0 {
		if !utf8.ValidString(x.Engine) {
			return nil, errUTF8
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, []byte(x.Engine))
	}
	for _, v := range x.Schema {
		if !utf8.ValidString(v) {
			return nil, errUTF8
		}
		b = appendVarint(b, 26)
		b = appendBytes(b, []byte(v))
	}
	for _, v := range x.Queries {
		if !utf8.ValidString(v) {
			return nil, errUTF8
		}
		b = appendVarint(b, 34)
		b = appendBytes(b, []byte(v))
	}
	if x.Codegen != nil {
		data, err := x.Codegen.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 98)
		b = appendBytes(b, data)
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Codegen struct {
	Out           string           `json:"out,omitempty"`
	Plugin        string           `json:"plugin,omitempty"`
	Options       []byte           `json:"options,omitempty"`
	Env           []string         `json:"env,omitempty"`
	Process       *Codegen_Process `json:"process,omitempty"`
	Wasm          *Codegen_WASM    `json:"wasm,omitempty"`
	unknownFields []byte
}

func (x *Codegen) Reset() { *x = Codegen{} }
func (x *Codegen) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}
func (x *Codegen) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}
func (x *Codegen) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}
func (x *Codegen) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}
func (x *Codegen) GetProcess() *Codegen_Process {
	if x != nil {
		return x.Process
	}
	return nil
}
func (x *Codegen) GetWasm() *Codegen_WASM {
	if x != nil {
		return x.Wasm
	}
	return nil
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Codegen) Clone() *Codegen {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	y.Options = cloneBytes(x.Options)
	if x.Env != nil {
		y.Env = append([]string{}, x.Env...)
	}
	y.Process = x.Process.Clone()
	y.Wasm = x.Wasm.Clone()
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Codegen) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Codegen) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Out = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Plugin = string(v)
		case number == 3 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.Options = cloneBytes(v)
		case number == 4 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Env = append(x.Env, string(v))
		case number == 5 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.Process == nil {
				x.Process = new(Codegen_Process)
			}
			if err := x.Process.unmarshal(v, depth-1); err != nil {
				return err
			}
		case number == 6 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.Wasm == nil {
				x.Wasm = new(Codegen_WASM)
			}
			if err := x.Wasm.unmarshal(v, depth-1); err != nil {
				return err
			}
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Codegen) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Codegen) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Out) > 0 {
		if !utf8.ValidString(x.Out) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Out))
	}
	if len(x.Plugin) > 0 {
		if !utf8.ValidString(x.Plugin) {
			return nil, errUTF8
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, []byte(x.Plugin))
	}
	if len(x.Options) > 0 {
		b = appendVarint(b, 26)
		b = appendBytes(b, x.Options)
	}
	for _, v := range x.Env {
		if !utf8.ValidString(v) {
			return nil, errUTF8
		}
		b = appendVarint(b, 34)
		b = appendBytes(b, []byte(v))
	}
	if x.Process != nil {
		data, err := x.Process.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 42)
		b = appendBytes(b, data)
	}
	if x.Wasm != nil {
		data, err := x.Wasm.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 50)
		b = appendBytes(b, data)
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Codegen_Process struct {
	Cmd           string `json:"cmd,omitempty"`
	unknownFields []byte
}

func (x *Codegen_Process) Reset() { *x = Codegen_Process{} }
func (x *Codegen_Process) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Codegen_Process) Clone() *Codegen_Process {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Codegen_Process) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Codegen_Process) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Cmd = string(v)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Codegen_Process) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Codegen_Process) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Cmd) > 0 {
		if !utf8.ValidString(x.Cmd) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Cmd))
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Codegen_WASM struct {
	Url           string `json:"url,omitempty"`
	Sha256        string `json:"sha256,omitempty"`
	unknownFields []byte
}

func (x *Codegen_WASM) Reset() { *x = Codegen_WASM{} }
func (x *Codegen_WASM) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}
func (x *Codegen_WASM) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Codegen_WASM) Clone() *Codegen_WASM {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Codegen_WASM) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Codegen_WASM) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Url = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Sha256 = string(v)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Codegen_WASM) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Codegen_WASM) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Url) > 0 {
		if !utf8.ValidString(x.Url) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Url))
	}
	if len(x.Sha256) > 0 {
		if !utf8.ValidString(x.Sha256) {
			return nil, errUTF8
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, []byte(x.Sha256))
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Catalog struct {
	Comment       string    `json:"comment,omitempty"`
	DefaultSchema string    `json:"default_schema,omitempty"`
	Name          string    `json:"name,omitempty"`
	Schemas       []*Schema `json:"schemas,omitempty"`
	unknownFields []byte
}

func (x *Catalog) Reset() { *x = Catalog{} }
func (x *Catalog) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}
func (x *Catalog) GetDefaultSchema() string {
	if x != nil {
		return x.DefaultSchema
	}
	return ""
}
func (x *Catalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *Catalog) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Catalog) Clone() *Catalog {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	if x.Schemas != nil {
		y.Schemas = make([]*Schema, len(x.Schemas))
		for i, v := range x.Schemas {
			y.Schemas[i] = v.Clone()
		}
	}
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Catalog) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Catalog) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Comment = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.DefaultSchema = string(v)
		case number == 3 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Name = string(v)
		case number == 4 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			m := new(Schema)
			if err := m.unmarshal(v, depth-1); err != nil {
				return err
			}
			x.Schemas = append(x.Schemas, m)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Catalog) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Catalog) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Comment) > 0 {
		if !utf8.ValidString(x.Comment) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Comment))
	}
	if len(x.DefaultSchema) > 0 {
		if !utf8.ValidString(x.DefaultSchema) {
			return nil, errUTF8
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, []byte(x.DefaultSchema))
	}
	if len(x.Name) > 0 {
		if !utf8.ValidString(x.Name) {
			return nil, errUTF8
		}
		b = appendVarint(b, 26)
		b = appendBytes(b, []byte(x.Name))
	}
	for _, v := range x.Schemas {
		data, err := v.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 34)
		b = appendBytes(b, data)
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Schema struct {
	Comment        string           `json:"comment,omitempty"`
	Name           string           `json:"name,omitempty"`
	Tables         []*Table         `json:"tables,omitempty"`
	Enums          []*Enum          `json:"enums,omitempty"`
	CompositeTypes []*CompositeType `json:"composite_types,omitempty"`
	unknownFields  []byte
}

func (x *Schema) Reset() { *x = Schema{} }
func (x *Schema) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}
func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *Schema) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}
func (x *Schema) GetEnums() []*Enum {
	if x != nil {
		return x.Enums
	}
	return nil
}
func (x *Schema) GetCompositeTypes() []*CompositeType {
	if x != nil {
		return x.CompositeTypes
	}
	return nil
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Schema) Clone() *Schema {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	if x.Tables != nil {
		y.Tables = make([]*Table, len(x.Tables))
		for i, v := range x.Tables {
			y.Tables[i] = v.Clone()
		}
	}
	if x.Enums != nil {
		y.Enums = make([]*Enum, len(x.Enums))
		for i, v := range x.Enums {
			y.Enums[i] = v.Clone()
		}
	}
	if x.CompositeTypes != nil {
		y.CompositeTypes = make([]*CompositeType, len(x.CompositeTypes))
		for i, v := range x.CompositeTypes {
			y.CompositeTypes[i] = v.Clone()
		}
	}
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Schema) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Schema) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Comment = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Name = string(v)
		case number == 3 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			m := new(Table)
			if err := m.unmarshal(v, depth-1); err != nil {
				return err
			}
			x.Tables = append(x.Tables, m)
		case number == 4 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			m := new(Enum)
			if err := m.unmarshal(v, depth-1); err != nil {
				return err
			}
			x.Enums = append(x.Enums, m)
		case number == 5 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			m := new(CompositeType)
			if err := m.unmarshal(v, depth-1); err != nil {
				return err
			}
			x.CompositeTypes = append(x.CompositeTypes, m)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Schema) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Schema) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Comment) > 0 {
		if !utf8.ValidString(x.Comment) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Comment))
	}
	if len(x.Name) > 0 {
		if !utf8.ValidString(x.Name) {
			return nil, errUTF8
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, []byte(x.Name))
	}
	for _, v := range x.Tables {
		data, err := v.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 26)
		b = appendBytes(b, data)
	}
	for _, v := range x.Enums {
		data, err := v.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 34)
		b = appendBytes(b, data)
	}
	for _, v := range x.CompositeTypes {
		data, err := v.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 42)
		b = appendBytes(b, data)
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type CompositeType struct {
	Name          string `json:"name,omitempty"`
	Comment       string `json:"comment,omitempty"`
	unknownFields []byte
}

func (x *CompositeType) Reset() { *x = CompositeType{} }
func (x *CompositeType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *CompositeType) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *CompositeType) Clone() *CompositeType {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *CompositeType) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *CompositeType) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Name = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Comment = string(v)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *CompositeType) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *CompositeType) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Name) > 0 {
		if !utf8.ValidString(x.Name) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Name))
	}
	if len(x.Comment) > 0 {
		if !utf8.ValidString(x.Comment) {
			return nil, errUTF8
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, []byte(x.Comment))
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Enum struct {
	Name          string   `json:"name,omitempty"`
	Vals          []string `json:"vals,omitempty"`
	Comment       string   `json:"comment,omitempty"`
	unknownFields []byte
}

func (x *Enum) Reset() { *x = Enum{} }
func (x *Enum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *Enum) GetVals() []string {
	if x != nil {
		return x.Vals
	}
	return nil
}
func (x *Enum) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Enum) Clone() *Enum {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	if x.Vals != nil {
		y.Vals = append([]string{}, x.Vals...)
	}
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Enum) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Enum) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Name = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Vals = append(x.Vals, string(v))
		case number == 3 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Comment = string(v)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Enum) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Enum) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Name) > 0 {
		if !utf8.ValidString(x.Name) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Name))
	}
	for _, v := range x.Vals {
		if !utf8.ValidString(v) {
			return nil, errUTF8
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, []byte(v))
	}
	if len(x.Comment) > 0 {
		if !utf8.ValidString(x.Comment) {
			return nil, errUTF8
		}
		b = appendVarint(b, 26)
		b = appendBytes(b, []byte(x.Comment))
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Table struct {
	Rel           *Identifier `json:"rel,omitempty"`
	Columns       []*Column   `json:"columns,omitempty"`
	Comment       string      `json:"comment,omitempty"`
	unknownFields []byte
}

func (x *Table) Reset() { *x = Table{} }
func (x *Table) GetRel() *Identifier {
	if x != nil {
		return x.Rel
	}
	return nil
}
func (x *Table) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}
func (x *Table) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Table) Clone() *Table {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	y.Rel = x.Rel.Clone()
	if x.Columns != nil {
		y.Columns = make([]*Column, len(x.Columns))
		for i, v := range x.Columns {
			y.Columns[i] = v.Clone()
		}
	}
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Table) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Table) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.Rel == nil {
				x.Rel = new(Identifier)
			}
			if err := x.Rel.unmarshal(v, depth-1); err != nil {
				return err
			}
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			m := new(Column)
			if err := m.unmarshal(v, depth-1); err != nil {
				return err
			}
			x.Columns = append(x.Columns, m)
		case number == 3 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Comment = string(v)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Table) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Table) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if x.Rel != nil {
		data, err := x.Rel.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, data)
	}
	for _, v := range x.Columns {
		data, err := v.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, data)
	}
	if len(x.Comment) > 0 {
		if !utf8.ValidString(x.Comment) {
			return nil, errUTF8
		}
		b = appendVarint(b, 26)
		b = appendBytes(b, []byte(x.Comment))
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Identifier struct {
	Catalog       string `json:"catalog,omitempty"`
	Schema        string `json:"schema,omitempty"`
	Name          string `json:"name,omitempty"`
	unknownFields []byte
}

func (x *Identifier) Reset() { *x = Identifier{} }
func (x *Identifier) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}
func (x *Identifier) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}
func (x *Identifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Identifier) Clone() *Identifier {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Identifier) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Identifier) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Catalog = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Schema = string(v)
		case number == 3 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Name = string(v)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Identifier) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Identifier) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Catalog) > 0 {
		if !utf8.ValidString(x.Catalog) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Catalog))
	}
	if len(x.Schema) > 0 {
		if !utf8.ValidString(x.Schema) {
			return nil, errUTF8
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, []byte(x.Schema))
	}
	if len(x.Name) > 0 {
		if !utf8.ValidString(x.Name) {
			return nil, errUTF8
		}
		b = appendVarint(b, 26)
		b = appendBytes(b, []byte(x.Name))
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Column struct {
	Name          string      `json:"name,omitempty"`
	NotNull       bool        `json:"not_null,omitempty"`
	IsArray       bool        `json:"is_array,omitempty"`
	Comment       string      `json:"comment,omitempty"`
	Length        int32       `json:"length,omitempty"`
	IsNamedParam  bool        `json:"is_named_param,omitempty"`
	IsFuncCall    bool        `json:"is_func_call,omitempty"`
	Scope         string      `json:"scope,omitempty"`
	Table         *Identifier `json:"table,omitempty"`
	TableAlias    string      `json:"table_alias,omitempty"`
	Type          *Identifier `json:"type,omitempty"`
	IsSqlcSlice   bool        `json:"is_sqlc_slice,omitempty"`
	EmbedTable    *Identifier `json:"embed_table,omitempty"`
	OriginalName  string      `json:"original_name,omitempty"`
	Unsigned      bool        `json:"unsigned,omitempty"`
	ArrayDims     int32       `json:"array_dims,omitempty"`
	unknownFields []byte
}

func (x *Column) Reset() { *x = Column{} }
func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *Column) GetNotNull() bool {
	if x != nil {
		return x.NotNull
	}
	return false
}
func (x *Column) GetIsArray() bool {
	if x != nil {
		return x.IsArray
	}
	return false
}
func (x *Column) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}
func (x *Column) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}
func (x *Column) GetIsNamedParam() bool {
	if x != nil {
		return x.IsNamedParam
	}
	return false
}
func (x *Column) GetIsFuncCall() bool {
	if x != nil {
		return x.IsFuncCall
	}
	return false
}
func (x *Column) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}
func (x *Column) GetTable() *Identifier {
	if x != nil {
		return x.Table
	}
	return nil
}
func (x *Column) GetTableAlias() string {
	if x != nil {
		return x.TableAlias
	}
	return ""
}
func (x *Column) GetType() *Identifier {
	if x != nil {
		return x.Type
	}
	return nil
}
func (x *Column) GetIsSqlcSlice() bool {
	if x != nil {
		return x.IsSqlcSlice
	}
	return false
}
func (x *Column) GetEmbedTable() *Identifier {
	if x != nil {
		return x.EmbedTable
	}
	return nil
}
func (x *Column) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}
func (x *Column) GetUnsigned() bool {
	if x != nil {
		return x.Unsigned
	}
	return false
}
func (x *Column) GetArrayDims() int32 {
	if x != nil {
		return x.ArrayDims
	}
	return 0
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Column) Clone() *Column {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	y.Table = x.Table.Clone()
	y.Type = x.Type.Clone()
	y.EmbedTable = x.EmbedTable.Clone()
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Column) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Column) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Name = string(v)
		case number == 3 && wire == 0:
			v, n, err := consumeVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.NotNull = v != 0
		case number == 4 && wire == 0:
			v, n, err := consumeVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.IsArray = v != 0
		case number == 5 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Comment = string(v)
		case number == 6 && wire == 0:
			v, n, err := consumeVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.Length = int32(v)
		case number == 7 && wire == 0:
			v, n, err := consumeVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.IsNamedParam = v != 0
		case number == 8 && wire == 0:
			v, n, err := consumeVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.IsFuncCall = v != 0
		case number == 9 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Scope = string(v)
		case number == 10 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.Table == nil {
				x.Table = new(Identifier)
			}
			if err := x.Table.unmarshal(v, depth-1); err != nil {
				return err
			}
		case number == 11 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.TableAlias = string(v)
		case number == 12 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.Type == nil {
				x.Type = new(Identifier)
			}
			if err := x.Type.unmarshal(v, depth-1); err != nil {
				return err
			}
		case number == 13 && wire == 0:
			v, n, err := consumeVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.IsSqlcSlice = v != 0
		case number == 14 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.EmbedTable == nil {
				x.EmbedTable = new(Identifier)
			}
			if err := x.EmbedTable.unmarshal(v, depth-1); err != nil {
				return err
			}
		case number == 15 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.OriginalName = string(v)
		case number == 16 && wire == 0:
			v, n, err := consumeVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.Unsigned = v != 0
		case number == 17 && wire == 0:
			v, n, err := consumeVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.ArrayDims = int32(v)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Column) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Column) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Name) > 0 {
		if !utf8.ValidString(x.Name) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Name))
	}
	if x.NotNull {
		b = appendVarint(b, 24)
		b = append(b, 1)
	}
	if x.IsArray {
		b = appendVarint(b, 32)
		b = append(b, 1)
	}
	if len(x.Comment) > 0 {
		if !utf8.ValidString(x.Comment) {
			return nil, errUTF8
		}
		b = appendVarint(b, 42)
		b = appendBytes(b, []byte(x.Comment))
	}
	if x.Length != 0 {
		b = appendVarint(b, 48)
		b = appendVarint(b, uint64(x.Length))
	}
	if x.IsNamedParam {
		b = appendVarint(b, 56)
		b = append(b, 1)
	}
	if x.IsFuncCall {
		b = appendVarint(b, 64)
		b = append(b, 1)
	}
	if len(x.Scope) > 0 {
		if !utf8.ValidString(x.Scope) {
			return nil, errUTF8
		}
		b = appendVarint(b, 74)
		b = appendBytes(b, []byte(x.Scope))
	}
	if x.Table != nil {
		data, err := x.Table.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 82)
		b = appendBytes(b, data)
	}
	if len(x.TableAlias) > 0 {
		if !utf8.ValidString(x.TableAlias) {
			return nil, errUTF8
		}
		b = appendVarint(b, 90)
		b = appendBytes(b, []byte(x.TableAlias))
	}
	if x.Type != nil {
		data, err := x.Type.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 98)
		b = appendBytes(b, data)
	}
	if x.IsSqlcSlice {
		b = appendVarint(b, 104)
		b = append(b, 1)
	}
	if x.EmbedTable != nil {
		data, err := x.EmbedTable.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 114)
		b = appendBytes(b, data)
	}
	if len(x.OriginalName) > 0 {
		if !utf8.ValidString(x.OriginalName) {
			return nil, errUTF8
		}
		b = appendVarint(b, 122)
		b = appendBytes(b, []byte(x.OriginalName))
	}
	if x.Unsigned {
		b = appendVarint(b, 128)
		b = append(b, 1)
	}
	if x.ArrayDims != 0 {
		b = appendVarint(b, 136)
		b = appendVarint(b, uint64(x.ArrayDims))
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Query struct {
	Text            string       `json:"text,omitempty"`
	Name            string       `json:"name,omitempty"`
	Cmd             string       `json:"cmd,omitempty"`
	Columns         []*Column    `json:"columns,omitempty"`
	Params          []*Parameter `json:"params,omitempty"`
	Comments        []string     `json:"comments,omitempty"`
	Filename        string       `json:"filename,omitempty"`
	InsertIntoTable *Identifier  `json:"insert_into_table,omitempty"`
	unknownFields   []byte
}

func (x *Query) Reset() { *x = Query{} }
func (x *Query) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}
func (x *Query) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *Query) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}
func (x *Query) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}
func (x *Query) GetParams() []*Parameter {
	if x != nil {
		return x.Params
	}
	return nil
}
func (x *Query) GetComments() []string {
	if x != nil {
		return x.Comments
	}
	return nil
}
func (x *Query) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}
func (x *Query) GetInsertIntoTable() *Identifier {
	if x != nil {
		return x.InsertIntoTable
	}
	return nil
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Query) Clone() *Query {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	if x.Columns != nil {
		y.Columns = make([]*Column, len(x.Columns))
		for i, v := range x.Columns {
			y.Columns[i] = v.Clone()
		}
	}
	if x.Params != nil {
		y.Params = make([]*Parameter, len(x.Params))
		for i, v := range x.Params {
			y.Params[i] = v.Clone()
		}
	}
	if x.Comments != nil {
		y.Comments = append([]string{}, x.Comments...)
	}
	y.InsertIntoTable = x.InsertIntoTable.Clone()
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Query) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Query) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Text = string(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Name = string(v)
		case number == 3 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Cmd = string(v)
		case number == 4 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			m := new(Column)
			if err := m.unmarshal(v, depth-1); err != nil {
				return err
			}
			x.Columns = append(x.Columns, m)
		case number == 5 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			m := new(Parameter)
			if err := m.unmarshal(v, depth-1); err != nil {
				return err
			}
			x.Params = append(x.Params, m)
		case number == 6 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Comments = append(x.Comments, string(v))
		case number == 7 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.Filename = string(v)
		case number == 8 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.InsertIntoTable == nil {
				x.InsertIntoTable = new(Identifier)
			}
			if err := x.InsertIntoTable.unmarshal(v, depth-1); err != nil {
				return err
			}
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Query) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Query) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if len(x.Text) > 0 {
		if !utf8.ValidString(x.Text) {
			return nil, errUTF8
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, []byte(x.Text))
	}
	if len(x.Name) > 0 {
		if !utf8.ValidString(x.Name) {
			return nil, errUTF8
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, []byte(x.Name))
	}
	if len(x.Cmd) > 0 {
		if !utf8.ValidString(x.Cmd) {
			return nil, errUTF8
		}
		b = appendVarint(b, 26)
		b = appendBytes(b, []byte(x.Cmd))
	}
	for _, v := range x.Columns {
		data, err := v.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 34)
		b = appendBytes(b, data)
	}
	for _, v := range x.Params {
		data, err := v.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 42)
		b = appendBytes(b, data)
	}
	for _, v := range x.Comments {
		if !utf8.ValidString(v) {
			return nil, errUTF8
		}
		b = appendVarint(b, 50)
		b = appendBytes(b, []byte(v))
	}
	if len(x.Filename) > 0 {
		if !utf8.ValidString(x.Filename) {
			return nil, errUTF8
		}
		b = appendVarint(b, 58)
		b = appendBytes(b, []byte(x.Filename))
	}
	if x.InsertIntoTable != nil {
		data, err := x.InsertIntoTable.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 66)
		b = appendBytes(b, data)
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type Parameter struct {
	Number        int32   `json:"number,omitempty"`
	Column        *Column `json:"column,omitempty"`
	unknownFields []byte
}

func (x *Parameter) Reset() { *x = Parameter{} }
func (x *Parameter) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}
func (x *Parameter) GetColumn() *Column {
	if x != nil {
		return x.Column
	}
	return nil
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *Parameter) Clone() *Parameter {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	y.Column = x.Column.Clone()
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *Parameter) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *Parameter) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 0:
			v, n, err := consumeVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.Number = int32(v)
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.Column == nil {
				x.Column = new(Column)
			}
			if err := x.Column.unmarshal(v, depth-1); err != nil {
				return err
			}
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *Parameter) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *Parameter) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if x.Number != 0 {
		b = appendVarint(b, 8)
		b = appendVarint(b, uint64(x.Number))
	}
	if x.Column != nil {
		data, err := x.Column.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, data)
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type GenerateRequest struct {
	Settings      *Settings `json:"settings,omitempty"`
	Catalog       *Catalog  `json:"catalog,omitempty"`
	Queries       []*Query  `json:"queries,omitempty"`
	SqlcVersion   string    `json:"sqlc_version,omitempty"`
	PluginOptions []byte    `json:"plugin_options,omitempty"`
	GlobalOptions []byte    `json:"global_options,omitempty"`
	unknownFields []byte
}

func (x *GenerateRequest) Reset() { *x = GenerateRequest{} }
func (x *GenerateRequest) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}
func (x *GenerateRequest) GetCatalog() *Catalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}
func (x *GenerateRequest) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}
func (x *GenerateRequest) GetSqlcVersion() string {
	if x != nil {
		return x.SqlcVersion
	}
	return ""
}
func (x *GenerateRequest) GetPluginOptions() []byte {
	if x != nil {
		return x.PluginOptions
	}
	return nil
}
func (x *GenerateRequest) GetGlobalOptions() []byte {
	if x != nil {
		return x.GlobalOptions
	}
	return nil
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *GenerateRequest) Clone() *GenerateRequest {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	y.Settings = x.Settings.Clone()
	y.Catalog = x.Catalog.Clone()
	if x.Queries != nil {
		y.Queries = make([]*Query, len(x.Queries))
		for i, v := range x.Queries {
			y.Queries[i] = v.Clone()
		}
	}
	y.PluginOptions = cloneBytes(x.PluginOptions)
	y.GlobalOptions = cloneBytes(x.GlobalOptions)
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *GenerateRequest) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *GenerateRequest) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.Settings == nil {
				x.Settings = new(Settings)
			}
			if err := x.Settings.unmarshal(v, depth-1); err != nil {
				return err
			}
		case number == 2 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if x.Catalog == nil {
				x.Catalog = new(Catalog)
			}
			if err := x.Catalog.unmarshal(v, depth-1); err != nil {
				return err
			}
		case number == 3 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			m := new(Query)
			if err := m.unmarshal(v, depth-1); err != nil {
				return err
			}
			x.Queries = append(x.Queries, m)
		case number == 4 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if !utf8.Valid(v) {
				return errUTF8
			}
			x.SqlcVersion = string(v)
		case number == 5 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.PluginOptions = cloneBytes(v)
		case number == 6 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			x.GlobalOptions = cloneBytes(v)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *GenerateRequest) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *GenerateRequest) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	if x.Settings != nil {
		data, err := x.Settings.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, data)
	}
	if x.Catalog != nil {
		data, err := x.Catalog.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 18)
		b = appendBytes(b, data)
	}
	for _, v := range x.Queries {
		data, err := v.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 26)
		b = appendBytes(b, data)
	}
	if len(x.SqlcVersion) > 0 {
		if !utf8.ValidString(x.SqlcVersion) {
			return nil, errUTF8
		}
		b = appendVarint(b, 34)
		b = appendBytes(b, []byte(x.SqlcVersion))
	}
	if len(x.PluginOptions) > 0 {
		b = appendVarint(b, 42)
		b = appendBytes(b, x.PluginOptions)
	}
	if len(x.GlobalOptions) > 0 {
		b = appendVarint(b, 50)
		b = appendBytes(b, x.GlobalOptions)
	}
	return appendUnknown(b, x.unknownFields, depth)
}

type GenerateResponse struct {
	Files         []*File `json:"files,omitempty"`
	unknownFields []byte
}

func (x *GenerateResponse) Reset() { *x = GenerateResponse{} }
func (x *GenerateResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

// Clone returns a deep copy and preserves nil slices and message presence.
func (x *GenerateResponse) Clone() *GenerateResponse {
	if x == nil {
		return nil
	}
	y := *x
	y.unknownFields = cloneBytes(x.unknownFields)
	if x.Files != nil {
		y.Files = make([]*File, len(x.Files))
		for i, v := range x.Files {
			y.Files[i] = v.Clone()
		}
	}
	return &y
}

// Unmarshal replaces x with the decoded message and owns all decoded bytes.
func (x *GenerateResponse) Unmarshal(b []byte) error {
	if x == nil {
		return errNil
	}
	x.Reset()
	return x.unmarshal(b, maxDepth)
}
func (x *GenerateResponse) unmarshal(b []byte, depth int) error {
	if depth <= 0 {
		return errDepth
	}
	for len(b) > 0 {
		original := b
		number, wire, n, err := consumeTag(b)
		if err != nil {
			return err
		}
		b = b[n:]
		switch {
		case number == 1 && wire == 2:
			v, n, err := consumeBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			m := new(File)
			if err := m.unmarshal(v, depth-1); err != nil {
				return err
			}
			x.Files = append(x.Files, m)
		default:
			n, err := skipField(b, number, wire, depth)
			if err != nil {
				return err
			}
			x.unknownFields = append(x.unknownFields, original[:len(original)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
}

// Marshal encodes fields in number order and preserves unknown wire bytes.
func (x *GenerateResponse) Marshal() ([]byte, error) { return x.appendTo(nil, maxDepth) }
func (x *GenerateResponse) appendTo(b []byte, depth int) ([]byte, error) {
	if x == nil {
		return b, nil
	}
	if depth <= 0 {
		return nil, errDepth
	}
	for _, v := range x.Files {
		data, err := v.appendTo(nil, depth-1)
		if err != nil {
			return nil, err
		}
		b = appendVarint(b, 10)
		b = appendBytes(b, data)
	}
	return appendUnknown(b, x.unknownFields, depth)
}
