// Command genprotocol generates sqlc's small, fixed protobuf message set. The
// official protobuf packages are build tools here; the plugin does not use them.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

type message struct {
	name string
	desc *descriptorpb.DescriptorProto
}

type generator struct {
	bytes.Buffer
	types map[string]string
}

func main() {
	schema := flag.String("schema", "codegen.proto", "pinned schema path")
	output := flag.String("out", "codegen.go", "generated Go file")
	check := flag.Bool("check", false, "check generated output without writing it")
	flag.Parse()
	if err := generate(*schema, *output, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(schema, output string, check bool) error {
	path, err := filepath.Abs(schema)
	if err != nil {
		return err
	}
	temp, err := os.MkdirTemp("", "sqlc-protocol-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(temp)
	descriptor := filepath.Join(temp, "schema.pb")
	cmd := exec.Command(protocPath(), "--proto_path="+filepath.Dir(path), "--descriptor_set_out="+descriptor, filepath.Base(path))
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("protoc: %w: %s", err, out)
	}
	data, err := os.ReadFile(descriptor)
	if err != nil {
		return err
	}
	var set descriptorpb.FileDescriptorSet
	if err := proto.Unmarshal(data, &set); err != nil {
		return err
	}
	if len(set.File) != 1 || set.File[0].GetSyntax() != "proto3" || len(set.File[0].EnumType) != 0 {
		return fmt.Errorf("expected one proto3 file without enums")
	}
	g := generator{types: map[string]string{}}
	var messages []message
	var walk func(string, string, []*descriptorpb.DescriptorProto)
	walk = func(prefix, goPrefix string, descs []*descriptorpb.DescriptorProto) {
		for _, desc := range descs {
			name := goPrefix + desc.GetName()
			full := prefix + "." + desc.GetName()
			g.types[full] = name
			messages = append(messages, message{name, desc})
			walk(full, name+"_", desc.NestedType)
		}
	}
	walk("."+set.File[0].GetPackage(), "", set.File[0].MessageType)
	g.line("// Code generated by go generate; DO NOT EDIT.")
	g.line("// Source: sqlc v1.31.1 protos/plugin/codegen.proto.")
	g.line("//go:generate go run ../internal/cmd/genprotocol -schema codegen.proto -out codegen.go")
	g.line("")
	g.line("// Package protocol implements sqlc's Generate request/response wire format.")
	g.line("// It keeps only the pinned schema, without protobuf reflection or RPC code.")
	g.line("package protocol")
	g.line("import \"unicode/utf8\"")
	for _, m := range messages {
		if err := g.message(m); err != nil {
			return err
		}
	}
	formatted, err := format.Source(g.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}
	if check {
		existing, err := os.ReadFile(output)
		if err != nil {
			return err
		}
		if !bytes.Equal(existing, formatted) {
			return fmt.Errorf("%s is stale; run go generate ./protocol", output)
		}
		return nil
	}
	return os.WriteFile(output, formatted, 0644)
}

func protocPath() string {
	if path := os.Getenv("PROTOC"); path != "" {
		return path
	}
	return "protoc"
}

func (g *generator) line(format string, args ...any) { fmt.Fprintf(&g.Buffer, format+"\n", args...) }

func goName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if part != "" {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func (g *generator) fieldType(f *descriptorpb.FieldDescriptorProto) (string, error) {
	var typ string
	switch f.GetType() {
	case descriptorpb.FieldDescriptorProto_TYPE_STRING:
		typ = "string"
	case descriptorpb.FieldDescriptorProto_TYPE_BYTES:
		typ = "[]byte"
	case descriptorpb.FieldDescriptorProto_TYPE_BOOL:
		typ = "bool"
	case descriptorpb.FieldDescriptorProto_TYPE_INT32:
		typ = "int32"
	case descriptorpb.FieldDescriptorProto_TYPE_MESSAGE:
		name, ok := g.types[f.GetTypeName()]
		if !ok {
			return "", fmt.Errorf("unknown message %s", f.GetTypeName())
		}
		typ = "*" + name
	default:
		return "", fmt.Errorf("unsupported field %s of type %s", f.GetName(), f.GetType())
	}
	if f.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED {
		if typ != "string" && !strings.HasPrefix(typ, "*") {
			return "", fmt.Errorf("unsupported repeated scalar %s", f.GetName())
		}
		typ = "[]" + typ
	}
	return typ, nil
}

func (g *generator) message(m message) error {
	if m.desc.GetOptions().GetMapEntry() || len(m.desc.OneofDecl) != 0 || len(m.desc.EnumType) != 0 || len(m.desc.Extension) != 0 {
		return fmt.Errorf("unsupported schema feature in %s", m.name)
	}
	fields := append([]*descriptorpb.FieldDescriptorProto(nil), m.desc.Field...)
	sort.Slice(fields, func(i, j int) bool { return fields[i].GetNumber() < fields[j].GetNumber() })
	g.line("type %s struct {", m.name)
	for _, f := range fields {
		typ, err := g.fieldType(f)
		if err != nil {
			return err
		}
		g.line("%s %s `json:%q`", goName(f.GetName()), typ, f.GetName()+",omitempty")
	}
	g.line("unknownFields []byte")
	g.line("}")
	g.line("func (x *%s) Reset() { *x = %s{} }", m.name, m.name)
	for _, f := range fields {
		typ, _ := g.fieldType(f)
		zero := "nil"
		switch typ {
		case "string":
			zero = `""`
		case "bool":
			zero = "false"
		case "int32":
			zero = "0"
		}
		g.line("func (x *%s) Get%s() %s { if x != nil { return x.%s }; return %s }", m.name, goName(f.GetName()), typ, goName(f.GetName()), zero)
	}
	g.line("// Clone returns a deep copy and preserves nil slices and message presence.")
	g.line("func (x *%s) Clone() *%s { if x == nil { return nil }; y := *x; y.unknownFields=cloneBytes(x.unknownFields)", m.name, m.name)
	for _, f := range fields {
		typ, _ := g.fieldType(f)
		name := goName(f.GetName())
		switch {
		case strings.HasPrefix(typ, "[]*"):
			g.line("if x.%s != nil { y.%s=make(%s,len(x.%s)); for i,v:=range x.%s { y.%s[i]=v.Clone() } }", name, name, typ, name, name, name)
		case strings.HasPrefix(typ, "*"):
			g.line("y.%s=x.%s.Clone()", name, name)
		case typ == "[]byte":
			g.line("y.%s=cloneBytes(x.%s)", name, name)
		case typ == "[]string":
			g.line("if x.%s != nil { y.%s=append([]string{}, x.%s...) }", name, name, name)
		}
	}
	g.line("return &y }")
	g.line("// Unmarshal replaces x with the decoded message and owns all decoded bytes.")
	g.line("func (x *%s) Unmarshal(b []byte) error { if x==nil{return errNil}; x.Reset(); return x.unmarshal(b,maxDepth) }", m.name)
	g.line("func (x *%s) unmarshal(b []byte, depth int) error { if depth<=0{return errDepth}; for len(b)>0 { original:=b; number,wire,n,err:=consumeTag(b); if err!=nil{return err}; b=b[n:]; switch {", m.name)
	for _, f := range fields {
		typ, _ := g.fieldType(f)
		name := goName(f.GetName())
		wire := 2
		if typ == "bool" || typ == "int32" {
			wire = 0
		}
		g.line("case number==%d && wire==%d:", f.GetNumber(), wire)
		if wire == 0 {
			g.line("v,n,err:=consumeVarint(b); if err!=nil{return err}; b=b[n:]")
			if typ == "bool" {
				g.line("x.%s=v!=0", name)
			} else {
				g.line("x.%s=int32(v)", name)
			}
			continue
		}
		g.line("v,n,err:=consumeBytes(b); if err!=nil{return err}; b=b[n:]")
		switch {
		case typ == "string":
			g.line("if !utf8.Valid(v){return errUTF8}; x.%s=string(v)", name)
		case typ == "[]string":
			g.line("if !utf8.Valid(v){return errUTF8}; x.%s=append(x.%s,string(v))", name, name)
		case typ == "[]byte":
			g.line("x.%s=cloneBytes(v)", name)
		case strings.HasPrefix(typ, "[]*"):
			g.line("m:=new(%s); if err:=m.unmarshal(v,depth-1);err!=nil{return err}; x.%s=append(x.%s,m)", typ[3:], name, name)
		case strings.HasPrefix(typ, "*"):
			g.line("if x.%s==nil {x.%s=new(%s)}; if err:=x.%s.unmarshal(v,depth-1);err!=nil{return err}", name, name, typ[1:], name)
		}
	}
	g.line("default: n,err:=skipField(b,number,wire,depth); if err!=nil{return err}; x.unknownFields=append(x.unknownFields,original[:len(original)-len(b)+n]...); b=b[n:]")
	g.line("} }; return nil }")
	g.line("// Marshal encodes fields in number order and preserves unknown wire bytes.")
	g.line("func (x *%s) Marshal() ([]byte,error) { return x.appendTo(nil,maxDepth) }", m.name)
	g.line("func (x *%s) appendTo(b []byte,depth int) ([]byte,error) { if x==nil{return b,nil}; if depth<=0{return nil,errDepth}", m.name)
	for _, f := range fields {
		typ, _ := g.fieldType(f)
		name := "x." + goName(f.GetName())
		tag := f.GetNumber()<<3 | 2
		switch {
		case typ == "bool":
			g.line("if %s { b=appendVarint(b,%d); b=append(b,1) }", name, f.GetNumber()<<3)
		case typ == "int32":
			g.line("if %s!=0 { b=appendVarint(b,%d); b=appendVarint(b,uint64(%s)) }", name, f.GetNumber()<<3, name)
		case typ == "string":
			g.line("if len(%s)>0 { if !utf8.ValidString(%s){return nil,errUTF8}; b=appendVarint(b,%d); b=appendBytes(b,[]byte(%s)) }", name, name, tag, name)
		case typ == "[]string":
			g.line("for _,v:=range %s { if !utf8.ValidString(v){return nil,errUTF8}; b=appendVarint(b,%d); b=appendBytes(b,[]byte(v)) }", name, tag)
		case typ == "[]byte":
			g.line("if len(%s)>0 { b=appendVarint(b,%d); b=appendBytes(b,%s) }", name, tag, name)
		case strings.HasPrefix(typ, "[]*"):
			g.line("for _,v:=range %s { data,err:=v.appendTo(nil,depth-1); if err!=nil{return nil,err}; b=appendVarint(b,%d); b=appendBytes(b,data) }", name, tag)
		case strings.HasPrefix(typ, "*"):
			g.line("if %s!=nil { data,err:=%s.appendTo(nil,depth-1); if err!=nil{return nil,err}; b=appendVarint(b,%d); b=appendBytes(b,data) }", name, name, tag)
		}
	}
	g.line("return appendUnknown(b,x.unknownFields,depth) }")
	return nil
}
