// Code generated by sqlc. DO NOT EDIT.

/**
 * Author describes a row in the authors table.
 */
export interface Author {
  /**
   * id corresponds to SQL column id. Integers retain SQLite's signed 64-bit precision.
   */
  id: bigint;
  /**
   * name corresponds to SQL column name.
   */
  name: string;
  /**
   * bio corresponds to SQL column bio. SQL NULL is represented by null.
   */
  bio: string | null;
}
