// Code generated by sqlc. DO NOT EDIT.

import type { QueryContext as _QueryContext } from "./runtime_common.ts";
import { codecContext as _codecContext } from "./runtime_common.ts";
import type { SqliteValue as _SqliteValue } from "./runtime_sqlite.ts";
import { decodeValue as _decodeValue, encodeValue as _encodeValue } from "./runtime_sqlite.ts";

export interface Args0 {
  id: bigint;
  name: string;
  bio: string | null;
}

export function bind0(args: Args0, _q: _QueryContext) {
  return [
    _encodeValue("integer", args.id, false, _codecContext(_q, f1)),
    _encodeValue("string", args.name, false, _codecContext(_q, f2)),
    _encodeValue("string", args.bio, true, _codecContext(_q, f3)),
  ] as const;
}

export interface Row1 {
  id: bigint;
  name: string;
  bio: string | null;
}

export function read1(row: [_SqliteValue, _SqliteValue, _SqliteValue], _q: _QueryContext): Row1 {
  if (row.length !== 3) throw new Error("SQL result column count does not match the generated query");
  return {
    id: _decodeValue<bigint>("integer", row[0], false, false, _codecContext(_q, f1)),
    name: _decodeValue<string>("string", row[1], false, false, _codecContext(_q, f2)),
    bio: _decodeValue<string | null>("string", row[2], true, false, _codecContext(_q, f3)),
  };
}

export interface Args2 {
  id: bigint;
}

export function bind2(args: Args2, _q: _QueryContext) {
  return [
    _encodeValue("integer", args.id, false, _codecContext(_q, f1)),
  ] as const;
}

export const f0 = ["rowsAffected", "bigint"] as const;
export const f1 = ["id", "bigint"] as const;
export const f2 = ["name", "string"] as const;
export const f3 = ["bio", "string | null"] as const;
