// Code generated by sqlc. DO NOT EDIT.

import type { Args0 as _Args0, Args2 as _Args2, Row1 as _Row1 } from "./query_helpers.ts";
import { bind0 as _bind0, bind2 as _bind2, f0 as _f0, read1 as _read1 } from "./query_helpers.ts";
import { withCodecContext as _withCodecContext } from "./runtime_common.ts";
import { queryMany as _queryMany, queryOne as _queryOne, runQuery as _runQuery } from "./runtime_sqlite.ts";
import type { Database as _Database } from "@bonakodo/sqlite";

const _file = "query.sql";

export const createAuthorQuery = `-- name: CreateAuthor :one
INSERT INTO authors (id, name, bio)
VALUES (?, ?, ?) RETURNING id, name, bio`;

export interface CreateAuthorArgs extends _Args0 {}

export interface CreateAuthorRow extends _Row1 {}

export function createAuthor(database: _Database, args: CreateAuthorArgs): CreateAuthorRow | null {
  const _q = ["CreateAuthor", _file] as const;
  const _sqlcBindings = _bind0(args, _q);
  return _queryOne(database, createAuthorQuery, _sqlcBindings, _read1, _q, null);
}

export const deleteAuthorQuery = `-- name: DeleteAuthor :execrows
DELETE FROM authors WHERE id = ?`;

export interface DeleteAuthorArgs extends _Args2 {}

export function deleteAuthor(database: _Database, args: DeleteAuthorArgs): bigint {
  const _q = ["DeleteAuthor", _file] as const;
  const _sqlcBindings = _bind2(args, _q);
  return _runQuery(database, deleteAuthorQuery, _sqlcBindings, (result) => {
    return _withCodecContext(_q, "decode", () => BigInt(result.changes), _f0);
  });
}

export const listAuthorsQuery = `-- name: ListAuthors :many
SELECT id, name, bio FROM authors ORDER BY id`;

export interface ListAuthorsRow extends _Row1 {}

export function listAuthors(database: _Database): ListAuthorsRow[] {
  const _q = ["ListAuthors", _file] as const;
  return _queryMany(database, listAuthorsQuery, [], _read1, _q);
}
