// Code generated by sqlc. DO NOT EDIT.

import type { Args3gWIBC as _Args3gWIBC, ArgsZNu5z as _ArgsZNu5z, Row3gWIBC as _Row3gWIBC } from "./query_helpers.ts";
import { bind3gWIBC as _bind3gWIBC, bindZNu5z as _bindZNu5z, read3gWIBC as _read3gWIBC } from "./query_helpers.ts";
import { queryMany as _queryMany, queryOne as _queryOne, readRowsAffected as _readRowsAffected, runQuery as _runQuery } from "./runtime_sqlite.ts";
import type { Database as _Database } from "@bonakodo/sqlite";

const _file = "query.sql";

export const createAuthorQuery = `-- name: CreateAuthor :one
INSERT INTO authors (id, name, bio)
VALUES (?, ?, ?) RETURNING id, name, bio`;

export interface CreateAuthorArgs extends _Args3gWIBC {}

export interface CreateAuthorRow extends _Row3gWIBC {}

export function createAuthor(database: _Database, args: CreateAuthorArgs): CreateAuthorRow | null {
  const _q = ["CreateAuthor", _file] as const;
  return _queryOne(database, createAuthorQuery, _bind3gWIBC(args, _q), _read3gWIBC, _q, null);
}

export const deleteAuthorQuery = `-- name: DeleteAuthor :execrows
DELETE FROM authors WHERE id = ?`;

export interface DeleteAuthorArgs extends _ArgsZNu5z {}

export function deleteAuthor(database: _Database, args: DeleteAuthorArgs): bigint {
  const _q = ["DeleteAuthor", _file] as const;
  return _runQuery(database, deleteAuthorQuery, _bindZNu5z(args, _q), _readRowsAffected, _q);
}

export const listAuthorsQuery = `-- name: ListAuthors :many
SELECT id, name, bio FROM authors ORDER BY id`;

export interface ListAuthorsRow extends _Row3gWIBC {}

export function listAuthors(database: _Database): ListAuthorsRow[] {
  const _q = ["ListAuthors", _file] as const;
  return _queryMany(database, listAuthorsQuery, [], _read3gWIBC, _q);
}
