// Code generated by sqlc. DO NOT EDIT.

import type { Database } from "@bonakodo/sqlite";
export type { Database };



import type { CodecContext } from "./runtime_common.ts";

import type { QueryContext } from "./runtime_common.ts";

import type { FieldContext } from "./runtime_common.ts";

import { throwCodecError } from "./runtime_common.ts";

export type SqliteValue = null | string | number | bigint | Uint8Array;

export type Kind =
  | "integer"
  | "sqlite-integer"
  | "number"
  | "boolean"
  | "date"
  | "bytes"
  | "json"
  | "string"
  | "unknown";

const minInt64 = -(1n << 63n);

const maxInt64 = (1n << 63n) - 1n;

function integer(value: unknown): bigint {
  if (typeof value === "number") {
    if (!Number.isSafeInteger(value)) {
      throw new TypeError("Expected a safe integer number or bigint");
    }
    value = BigInt(value);
  }
  if (typeof value !== "bigint") {
    throw new TypeError("Expected a SQLite integer");
  }
  if (value < minInt64 || value > maxInt64) {
    throw new RangeError("Integer exceeds SQLite's signed 64-bit range");
  }
  return value;
}

function encodeValueUnchecked(
  kind: Kind,
  value: unknown,
  nullable = true,
): SqliteValue {
  if (!nullable && (value === null || value === undefined)) {
    throw new TypeError("Missing a non-null argument");
  }
  if (value === null || value === undefined) return null;
  switch (kind) {
    case "integer":
      return integer(value);
    case "string":
      if (typeof value !== "string") throw new TypeError("Expected a string");
      return value;
  }
  throw new TypeError("SQL kind is not used by these queries: " + kind);
}

function decodeValueUnchecked<T>(
  kind: Kind,
  value: SqliteValue,
  nullable: boolean,
  undefinedNull: boolean,
): T {
  if (value === null) {
    if (!nullable) {
      throw new TypeError("Unexpected SQL NULL in a non-null column");
    }
    return (undefinedNull ? undefined : null) as T;
  }
  let result: unknown;
  switch (kind) {
    case "integer":
      result = integer(value);
      break;
    case "string":
      if (typeof value !== "string") {
        throw new TypeError("Expected SQLite text");
      }
      result = value;
      break;
    default:
      throw new TypeError("SQL kind is not used by these queries: " + kind);
  }
  return result as T;
}

type DriverValue = SqliteValue;

export function encodeValue(
  kind: Kind,
  value: unknown,
  nullable = true,
  context?: CodecContext | QueryContext,
  field?: FieldContext,
): DriverValue {
  try {
    return encodeValueUnchecked(kind, value, nullable);
  } catch (cause) {
    throwCodecError(cause, "encode", context, field);
  }
}

export function decodeValue<T>(
  kind: Kind,
  value: DriverValue,
  nullable: boolean,
  undefinedNull: boolean,
  context?: CodecContext | QueryContext,
  field?: FieldContext,
): T {
  try {
    return decodeValueUnchecked<T>(kind, value, nullable, undefinedNull);
  } catch (cause) {
    throwCodecError(cause, "decode", context, field);
  }
}

interface StatementLease {
  statement: ReturnType<Database["prepare"]>;
  cache: StatementCache;
  key: string | undefined;
  active: boolean;
  discard: boolean;
}

interface StatementCache {
  capacity: number;
  entries: Map<string, StatementLease>;
}

const statementCaches = new WeakMap<Database, StatementCache>();

function statementCache(database: Database): StatementCache {
  let cache = statementCaches.get(database);
  if (cache === undefined) {
    cache = { capacity: 16, entries: new Map() };
    statementCaches.set(database, cache);
  }
  return cache;
}

function discardStatement(lease: StatementLease): void {
  lease.discard = true;
  // Keep ownership if the driver rejects disposal (for example, a clear from
  // a SQLite callback). A later clear can retry; the marked handle cannot run.
  lease.statement[Symbol.dispose]();
  if (lease.key !== undefined && lease.cache.entries.get(lease.key) === lease) {
    lease.cache.entries.delete(lease.key);
  }
}

function trimStatementCache(cache: StatementCache, limit: number): void {
  if (cache.entries.size <= limit) return;
  let failed = false;
  let failure: unknown;
  for (const lease of cache.entries.values()) {
    if (cache.entries.size <= limit) break;
    if (lease.active) continue;
    try {
      discardStatement(lease);
    } catch (error) {
      if (!failed) { failed = true; failure = error; }
    }
  }
  if (failed) throw failure;
}

export function configureStatementCache(database: Database, capacity: number): void {
  if (!Number.isSafeInteger(capacity) || capacity < 0) {
    throw new RangeError("Statement cache capacity must be a nonnegative safe integer");
  }
  const cache = statementCache(database);
  cache.capacity = capacity;
  if (capacity === 0) clearStatementCache(database);
  else trimStatementCache(cache, capacity);
}

export function clearStatementCache(database: Database): void {
  const cache = statementCaches.get(database);
  if (cache === undefined) return;
  for (const lease of cache.entries.values()) lease.discard = true;
  trimStatementCache(cache, 0);
}

function acquireStatement(database: Database, sql: string, rows: boolean): StatementLease {
  const cache = statementCache(database);
  // Database.close() finalizes handles. Keep its own closed-connection error
  // when the next prepare runs, and drop references to those stale handles.
  if (database.open === false) clearStatementCache(database);
  const key = cache.capacity === 0 ? undefined : (rows ? "rows:" : "run:") + sql;
  const found = key === undefined ? undefined : cache.entries.get(key);
  if (key !== undefined && found !== undefined && !found.active && !found.discard && cache.capacity > 0) {
    cache.entries.delete(key);
    cache.entries.set(key, found);
    found.active = true;
    return found;
  }
  // Same-key recursion cannot replace its active owner. Under pressure, use
  // a temporary handle and finalize it at call exit; never wait on a lease.
  if (found === undefined && cache.capacity > 0) trimStatementCache(cache, cache.capacity - 1);
  const statement = database.prepare(sql);
  try {
    statement.safeIntegers();
    if (rows) statement.raw();
  } catch (error) {
    statement[Symbol.dispose]();
    throw error;
  }
  const lease: StatementLease = {
    statement, cache, key, active: true,
    discard: found !== undefined || cache.entries.size >= cache.capacity,
  };
  if (key !== undefined && !lease.discard) cache.entries.set(key, lease);
  return lease;
}

function releaseStatement(lease: StatementLease, success: boolean): void {
  lease.active = false;
  // get/all/run already reset and clear transient bindings before returning.
  // Any reported execution/reset/conversion error discards; never replay SQL.
  if (!success || lease.discard || lease.cache.capacity === 0) {
    discardStatement(lease);
  } else {
    trimStatementCache(lease.cache, lease.cache.capacity);
  }
}

export function queryOne<
  R extends SqliteValue[],
  T,
  C,
  N extends null | undefined,
>(
  database: Database,
  sql: string,
  params: readonly SqliteValue[],
  read: (row: R, context: C) => T,
  context: C,
  missing: N,
): T | N {
  const lease = acquireStatement(database, sql, true);
  let success = false;
  try {
    const stmt = lease.statement;
    const row = stmt.get(params) as unknown as R | undefined;
    const result = row === undefined ? missing : read(row, context);
    success = true;
    return result;
  } finally {
    releaseStatement(lease, success);
  }
}

export function queryMany<R extends SqliteValue[], T, C>(
  database: Database,
  sql: string,
  params: readonly SqliteValue[],
  read: (row: R, context: C) => T,
  context: C,
): T[] {
  const lease = acquireStatement(database, sql, true);
  let success = false;
  try {
    const stmt = lease.statement;
    const rows = stmt.all(params) as unknown as R[];
    const result = rows.map((row) => read(row, context));
    success = true;
    return result;
  } finally {
    releaseStatement(lease, success);
  }
}

export function runQuery<T>(
  database: Database,
  sql: string,
  params: readonly SqliteValue[],
  read: (result: SqliteRunResult, context?: QueryContext) => T,
  context?: QueryContext,
): T {
  const lease = acquireStatement(database, sql, false);
  let success = false;
  try {
    const stmt = lease.statement;
    const result = read(stmt.run(params), context);
    success = true;
    return result;
  } finally {
    releaseStatement(lease, success);
  }
}

type SqliteRunResult = ReturnType<ReturnType<Database["prepare"]>["run"]>;

const rowsAffectedField: FieldContext = ["rowsAffected", "bigint"];

export function readRowsAffected(result: SqliteRunResult, context?: QueryContext): bigint {
  try {
    return BigInt(result.changes);
  } catch (cause) {
    throwCodecError(cause, "decode", context, rowsAffectedField);
  }
}
