// Code generated by sqlc. DO NOT EDIT.

import type { Database } from "@bonakodo/sqlite";
export type { Database };


import type { JsonValue } from "./json.ts";
import { type CodecContext, withCodecContext } from "./codec_error.ts";
export {
  encodeSlice,
  QueryCodecError,
  withCodecContext,
} from "./codec_error.ts";
export type { CodecContext } from "./codec_error.ts";

function checkedJson(
  value: unknown,
  numberError = "Expected a JSON value",
): JsonValue {
  const ancestors = new Set<object>();
  const visit = (item: unknown): void => {
    if (
      item === null || typeof item === "string" || typeof item === "boolean"
    ) {
      return;
    }
    if (typeof item === "number") {
      if (!Number.isFinite(item)) {
        throw new TypeError(numberError);
      }
      return;
    }
    if (typeof item !== "object") throw new TypeError("Expected a JSON value");
    if (ancestors.has(item)) {
      throw new TypeError("Expected JSON without cycles");
    }
    const array = Array.isArray(item);
    if (
      !array && Object.getPrototypeOf(item) !== Object.prototype &&
      Object.getPrototypeOf(item) !== null
    ) {
      throw new TypeError("Expected a plain JSON object");
    }
    ancestors.add(item);
    for (const child of array ? item : Object.values(item)) visit(child);
    ancestors.delete(item);
  };
  visit(value);
  return value as JsonValue;
}

export type SqliteValue = null | string | number | bigint | Uint8Array;

export interface SqliteCodec<T> {
  encode(value: T): SqliteValue;
  decode(value: SqliteValue): T;
}

export interface ExecResult {
  rowsAffected: bigint;
  lastInsertId: bigint;
}

export type Kind =
  | "integer"
  | "sqlite-integer"
  | "number"
  | "boolean"
  | "date"
  | "bytes"
  | "json"
  | "string"
  | "unknown";

const minInt64 = -(1n << 63n);

const maxInt64 = (1n << 63n) - 1n;

const utf8 = new TextEncoder();

function integer(value: unknown): bigint {
  if (typeof value === "number") {
    if (!Number.isSafeInteger(value)) {
      throw new TypeError("Expected a safe integer number or bigint");
    }
    value = BigInt(value);
  }
  if (typeof value !== "bigint") {
    throw new TypeError("Expected a SQLite integer");
  }
  if (value < minInt64 || value > maxInt64) {
    throw new RangeError("Integer exceeds SQLite's signed 64-bit range");
  }
  return value;
}

function finiteNumber(value: unknown): number {
  if (typeof value === "bigint") value = Number(integer(value));
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new TypeError("Expected a finite SQLite number");
  }
  return value;
}

function dateValue(value: unknown): Date {
  if (typeof value !== "string") {
    throw new TypeError(
      "Expected date text; numeric timestamps need a custom codec",
    );
  }
  const match =
    /^([+-]\d{6}|\d{4})-(\d{2})-(\d{2})(?:[ T](\d{2}):(\d{2})(?::(\d{2})(?:\.(\d+))?)?(Z|[+-]\d{2}:\d{2})?)?$/
      .exec(value);
  if (match === null) throw new TypeError("Invalid SQLite date text");
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = Number(match[4] ?? 0);
  const minute = Number(match[5] ?? 0);
  const second = Number(match[6] ?? 0);
  const millisecond = Number((match[7] ?? "").padEnd(3, "0").slice(0, 3));
  const zone = match[8] ?? "Z";
  if (
    month < 1 || month > 12 || day < 1 || day > 31 || hour > 23 ||
    minute > 59 || second > 59
  ) {
    throw new TypeError("Invalid SQLite date fields");
  }
  const date = new Date(0);
  date.setUTCFullYear(year, month - 1, day);
  date.setUTCHours(hour, minute, second, millisecond);
  if (
    !Number.isFinite(date.getTime()) || date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 || date.getUTCDate() !== day
  ) {
    throw new TypeError("Invalid SQLite calendar date");
  }
  if (zone !== "Z") {
    const zoneHour = Number(zone.slice(1, 3));
    const zoneMinute = Number(zone.slice(4, 6));
    if (zoneHour > 23 || zoneMinute > 59) {
      throw new TypeError("Invalid SQLite date offset");
    }
    const sign = zone.startsWith("+") ? 1 : -1;
    date.setTime(date.getTime() - sign * (zoneHour * 60 + zoneMinute) * 60_000);
    if (!Number.isFinite(date.getTime())) {
      throw new TypeError("SQLite date exceeds Date's range");
    }
  }
  return date;
}

function encodeValueUnchecked(
  kind: Kind,
  value: unknown,
  nullable = true,
): SqliteValue {
  if (!nullable && (value === null || value === undefined)) {
    throw new TypeError("Missing a non-null argument");
  }
  if (value === null || value === undefined) return null;
  switch (kind) {
    case "sqlite-integer":
      if (typeof value === "bigint") return integer(value);
      if (typeof value === "number" && Number.isFinite(value)) {
        if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
          throw new TypeError("Expected a safe integer number or bigint");
        }
        return value;
      }
      throw new TypeError("Expected a SQLite number or bigint");
    case "integer":
      return integer(value);
    case "number": {
      if (typeof value !== "number") {
        throw new TypeError("Expected a finite JavaScript number");
      }
      const number = finiteNumber(value);
      return Number.isInteger(number) && !Number.isSafeInteger(number)
        ? String(number)
        : number;
    }
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("Expected a boolean");
      return value ? 1 : 0;
    case "date":
      if (!(value instanceof Date) || !Number.isFinite(value.getTime())) {
        throw new TypeError("Expected a valid Date");
      }
      return value.toISOString();
    case "bytes":
    case "json":
      if (!(value instanceof Uint8Array)) {
        throw new TypeError("Expected Uint8Array");
      }
      return value;
    case "string":
      if (typeof value !== "string") throw new TypeError("Expected a string");
      return value;
    case "unknown":
      if (typeof value === "bigint") return integer(value);
      if (typeof value === "number") {
        if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
          throw new TypeError(
            "Expected a number without unsafe integer rounding",
          );
        }
        return finiteNumber(value);
      }
      if (typeof value === "string" || value instanceof Uint8Array) {
        return value;
      }
      throw new TypeError("Expected a SQLite scalar value");
  }
}

function decodeValueUnchecked<T>(
  kind: Kind,
  value: SqliteValue,
  nullable: boolean,
  undefinedNull: boolean,
): T {
  if (value === null) {
    if (!nullable) {
      throw new TypeError("Unexpected SQL NULL in a non-null column");
    }
    return (undefinedNull ? undefined : null) as T;
  }
  let result: unknown;
  switch (kind) {
    case "sqlite-integer":
      if (typeof value !== "number" && typeof value !== "bigint") {
        throw new TypeError("Expected a SQLite number or bigint");
      }
      result = typeof value === "bigint" ? integer(value) : finiteNumber(value);
      if (typeof result === "bigint" && Number.isSafeInteger(Number(result))) {
        result = Number(result);
      }
      break;
    case "integer":
      result = integer(value);
      break;
    case "number":
      result = finiteNumber(value);
      break;
    case "boolean":
      if (value !== 0 && value !== 1 && value !== 0n && value !== 1n) {
        throw new TypeError("Expected SQLite boolean 0 or 1");
      }
      result = value === 1 || value === 1n;
      break;
    case "date":
      result = dateValue(value);
      break;
    case "json":
      if (typeof value === "string") {
        result = utf8.encode(value);
        break;
      }
      if (!(value instanceof Uint8Array)) {
        throw new TypeError("Expected raw JSON text or bytes");
      }
      result = value;
      break;
    case "bytes":
      if (!(value instanceof Uint8Array)) {
        throw new TypeError("Expected SQLite bytes");
      }
      result = value;
      break;
    case "string":
      if (typeof value !== "string") {
        throw new TypeError("Expected SQLite text");
      }
      result = value;
      break;
    case "unknown":
      if (typeof value === "bigint") result = integer(value);
      else if (typeof value === "number") result = finiteNumber(value);
      else if (typeof value === "string" || value instanceof Uint8Array) {
        result = value;
      } else throw new TypeError("Expected a SQLite scalar value");
      break;
  }
  return result as T;
}

function encodeCustomUnchecked<T>(
  codec: SqliteCodec<T>,
  value: unknown,
  nullable: boolean,
): SqliteValue {
  if (
    value === undefined ||
    (value === null && (nullable || !jsonCodecs.has(codec)))
  ) {
    if (!nullable) throw new TypeError("Missing a non-null custom argument");
    return null;
  }
  const encoded = encodeValue("unknown", codec.encode(value as T));
  if (encoded === null && !nullable) {
    throw new TypeError("Codec returned NULL for a non-null argument");
  }
  return encoded;
}

function decodeCustomUnchecked<T>(
  codec: SqliteCodec<T>,
  value: SqliteValue,
  nullable: boolean,
  undefinedNull: boolean,
): T {
  if (value === null) {
    if (!nullable) {
      throw new TypeError("Unexpected SQL NULL in a non-null custom column");
    }
    return (undefinedNull ? undefined : null) as T;
  }
  return codec.decode(value);
}

export const safeInteger: SqliteCodec<number> = {
  encode(value) {
    if (typeof value !== "number" || !Number.isSafeInteger(value)) {
      throw new TypeError("Expected a safe integer number");
    }
    return BigInt(value);
  },
  decode(value) {
    const result = Number(integer(value));
    if (!Number.isSafeInteger(result)) {
      throw new RangeError("SQLite integer exceeds JavaScript's safe range");
    }
    return result;
  },
};

export const epochMilliseconds: SqliteCodec<Date> = {
  encode(value) {
    if (!(value instanceof Date)) throw new TypeError("Expected a valid Date");
    return safeInteger.encode(value.getTime());
  },
  decode(value) {
    const result = new Date(safeInteger.decode(value));
    if (!Number.isFinite(result.getTime())) {
      throw new RangeError("SQLite timestamp exceeds Date's range");
    }
    return result;
  },
};

export const sqliteBoolean: SqliteCodec<boolean> = {
  encode(value) {
    if (typeof value !== "boolean") throw new TypeError("Expected a boolean");
    return value ? 1 : 0;
  },
  decode(value) {
    if (value !== 0 && value !== 1 && value !== 0n && value !== 1n) {
      throw new TypeError("Expected SQLite boolean 0 or 1");
    }
    return value === 1 || value === 1n;
  },
};

const jsonCodecs = new WeakSet<object>();

export const jsonText = {
  encode(value: unknown): SqliteValue {
    return JSON.stringify(checkedJson(value));
  },
  decode<T = JsonValue>(value: SqliteValue): T {
    if (typeof value !== "string") {
      throw new TypeError("Expected SQLite JSON text");
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(value);
    } catch {
      // JSON.parse errors can include excerpts of the original document.
      throw new TypeError("Invalid SQLite JSON text");
    }
    return checkedJson(parsed) as T;
  },
};
jsonCodecs.add(jsonText);

export function createJsonTextCodec<T>(
  parse: (value: unknown) => T,
): SqliteCodec<T> {
  const codec: SqliteCodec<T> = {
    encode(value) {
      return jsonText.encode(parse(value));
    },
    decode(value) {
      return parse(jsonText.decode(value));
    },
  };
  jsonCodecs.add(codec);
  return codec;
}

type DriverValue = SqliteValue;
type DriverCodec<T> = SqliteCodec<T>;

export function lastInsertId(database: Database): bigint {
  const statement = database.prepare("SELECT last_insert_rowid()");
  try {
    statement.safeIntegers();
    const row = statement.raw().get();
    if (row === undefined) {
      throw new Error("SQLite did not return last_insert_rowid()");
    }
    return integer(row[0]);
  } finally {
    statement[Symbol.dispose]();
  }
}



export function encodeValue(
  kind: Kind,
  value: unknown,
  nullable = true,
  context?: CodecContext,
): DriverValue {
  return withCodecContext(
    context,
    "encode",
    () => encodeValueUnchecked(kind, value, nullable),
  );
}

export function decodeValue<T>(
  kind: Kind,
  value: DriverValue,
  nullable: boolean,
  undefinedNull: boolean,
  context?: CodecContext,
): T {
  return withCodecContext(
    context,
    "decode",
    () => decodeValueUnchecked<T>(kind, value, nullable, undefinedNull),
  );
}

export function encodeCustom<T>(
  codec: DriverCodec<T>,
  value: unknown,
  nullable: boolean,
  context?: CodecContext,
): DriverValue {
  return withCodecContext(
    context,
    "encode",
    () => encodeCustomUnchecked(codec, value, nullable),
  );
}

export function decodeCustom<T>(
  codec: DriverCodec<T>,
  value: DriverValue,
  nullable: boolean,
  undefinedNull: boolean,
  context?: CodecContext,
): T {
  return withCodecContext(
    context,
    "decode",
    () => decodeCustomUnchecked(codec, value, nullable, undefinedNull),
  );
}
