// Code generated by sqlc. DO NOT EDIT.
// This runtime targets Deno and @bonakodo/sqlite.

import type { Database } from "@bonakodo/sqlite";

/** SqliteValue is a bound or returned SQLite value before application conversion. */
export type SqliteValue = null | string | number | bigint | Uint8Array;

/** SqliteCodec converts a non-null custom type to and from SQLite values. */
export interface SqliteCodec<T> {
  /** encode returns a SQLite value; throw when the application value is invalid. */
  encode(value: T): SqliteValue;
  /** decode returns an application value; throw when the stored value is invalid. */
  decode(value: SqliteValue): T;
}

/** ExecResult reports changes and the connection's inserted row ID after a query. */
export interface ExecResult {
  /** rowsAffected counts rows directly changed by this statement. */
  rowsAffected: bigint;
  /** lastInsertId is the connection's last inserted row ID, read without rounding. */
  lastInsertId: bigint;
}

/** Kind names the built-in conversion selected from a SQLite column declaration. */
export type Kind =
  | "integer"
  | "sqlite-integer"
  | "number"
  | "boolean"
  | "date"
  | "bytes"
  | "json"
  | "string"
  | "unknown";

/** minInt64 is the smallest integer that SQLite can store without overflow. */
const minInt64 = -(1n << 63n);

/** maxInt64 is the largest integer that SQLite can store without overflow. */
const maxInt64 = (1n << 63n) - 1n;

/** utf8 converts stored JSON text to bytes without parsing or rewriting JSON. */
const utf8 = new TextEncoder();

/**
 * integer validates SQLite's signed 64-bit range and returns a bigint.
 * Safe integer numbers are also accepted for bindings and custom codecs.
 * @throws {TypeError} For non-integers or already-rounded JavaScript numbers.
 * @throws {RangeError} For values outside SQLite's signed 64-bit range.
 */
function integer(value: unknown): bigint {
  if (typeof value === "number") {
    if (!Number.isSafeInteger(value)) {
      throw new TypeError("Expected a safe integer number or bigint");
    }
    value = BigInt(value);
  }
  if (typeof value !== "bigint") {
    throw new TypeError("Expected a SQLite integer");
  }
  if (value < minInt64 || value > maxInt64) {
    throw new RangeError("Integer exceeds SQLite's signed 64-bit range");
  }
  return value;
}

/**
 * finiteNumber validates a REAL or NUMERIC value and returns a JavaScript number.
 * A stored integer uses number precision under this mapping; use an integer
 * column or a custom codec when the application needs exact integer arithmetic.
 * Text remains invalid here. Generated CAST placeholders convert temporary
 * decimal text in SQLite before a result reaches this decoder.
 * @throws {TypeError} For values other than finite numbers or bigints.
 */
function finiteNumber(value: unknown): number {
  if (typeof value === "bigint") value = Number(integer(value));
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new TypeError("Expected a finite SQLite number");
  }
  return value;
}

/**
 * dateValue decodes ISO or SQLite date/time text, treating absent zones as UTC.
 * It validates the calendar before conversion; Date's parser alone normalizes
 * invalid dates such as February 30. Fractions beyond milliseconds are dropped
 * because JavaScript Date stores only millisecond precision.
 * @throws {TypeError} For numeric timestamps, invalid dates, or unsupported text.
 */
function dateValue(value: unknown): Date {
  if (typeof value !== "string") {
    throw new TypeError(
      "Expected date text; numeric timestamps need a custom codec",
    );
  }
  const match =
    /^([+-]\d{6}|\d{4})-(\d{2})-(\d{2})(?:[ T](\d{2}):(\d{2})(?::(\d{2})(?:\.(\d+))?)?(Z|[+-]\d{2}:\d{2})?)?$/
      .exec(value);
  if (match === null) throw new TypeError("Invalid SQLite date text");
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = Number(match[4] ?? 0);
  const minute = Number(match[5] ?? 0);
  const second = Number(match[6] ?? 0);
  const millisecond = Number((match[7] ?? "").padEnd(3, "0").slice(0, 3));
  const zone = match[8] ?? "Z";
  if (
    month < 1 || month > 12 || day < 1 || day > 31 || hour > 23 ||
    minute > 59 || second > 59
  ) {
    throw new TypeError("Invalid SQLite date fields");
  }
  const date = new Date(0);
  date.setUTCFullYear(year, month - 1, day);
  date.setUTCHours(hour, minute, second, millisecond);
  if (
    !Number.isFinite(date.getTime()) || date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 || date.getUTCDate() !== day
  ) {
    throw new TypeError("Invalid SQLite calendar date");
  }
  if (zone !== "Z") {
    const zoneHour = Number(zone.slice(1, 3));
    const zoneMinute = Number(zone.slice(4, 6));
    if (zoneHour > 23 || zoneMinute > 59) {
      throw new TypeError("Invalid SQLite date offset");
    }
    const sign = zone.startsWith("+") ? 1 : -1;
    date.setTime(date.getTime() - sign * (zoneHour * 60 + zoneMinute) * 60_000);
    if (!Number.isFinite(date.getTime())) {
      throw new TypeError("SQLite date exceeds Date's range");
    }
  }
  return date;
}

/**
 * encodeValue converts one application value for SQLite binding.
 * Null and undefined bind as SQL NULL. Dates use UTC ISO text with millisecond
 * precision; JSON remains raw bytes. The returned byte array retains ownership
 * with the caller and must not change during the synchronous statement call.
 * Integer-valued REAL inputs outside JavaScript's safe integer range use decimal
 * text with the generator's CAST placeholder to preserve the shared REAL
 * binding representation across SQLite drivers.
 * SQLite's decimal conversion can round a huge value by one floating-point step;
 * fractional and subnormal inputs stay numeric to avoid that conversion.
 * @throws {TypeError} For invalid types, dates, nonfinite numbers, or unsafe
 * integer numbers supplied without a declared REAL/NUMERIC representation.
 * @throws {RangeError} For integers outside SQLite's signed 64-bit range.
 */
export function encodeValue(kind: Kind, value: unknown): SqliteValue {
  if (value === null || value === undefined) return null;
  switch (kind) {
    case "sqlite-integer":
      if (typeof value === "bigint") return integer(value);
      if (typeof value === "number" && Number.isFinite(value)) {
        if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
          throw new TypeError("Expected a safe integer number or bigint");
        }
        return value;
      }
      throw new TypeError("Expected a SQLite number or bigint");
    case "integer":
      return integer(value);
    case "number": {
      if (typeof value !== "number") {
        throw new TypeError("Expected a finite JavaScript number");
      }
      const number = finiteNumber(value);
      return Number.isInteger(number) && !Number.isSafeInteger(number)
        ? String(number)
        : number;
    }
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("Expected a boolean");
      return value ? 1 : 0;
    case "date":
      if (!(value instanceof Date) || !Number.isFinite(value.getTime())) {
        throw new TypeError("Expected a valid Date");
      }
      return value.toISOString();
    case "bytes":
    case "json":
      if (!(value instanceof Uint8Array)) {
        throw new TypeError("Expected Uint8Array");
      }
      return value;
    case "string":
      if (typeof value !== "string") throw new TypeError("Expected a string");
      return value;
    case "unknown":
      if (typeof value === "bigint") return integer(value);
      if (typeof value === "number") {
        if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
          throw new TypeError(
            "Expected a number without unsafe integer rounding",
          );
        }
        return finiteNumber(value);
      }
      if (typeof value === "string" || value instanceof Uint8Array) {
        return value;
      }
      throw new TypeError("Expected a SQLite scalar value");
  }
}

/**
 * decodeValue converts a SQLite result using its declared type and null policy.
 * The generator selects T from the same type mapping as kind. Integers always
 * become bigint; JSON text becomes UTF-8 bytes without parsing. Dates use UTC
 * for missing zones and retain millisecond precision. Returned bytes belong to
 * the result, so callers may retain them after the statement is finalized.
 * @throws {TypeError} For unexpected NULL, invalid stored types, or invalid dates.
 * @throws {RangeError} For stored integers outside SQLite's signed 64-bit range.
 */
export function decodeValue<T>(
  kind: Kind,
  value: SqliteValue,
  nullable: boolean,
  undefinedNull: boolean,
): T {
  if (value === null) {
    if (!nullable) {
      throw new TypeError("Unexpected SQL NULL in a non-null column");
    }
    return (undefinedNull ? undefined : null) as T;
  }
  let result: unknown;
  switch (kind) {
    case "sqlite-integer":
      if (typeof value !== "number" && typeof value !== "bigint") {
        throw new TypeError("Expected a SQLite number or bigint");
      }
      result = typeof value === "bigint" ? integer(value) : finiteNumber(value);
      if (typeof result === "bigint" && Number.isSafeInteger(Number(result))) {
        result = Number(result);
      }
      break;
    case "integer":
      result = integer(value);
      break;
    case "number":
      result = finiteNumber(value);
      break;
    case "boolean":
      if (value !== 0 && value !== 1 && value !== 0n && value !== 1n) {
        throw new TypeError("Expected SQLite boolean 0 or 1");
      }
      result = value === 1 || value === 1n;
      break;
    case "date":
      result = dateValue(value);
      break;
    case "json":
      if (typeof value === "string") {
        result = utf8.encode(value);
        break;
      }
      if (!(value instanceof Uint8Array)) {
        throw new TypeError("Expected raw JSON text or bytes");
      }
      result = value;
      break;
    case "bytes":
      if (!(value instanceof Uint8Array)) {
        throw new TypeError("Expected SQLite bytes");
      }
      result = value;
      break;
    case "string":
      if (typeof value !== "string") {
        throw new TypeError("Expected SQLite text");
      }
      result = value;
      break;
    case "unknown":
      if (typeof value === "bigint") result = integer(value);
      else if (typeof value === "number") result = finiteNumber(value);
      else if (typeof value === "string" || value instanceof Uint8Array) {
        result = value;
      } else throw new TypeError("Expected a SQLite scalar value");
      break;
  }
  return result as T;
}

/**
 * encodeCustom applies a custom codec to a non-null argument and checks its SQL
 * value. Nullable null and undefined arguments bypass the codec and bind NULL.
 * @throws {TypeError} For missing required values or unsupported encoded values.
 * @throws Propagates codec errors and signed 64-bit range errors.
 */
export function encodeCustom<T>(
  codec: SqliteCodec<T>,
  value: unknown,
  nullable: boolean,
): SqliteValue {
  if (value === null || value === undefined) {
    if (!nullable) throw new TypeError("Missing a non-null custom argument");
    return null;
  }
  const encoded = encodeValue("unknown", codec.encode(value as T));
  if (encoded === null && !nullable) {
    throw new TypeError("Codec returned NULL for a non-null argument");
  }
  return encoded;
}

/**
 * decodeCustom applies a custom codec after handling SQL NULL. Codecs receive
 * non-null SQLite values; null output policy remains the generator's concern.
 * @throws {TypeError} For NULL in a non-null column.
 * @throws Propagates errors raised by the custom codec.
 */
export function decodeCustom<T>(
  codec: SqliteCodec<T>,
  value: SqliteValue,
  nullable: boolean,
  undefinedNull: boolean,
): T {
  if (value === null) {
    if (!nullable) {
      throw new TypeError("Unexpected SQL NULL in a non-null custom column");
    }
    return (undefinedNull ? undefined : null) as T;
  }
  return codec.decode(value);
}

/**
 * lastInsertId reads the connection's last inserted row ID without number loss.
 * It leaves database-wide options untouched and works in Database.transaction.
 * The helper owns and finalizes its statement even when execution or conversion
 * fails. A connection with no successful row insert returns 0n.
 * @throws Propagates database, statement, and integer conversion errors.
 */
export function lastInsertId(database: Database): bigint {
  const statement = database.prepare("SELECT last_insert_rowid()");
  try {
    statement.safeIntegers();
    const row = statement.raw().get();
    if (row === undefined) {
      throw new Error("SQLite did not return last_insert_rowid()");
    }
    return integer(row[0]);
  } finally {
    statement[Symbol.dispose]();
  }
}
