// Code generated by sqlc. DO NOT EDIT.

import type { Database } from "@bonakodo/sqlite";
export type { Database };



import type { CodecContext } from "./runtime_common.ts";

import type { QueryContext } from "./runtime_common.ts";

import type { FieldContext } from "./runtime_common.ts";

import { throwCodecError } from "./runtime_common.ts";

export type SqliteValue = null | string | number | bigint | Uint8Array;

export type Kind =
  | "integer"
  | "sqlite-integer"
  | "number"
  | "boolean"
  | "date"
  | "bytes"
  | "json"
  | "string"
  | "unknown";

const minInt64 = -(1n << 63n);

const maxInt64 = (1n << 63n) - 1n;

function integer(value: unknown): bigint {
  if (typeof value === "number") {
    if (!Number.isSafeInteger(value)) {
      throw new TypeError("Expected a safe integer number or bigint");
    }
    value = BigInt(value);
  }
  if (typeof value !== "bigint") {
    throw new TypeError("Expected a SQLite integer");
  }
  if (value < minInt64 || value > maxInt64) {
    throw new RangeError("Integer exceeds SQLite's signed 64-bit range");
  }
  return value;
}

function encodeValueUnchecked(
  kind: Kind,
  value: unknown,
  nullable = true,
): SqliteValue {
  if (!nullable && (value === null || value === undefined)) {
    throw new TypeError("Missing a non-null argument");
  }
  if (value === null || value === undefined) return null;
  switch (kind) {
    case "integer":
      return integer(value);
    case "string":
      if (typeof value !== "string") throw new TypeError("Expected a string");
      return value;
  }
  throw new TypeError("SQL kind is not used by these queries: " + kind);
}

function decodeValueUnchecked<T>(
  kind: Kind,
  value: SqliteValue,
  nullable: boolean,
  undefinedNull: boolean,
): T {
  if (value === null) {
    if (!nullable) {
      throw new TypeError("Unexpected SQL NULL in a non-null column");
    }
    return (undefinedNull ? undefined : null) as T;
  }
  let result: unknown;
  switch (kind) {
    case "integer":
      result = integer(value);
      break;
    case "string":
      if (typeof value !== "string") {
        throw new TypeError("Expected SQLite text");
      }
      result = value;
      break;
    default:
      throw new TypeError("SQL kind is not used by these queries: " + kind);
  }
  return result as T;
}

type DriverValue = SqliteValue;

export function encodeValue(
  kind: Kind,
  value: unknown,
  nullable = true,
  context?: CodecContext | QueryContext,
  field?: FieldContext,
): DriverValue {
  try {
    return encodeValueUnchecked(kind, value, nullable);
  } catch (cause) {
    throwCodecError(cause, "encode", context, field);
  }
}

export function decodeValue<T>(
  kind: Kind,
  value: DriverValue,
  nullable: boolean,
  undefinedNull: boolean,
  context?: CodecContext | QueryContext,
  field?: FieldContext,
): T {
  try {
    return decodeValueUnchecked<T>(kind, value, nullable, undefinedNull);
  } catch (cause) {
    throwCodecError(cause, "decode", context, field);
  }
}

export function queryOne<
  R extends SqliteValue[],
  T,
  C,
  N extends null | undefined,
>(
  database: Database,
  sql: string,
  params: readonly SqliteValue[],
  read: (row: R, context: C) => T,
  context: C,
  missing: N,
): T | N {
  const stmt = database.prepare(sql);
  try {
    stmt.safeIntegers();
    const row = stmt.raw().get(params) as R | undefined;
    return row === undefined ? missing : read(row, context);
  } finally {
    stmt[Symbol.dispose]();
  }
}

export function queryMany<R extends SqliteValue[], T, C>(
  database: Database,
  sql: string,
  params: readonly SqliteValue[],
  read: (row: R, context: C) => T,
  context: C,
): T[] {
  const stmt = database.prepare(sql);
  try {
    stmt.safeIntegers();
    const rows = stmt.raw().all(params) as R[];
    return rows.map((row) => read(row, context));
  } finally {
    stmt[Symbol.dispose]();
  }
}

export function runQuery<T>(
  database: Database,
  sql: string,
  params: readonly SqliteValue[],
  read: (result: ReturnType<ReturnType<Database["prepare"]>["run"]>) => T,
): T {
  const stmt = database.prepare(sql);
  try {
    stmt.safeIntegers();
    return read(stmt.run(params));
  } finally {
    stmt[Symbol.dispose]();
  }
}
