/** Encode trusted support declarations and their dependency graph as WAT data. */
const HEADER = "// Code generated by sqlc. DO NOT EDIT.\n\n";
const CONSTANT_START = 2686976;
const CONSTANT_END = 2899968;
const TEMPLATE_START = 3 * 1024 * 1024;
const TEMPLATE_END = 4 * 1024 * 1024;
const encoder = new TextEncoder();
export const runtimeFiles = [
  ["runtime_common", "runtime_common.ts", 62],
  ["runtime_sqlite", "runtime_sqlite.ts", 48],
  ["runtime_postgresql", "runtime_postgresql.ts", 6],
  ["runtime_mysql", "runtime_mysql.ts", 8],
] as const;
const ordinaryFiles = [["json", "json.ts"], [
  "codec_error",
  "codec_error.ts",
]] as const;
const templateFiles = [...runtimeFiles, ...ordinaryFiles] as const;
type TemplateName = (typeof templateFiles)[number][0];
export type Templates = Readonly<Record<TemplateName, string>>;
const driverMasks = new Map([
  ["pg", 2],
  ["postgres", 4],
  ["mysql2", 8],
  ["better-sqlite3", 16],
  ["bonakodo", 32],
]);
export const runtimeKinds = [
  "integer",
  "sqlite-integer",
  "number",
  "boolean",
  "date",
  "bytes",
  "json",
  "string",
  "unknown",
  "number-or-string",
  "buffer",
  "point",
  "box",
  "circle",
  "interval",
] as const;

/** Remove JSDoc blocks from trusted support text, retaining all other lines. */
export function compactSupportText(text: string): string {
  const result: string[] = [];
  let inDoc = false;
  for (const line of text.split("\n")) {
    const stripped = line.trim();
    if (stripped.startsWith("/**")) inDoc = true;
    if (inDoc) {
      if (stripped.includes("*/")) inDoc = false;
      continue;
    }
    result.push(line);
  }
  return result.join("\n");
}

/** WAT data literals contain bytes; escaping each byte preserves UTF-8 and NUL. */
export function watBytes(data: Uint8Array): string {
  return Array.from(data, (byte) => `\\${byte.toString(16).padStart(2, "0")}`)
    .join("");
}

export interface RuntimeFragment {
  kinds: number;
  text: string;
  dependencies: number[];
}
export interface RuntimeDeclaration {
  name: string;
  file: number;
  mask: number;
  kinds: number;
  fragments: RuntimeFragment[];
  dependencies: number[];
}
function kindMask(names: string[]): number {
  return names.reduce((mask, name) => {
    const index = runtimeKinds.indexOf(name as typeof runtimeKinds[number]);
    if (index < 0) throw new Error(`Unknown runtime kind ${name}`);
    return mask | (1 << index);
  }, 0);
}

// These are trusted templates, not arbitrary TypeScript input. Declaration
// boundaries and exceptional cross-file dependencies are explicit markers.
// Identifier references conservatively include types; quoted text and comments
// cannot accidentally retain helpers. Any dependency inside a template string
// expression must be declared explicitly in the @part marker.
function identifiers(source: string): Set<string> {
  const code = source.replace(
    /\/\*[\s\S]*?\*\/|\/\/[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`/g,
    " ",
  );
  return new Set(code.match(/[A-Za-z_$][\w$]*/g) ?? []);
}

/** Resolve declarations once at build time; WASM only follows numeric edges. */
export function compileRuntimeTemplates(
  templates: Templates,
): RuntimeDeclaration[] {
  const declarations: RuntimeDeclaration[] = [];
  const namedDependencies: string[][] = [];
  for (const [file, [template, , fileMask]] of runtimeFiles.entries()) {
    let declaration: RuntimeDeclaration | undefined;
    let fragment: RuntimeFragment | undefined;
    let conditional = false;
    for (
      const line
        of compactSupportText(templates[template]).match(/[^\n]*\n|[^\n]+$/g) ??
          []
    ) {
      const directive = /^\/\/ @(\w+)(?:\s+(.*))?$/.exec(line.trim());
      if (!directive) {
        if (!declaration) {
          if (line.trim()) {
            throw new Error(
              `Runtime ${template} text precedes its first @part`,
            );
          }
        } else fragment!.text += line;
        continue;
      }
      const [, command, args = ""] = directive;
      const words = args.split(/\s+/).filter(Boolean);
      if (command === "part") {
        if (conditional) throw new Error("Runtime @when is missing @endwhen");
        const [name, ...options] = words;
        if (!name || !/^[A-Za-z_$][\w$]*$/.test(name)) {
          throw new Error("Runtime @part requires an identifier");
        }
        let mask = fileMask as number;
        const driver = options.filter((word) => word.startsWith("@"));
        if (driver.length) {
          mask = 0;
          for (const word of driver) {
            const value = driverMasks.get(word.slice(1));
            if (!value) throw new Error(`Unknown runtime driver ${word}`);
            mask |= value;
          }
          if (mask & ~fileMask) {
            throw new Error(`Runtime driver does not belong to ${template}`);
          }
        }
        fragment = { kinds: 0, text: "", dependencies: [] };
        declaration = {
          name,
          file,
          mask,
          kinds: 0,
          fragments: [fragment],
          dependencies: [],
        };
        declarations.push(declaration);
        namedDependencies.push(options.filter((word) => !word.startsWith("@")));
      } else if (command === "when") {
        if (!declaration || conditional || !words.length) {
          throw new Error(
            "Runtime @when must be inside a part and cannot nest",
          );
        }
        conditional = true;
        fragment = { kinds: kindMask(words), text: "", dependencies: [] };
        declaration.fragments.push(fragment);
      } else if (command === "endwhen") {
        if (!declaration || !conditional || words.length) {
          throw new Error("Runtime has unmatched or labeled @endwhen");
        }
        conditional = false;
        fragment = { kinds: 0, text: "", dependencies: [] };
        declaration.fragments.push(fragment);
      } else if (command === "kind") {
        if (!declaration || conditional || !words.length) {
          throw new Error(
            "Runtime @kind requires a declaration and kind names",
          );
        }
        declaration.kinds |= kindMask(words);
      } else throw new Error(`Unknown runtime directive @${command}`);
    }
    if (conditional) throw new Error("Runtime @when is missing @endwhen");
  }
  if (declarations.length > 256) {
    throw new Error("Runtime declarations exceed their fixed selection table");
  }
  const find = (owner: RuntimeDeclaration, name: string): number[] => {
    const split = name.split(".");
    const file = split.length === 1
      ? owner.file
      : runtimeFiles.findIndex(([key]) => key === `runtime_${split[0]}`);
    if (split.length > 2 || file < 0) {
      throw new Error(`Invalid runtime dependency ${name}`);
    }
    const targets = declarations.flatMap((candidate, index) =>
      candidate.file === file && candidate.name === split.at(-1) &&
        (candidate.mask & owner.mask)
        ? [index]
        : []
    );
    let covered = 0;
    for (const index of targets) covered |= declarations[index]!.mask;
    // A common declaration can retain engine reexports without introducing
    // a TypeScript import cycle. Such an edge applies only to that engine's
    // drivers; the WAT walk ignores the other driver's dependency records.
    const required = owner.mask & runtimeFiles[file]![2];
    if (!required || (covered & required) !== required) {
      throw new Error(
        `Missing runtime dependency ${name} in ${
          runtimeFiles[owner.file]![0]
        }.${owner.name}`,
      );
    }
    return targets;
  };
  for (const [index, declaration] of declarations.entries()) {
    const duplicates = declarations.filter((other, otherIndex) =>
      otherIndex !== index && other.file === declaration.file &&
      other.name === declaration.name && (other.mask & declaration.mask)
    );
    if (duplicates.length) {
      throw new Error(`Duplicate runtime declaration ${declaration.name}`);
    }
    declaration.dependencies = [
      ...new Set(
        namedDependencies[index]!.flatMap((name) => find(declaration, name)),
      ),
    ];
    const names = new Set(
      declarations.filter((candidate) => candidate.file === declaration.file)
        .map(({ name }) => name),
    );
    for (const fragment of declaration.fragments) {
      fragment.dependencies = [...identifiers(fragment.text)].filter((name) =>
        name !== declaration.name && names.has(name)
      ).flatMap((name) => find(declaration, name));
    }
  }
  return declarations;
}

/** Readable build-time selection mirrors the small WAT dependency walk. */
export function renderRuntimeTemplates(
  templates: Templates,
  driver: number,
  names: string[],
  kinds: string[],
): Map<string, string> {
  if (!Number.isInteger(driver) || driver < 1 || driver > 5) {
    throw new Error("Runtime driver must be an integer from 1 to 5");
  }
  const declarations = compileRuntimeTemplates(templates);
  const bit = 1 << driver;
  const engine = driver >= 4 ? 1 : driver === 3 ? 3 : 2;
  const used = new Set<number>();
  let selectedKinds = kindMask(kinds);
  for (const name of names) {
    const index = declarations.findIndex((part) =>
      part.name === name && (part.mask & bit) &&
      (part.file === engine || part.file === 0)
    );
    if (index < 0) throw new Error(`Unknown runtime import ${name}`);
    used.add(index);
  }
  let previous: string;
  do {
    previous = `${selectedKinds}:${used.size}`;
    for (const index of used) {
      const part = declarations[index]!;
      selectedKinds |= part.kinds;
      for (
        const dependency of [
          ...part.dependencies,
          ...part.fragments.filter((fragment) =>
            !fragment.kinds || (fragment.kinds & selectedKinds)
          ).flatMap(({ dependencies }) => dependencies),
        ]
      ) {
        if (declarations[dependency]!.mask & bit) used.add(dependency);
      }
    }
  } while (previous !== `${selectedKinds}:${used.size}`);
  const files = new Map<string, string>();
  for (const file of [0, engine]) {
    files.set(
      runtimeFiles[file]![1],
      declarations.filter((part, index) =>
        part.file === file && used.has(index)
      ).flatMap(({ fragments }) =>
        fragments.filter((fragment) =>
          !fragment.kinds || (fragment.kinds & selectedKinds)
        ).map(({ text }) => text)
      ).join(""),
    );
  }
  return files;
}

export function renderAssets(
  constants: Readonly<Record<string, string>>,
  templates: Templates,
): string {
  const parts = [
    ";; Generated DATA ONLY by assets.ts; executable functions are hand-written WAT.",
  ];
  let address = CONSTANT_START;
  for (const [name, text] of Object.entries(constants)) {
    if (!/^[A-Za-z0-9_]+$/.test(name) || !/[A-Za-z0-9]/.test(name)) {
      throw new Error(`Invalid constant name ${name}`);
    }
    if (typeof text !== "string") {
      throw new Error(`Constant ${name} must contain text`);
    }
    const content = encoder.encode(text);
    if (content.length > CONSTANT_END - address) {
      throw new Error("Generator constants exceed their fixed memory region");
    }
    parts.push(
      `;; Constant ${name}: ${JSON.stringify(text)}`,
      `(data (i32.const ${address}) "${watBytes(content)}")`,
      `(func $c_${name} (result i32 i32) (i32.const ${address}) (i32.const ${content.length}))`,
    );
    address += content.length;
  }
  for (const [name] of templateFiles) {
    if (typeof templates[name] !== "string") {
      throw new Error(`Template ${name} must contain text`);
    }
  }
  const runtime = compileRuntimeTemplates(templates);
  address = TEMPLATE_START;
  const requireRoom = (length: number) => {
    if (length > TEMPLATE_END - address) {
      throw new Error("Support text exceeds its fixed read-only memory region");
    }
  };
  const reserve = (length: number): number => {
    requireRoom(length);
    const start = address;
    address += length;
    return start;
  };
  const data = (pointer: number, bytes: Uint8Array) =>
    parts.push(`(data (i32.const ${pointer}) "${watBytes(bytes)}")`);
  const append = (bytes: Uint8Array): [number, number] => {
    const start = reserve(bytes.length);
    data(start, bytes);
    return [start, bytes.length];
  };
  const appendText = (text: string): [number, number] =>
    append(encoder.encode(text));
  const numbers = (values: number[]): Uint8Array => {
    const bytes = new Uint8Array(values.length * 4);
    const view = new DataView(bytes.buffer);
    values.forEach((value, index) => view.setUint32(index * 4, value, true));
    return bytes;
  };
  const globals = (name: string, pointer: number, length: number) =>
    parts.push(
      `(global $asset_${name}_p i32 (i32.const ${pointer}))`,
      `(global $asset_${name}_n i32 (i32.const ${length}))`,
    );
  for (const [name, filename] of runtimeFiles) {
    const [pointer, length] = appendText(`./${filename}`);
    globals(`${name}_path`, pointer, length);
  }
  const tableAddress = reserve(runtime.length * 36);
  const table: number[] = [];
  for (const part of runtime) {
    const fragmentAddress = reserve(part.fragments.length * 20);
    const fragments: number[] = [];
    for (const fragment of part.fragments) {
      const [pointer, length] = appendText(fragment.text);
      const [dependencies] = append(numbers(fragment.dependencies));
      fragments.push(
        fragment.kinds,
        pointer,
        length,
        dependencies,
        fragment.dependencies.length,
      );
    }
    data(fragmentAddress, numbers(fragments));
    const [name, nameLength] = appendText(part.name);
    const [dependencies] = append(numbers(part.dependencies));
    table.push(
      part.mask,
      part.file,
      name,
      nameLength,
      fragmentAddress,
      part.fragments.length,
      dependencies,
      part.dependencies.length,
      part.kinds,
    );
  }
  data(tableAddress, numbers(table));
  globals("runtime_parts", tableAddress, runtime.length);
  parts.push(
    `(global $asset_runtime_sqlite_codecs_i i32 (i32.const ${
      runtime.findIndex((part) =>
        part.file === 1 && part.name === "externalCodecs"
      )
    }))`,
  );
  const kindTableAddress = reserve(runtimeKinds.length * 8);
  data(
    kindTableAddress,
    numbers(runtimeKinds.flatMap((name) => appendText(name))),
  );
  globals("runtime_kinds", kindTableAddress, runtimeKinds.length);
  for (const [name, filename] of ordinaryFiles) {
    parts.push(
      `;; ${filename}: verbatim output text, with documentation blocks omitted.`,
    );
    globals(name, ...appendText(compactSupportText(HEADER + templates[name])));
  }
  return parts.join("\n") + "\n";
}

export async function generateAssets(
  root = new URL("../", import.meta.url),
): Promise<string> {
  const decoder = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true });
  const readText = async (relative: string) =>
    decoder.decode(await Deno.readFile(new URL(relative, root))).replace(
      /\r\n?/g,
      "\n",
    );
  const [source, ...texts] = await Promise.all([
    readText("src/strings.json"),
    ...templateFiles.map(([, filename]) =>
      readText(`src/templates/${filename}`)
    ),
  ]);
  const constants: unknown = JSON.parse(source!);
  if (
    constants === null || typeof constants !== "object" ||
    Array.isArray(constants)
  ) throw new Error("src/strings.json must contain an object of named strings");
  const templates = Object.fromEntries(
    templateFiles.map(([name], index) => [name, texts[index]]),
  ) as Templates;
  return renderAssets(constants as Record<string, string>, templates);
}
if (import.meta.main) {
  if (Deno.args.length !== 1) {
    console.error(
      "Usage: deno run --allow-read --allow-write tools/assets.ts output.wat",
    );
    Deno.exit(2);
  }
  try {
    await Deno.writeTextFile(Deno.args[0]!, await generateAssets());
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    Deno.exit(1);
  }
}
