/** Encode output templates and constant strings as WAT data, without compiling them. */

const HEADER = "// Code generated by sqlc. DO NOT EDIT.\n\n";
const CONSTANT_START = 2686976;
const CONSTANT_END = 2899968;
const TEMPLATE_START = 3 * 1024 * 1024;
const TEMPLATE_END = 4 * 1024 * 1024;
const encoder = new TextEncoder();
const ordinaryFiles = [
  ["json", "json.ts", HEADER],
  ["codec_error", "codec_error.ts", HEADER],
] as const;
const templateFiles = [
  ["runtime", "runtime.ts", ""],
  ...ordinaryFiles,
] as const;

type TemplateName = (typeof templateFiles)[number][0];
export type Templates = Readonly<Record<TemplateName, string>>;

/** Remove JSDoc blocks from trusted support text, retaining all other lines. */
export function compactSupportText(text: string): string {
  const result: string[] = [];
  let inDoc = false;
  for (const line of text.split("\n")) {
    const stripped = line.trim();
    if (stripped.startsWith("/**")) inDoc = true;
    if (inDoc) {
      if (stripped.includes("*/")) inDoc = false;
      continue;
    }
    result.push(line);
  }
  return result.join("\n");
}

/** WAT data literals contain bytes; escaping each byte preserves UTF-8 and NUL. */
export function watBytes(data: Uint8Array): string {
  return Array.from(data, (byte) => `\\${byte.toString(16).padStart(2, "0")}`)
    .join("");
}

// Bits match src/options.wat driver IDs: pg=1, postgres=2, mysql2=3,
// better-sqlite3=4, bonakodo=5. Each descriptor selects 1 << driver.
const driverMasks = new Map([
  ["sqlite", 48],
  ["server", 14],
  ["bonakodo", 32],
  ["better-sqlite3", 16],
]);
const ALL_DRIVERS = 62;

export interface RuntimeFragment {
  mask: number;
  text: string;
}

/** Split trusted runtime source into ordered common and driver-specific spans. */
export function splitRuntimeTemplate(source: string): RuntimeFragment[] {
  const fragments: RuntimeFragment[] = [];
  let mask = ALL_DRIVERS;
  let text = "";
  const flush = () => {
    if (text) {
      const last = fragments.at(-1);
      if (last?.mask === mask) last.text += text;
      else fragments.push({ mask, text });
      text = "";
    }
  };
  for (
    const line of compactSupportText(source).match(/[^\n]*\n|[^\n]+$/g) ?? []
  ) {
    const directive = /^\/\/ @(if|endif)(?:\s+(.*))?$/.exec(line.trim());
    if (!directive) {
      text += line;
      continue;
    }
    flush();
    const [, kind, label] = directive;
    if (kind === "if") {
      if (mask !== ALL_DRIVERS) {
        throw new Error("Runtime template conditions cannot nest");
      }
      const selected = driverMasks.get(label ?? "");
      if (selected === undefined) {
        throw new Error(`Unknown runtime template condition ${label ?? ""}`);
      }
      mask = selected;
    } else {
      if (label) throw new Error("Runtime template @endif takes no label");
      if (mask === ALL_DRIVERS) {
        throw new Error("Runtime template has unmatched @endif");
      }
      mask = ALL_DRIVERS;
    }
  }
  if (mask !== ALL_DRIVERS) {
    throw new Error("Runtime template is missing @endif");
  }
  flush();
  return fragments;
}

export function renderRuntimeTemplate(source: string, driver: number): string {
  if (!Number.isInteger(driver) || driver < 1 || driver > 5) {
    throw new Error("Runtime template driver must be an integer from 1 to 5");
  }
  return splitRuntimeTemplate(source)
    .filter(({ mask }) => mask & (1 << driver))
    .map(({ text }) => text)
    .join("");
}

export function renderAssets(
  constants: Readonly<Record<string, string>>,
  templates: Templates,
): string {
  const parts = [
    ";; Generated DATA ONLY by assets.ts; executable functions are hand-written WAT.",
  ];
  let address = CONSTANT_START;
  for (const [name, text] of Object.entries(constants)) {
    if (!/^[A-Za-z0-9_]+$/.test(name) || !/[A-Za-z0-9]/.test(name)) {
      throw new Error(`Invalid constant name ${name}`);
    }
    if (typeof text !== "string") {
      throw new Error(`Constant ${name} must contain text`);
    }
    const content = encoder.encode(text);
    if (content.length > CONSTANT_END - address) {
      throw new Error("Generator constants exceed their fixed memory region");
    }
    // The getter is two constants, with no runtime lookup table. Binaryen can
    // inline it; hand-written WAT need not repeat addresses and byte lengths.
    parts.push(
      `;; Constant ${name}: ${JSON.stringify(text)}`,
      `(data (i32.const ${address}) "${watBytes(content)}")`,
      `(func $c_${name} (result i32 i32) (i32.const ${address}) (i32.const ${content.length}))`,
    );
    address += content.length;
  }
  for (const [name] of templateFiles) {
    if (typeof templates[name] !== "string") {
      throw new Error(`Template ${name} must contain text`);
    }
  }
  address = TEMPLATE_START;
  const runtime = splitRuntimeTemplate(templates.runtime);
  const tableAddress = address;
  const tableLength = runtime.length * 12;
  const requireRoom = (length: number) => {
    if (length > TEMPLATE_END - address) {
      throw new Error("Support text exceeds its fixed read-only memory region");
    }
  };
  requireRoom(tableLength);
  address += tableLength;
  const table = new Uint8Array(tableLength);
  const view = new DataView(table.buffer);
  const appendData = (text: string): [number, number] => {
    const content = encoder.encode(text);
    requireRoom(content.length);
    const start = address;
    parts.push(`(data (i32.const ${start}) "${watBytes(content)}")`);
    address += content.length;
    return [start, content.length];
  };
  for (const [index, fragment] of runtime.entries()) {
    const [pointer, length] = appendData(fragment.text);
    view.setUint32(index * 12, fragment.mask, true);
    view.setUint32(index * 12 + 4, pointer, true);
    view.setUint32(index * 12 + 8, length, true);
  }
  parts.push(
    ";; Runtime descriptors: driver mask, byte pointer, byte length.",
    `(global $asset_runtime_parts_p i32 (i32.const ${tableAddress}))`,
    `(global $asset_runtime_parts_n i32 (i32.const ${runtime.length}))`,
    `(data (i32.const ${tableAddress}) "${watBytes(table)}")`,
  );
  for (const [name, filename, header] of ordinaryFiles) {
    parts.push(
      `;; ${filename}: verbatim output text, with documentation blocks omitted.`,
    );
    const [pointer, length] = appendData(
      compactSupportText(header + templates[name]),
    );
    parts.push(
      `(global $asset_${name}_p i32 (i32.const ${pointer}))`,
      `(global $asset_${name}_n i32 (i32.const ${length}))`,
    );
  }
  return parts.join("\n") + "\n";
}

/** Read repository assets in their declared order and emit deterministic WAT. */
export async function generateAssets(
  root = new URL("../", import.meta.url),
): Promise<string> {
  const decoder = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true });
  const readText = async (relative: string) =>
    decoder.decode(await Deno.readFile(new URL(relative, root))).replace(
      /\r\n?/g,
      "\n",
    );
  const [source, ...texts] = await Promise.all([
    readText("src/strings.json"),
    ...templateFiles.map(([, filename]) =>
      readText(`src/templates/${filename}`)
    ),
  ]);
  const constants: unknown = JSON.parse(source!);
  if (
    constants === null || typeof constants !== "object" ||
    Array.isArray(constants)
  ) {
    throw new Error("src/strings.json must contain an object of named strings");
  }
  const templates = Object.fromEntries(
    templateFiles.map(([name], index) => [name, texts[index]]),
  ) as Templates;
  return renderAssets(constants as Record<string, string>, templates);
}

if (import.meta.main) {
  if (Deno.args.length !== 1) {
    console.error(
      "Usage: deno run --allow-read --allow-write tools/assets.ts output.wat",
    );
    Deno.exit(2);
  }
  try {
    await Deno.writeTextFile(Deno.args[0]!, await generateAssets());
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    Deno.exit(1);
  }
}
