;; Shared typed encoders/decoders keep query wrappers small. Shape equality
;; compares resolved fields structurally, including codecs and nested joins.
;; No source SQL, table identity, or query name is used as a substitute for
;; the actual conversion contract. Context remains specific to each call.
(global $compact_active (mut i32) (i32.const 0))
(global $compact_in_helper (mut i32) (i32.const 0))
(global $compact_module (mut i32) (i32.const 0))
(global $compact_shapes (mut i32) (i32.const 0))
(global $compact_shapes_tail (mut i32) (i32.const 0))
(global $compact_shape_count (mut i32) (i32.const 0))
(global $compact_fields (mut i32) (i32.const 0))
(global $compact_fields_tail (mut i32) (i32.const 0))
(global $compact_field_count (mut i32) (i32.const 0))

(func $compact_init
  (global.set $compact_active (i32.const 1))
  (global.set $compact_in_helper (i32.const 0))
  (global.set $compact_shapes (i32.const 0))
  (global.set $compact_shapes_tail (i32.const 0))
  (global.set $compact_shape_count (i32.const 0))
  (global.set $compact_fields (i32.const 0))
  (global.set $compact_fields_tail (i32.const 0))
  (global.set $compact_field_count (i32.const 0))
  (global.set $compact_module (call $module_new (call $c_compact_file)))
  (call $compact_module_names (global.get $compact_module)))

;; Module offsets 40/48 own the context and SQL-file constant names. Names
;; are reserved before imports so even custom symbols named q/file stay safe.
;; Offset56 records whether a query needs the SQL-file constant.
(func $compact_module_names (param $m i32)
  (call $set_text (local.get $m) (i32.const 40)
    (call $name_take (i32.load offset=16 (local.get $m)) (call $c_compact_query)))
  (call $set_text (local.get $m) (i32.const 48)
    (call $name_take (i32.load offset=16 (local.get $m)) (call $c_compact_file_var))))

(func $compact_type_module (param $m i32) (result i32)
  (select (global.get $compact_module) (local.get $m) (global.get $compact_active)))

(func $compact_fields_equal (param $a i32) (param $b i32) (result i32)
  (block $done (loop $fields
    (br_if $done (i32.or (i32.eqz (local.get $a)) (i32.eqz (local.get $b))))
    (if (i32.or
      (i32.or (i32.ne (i32.load offset=32 (local.get $a)) (i32.load offset=32 (local.get $b)))
              (i32.ne (i32.load offset=36 (local.get $a)) (i32.load offset=36 (local.get $b))))
      (i32.or (i32.ne (i32.load offset=40 (local.get $a)) (i32.load offset=40 (local.get $b)))
              (i32.ne (i32.load offset=44 (local.get $a)) (i32.load offset=44 (local.get $b)))))
      (then (return (i32.const 0))))
    (if (i32.eqz (call $eq (call $get_text (local.get $a) (i32.const 16)) (call $get_text (local.get $b) (i32.const 16)))) (then (return (i32.const 0))))
    (if (i32.eqz (call $eq (call $get_text (local.get $a) (i32.const 24)) (call $get_text (local.get $b) (i32.const 24)))) (then (return (i32.const 0))))
    (if (i32.eqz (call $eq (call $get_text (local.get $a) (i32.const 48)) (call $get_text (local.get $b) (i32.const 48)))) (then (return (i32.const 0))))
    (if (i32.eqz (call $eq (call $get_text (local.get $a) (i32.const 56)) (call $get_text (local.get $b) (i32.const 56)))) (then (return (i32.const 0))))
    ;; Preserve column comments on the shared interface too.
    (if (i32.eqz (call $eq (call $text (i32.load offset=8 (local.get $a)) (i32.const 5))
                           (call $text (i32.load offset=8 (local.get $b)) (i32.const 5)))) (then (return (i32.const 0))))
    (if (i32.eqz (call $compact_fields_equal (i32.load offset=12 (local.get $a)) (i32.load offset=12 (local.get $b)))) (then (return (i32.const 0))))
    (local.set $a (call $next (local.get $a))) (local.set $b (call $next (local.get $b))) (br $fields)))
  (i32.eq (local.get $a) (local.get $b)))

;; Shape kind109: fields8, argument flag12, type name16, function name24,
;; original query32. All referenced field text precedes query scratch marks.
(func $compact_shape (param $fields i32) (param $args i32) (param $query i32) (result i32)
  (local $shape i32) (local $scope i32)
  (local.set $shape (global.get $compact_shapes))
  (block $new (loop $find
    (br_if $new (i32.eqz (local.get $shape)))
    (if (i32.and (i32.eq (i32.load offset=12 (local.get $shape)) (local.get $args))
      (call $compact_fields_equal (i32.load offset=8 (local.get $shape)) (local.get $fields)))
      (then (return (local.get $shape))))
    (local.set $shape (call $next (local.get $shape))) (br $find)))
  (local.set $shape (call $work_record (i32.const 109)))
  (i32.store offset=8 (local.get $shape) (local.get $fields))
  (i32.store offset=12 (local.get $shape) (local.get $args))
  (i32.store offset=32 (local.get $shape) (local.get $query))
  (local.set $scope (i32.load offset=16 (global.get $compact_module)))
  (call $set_text (local.get $shape) (i32.const 16) (call $name_take (local.get $scope)
    (call $concat (if (result i32 i32) (local.get $args) (then (call $c_compact_args_type)) (else (call $c_compact_row_type)))
      (call $decimal_i32 (global.get $compact_shape_count)))))
  (call $set_text (local.get $shape) (i32.const 24) (call $name_take (local.get $scope)
    (call $concat (if (result i32 i32) (local.get $args) (then (call $c_compact_args_fn)) (else (call $c_compact_row_fn)))
      (call $decimal_i32 (global.get $compact_shape_count)))))
  (global.set $compact_shape_count (i32.add (global.get $compact_shape_count) (i32.const 1)))
  (if (global.get $compact_shapes_tail) (then (i32.store offset=4 (global.get $compact_shapes_tail) (local.get $shape)))
    (else (global.set $compact_shapes (local.get $shape))))
  (global.set $compact_shapes_tail (local.get $shape))
  (local.get $shape))

;; Plan offsets72/76 refer to argument and result shapes. Public query names
;; remain in the original plan; only the conversion implementation is shared.
(func $compact_plan (param $plan i32)
  (if (i32.load offset=36 (local.get $plan)) (then
    (i32.store offset=72 (local.get $plan) (call $compact_shape (i32.load offset=48 (local.get $plan)) (i32.const 1) (i32.load offset=8 (local.get $plan))))))
  (if (i32.load offset=44 (local.get $plan)) (then
    (i32.store offset=76 (local.get $plan) (call $compact_shape (i32.load offset=52 (local.get $plan)) (i32.const 0) (i32.load offset=8 (local.get $plan)))))))

(func $compact_interfaces (param $m i32) (param $plan i32)
  (local $args i32) (local $shape i32) (local $offset i32)
  (local.set $args (i32.const 1))
  (loop $interfaces
    (local.set $offset (select (i32.const 32) (i32.const 40) (local.get $args)))
    (local.set $shape (i32.load (i32.add (local.get $plan) (select (i32.const 72) (i32.const 76) (local.get $args)))))
    (if (local.get $shape) (then
      (call $line (call $fmt2 (call $c_compact_interface) (call $get_text (local.get $plan) (local.get $offset))
        (call $module_import (local.get $m) (call $c_compact_path) (call $get_text (local.get $shape) (i32.const 16)) (i32.const 1))))
      (call $line (call $c_empty))))
    (if (local.get $args) (then (local.set $args (i32.const 0)) (br $interfaces)))))

(func $compact_query_context (param $m i32) (param $plan i32)
  (if (i32.and (i32.eq (i32.load offset=12 (local.get $plan)) (i32.const 3))
              (i32.eqz (i32.load offset=48 (local.get $plan)))) (then return))
  (call $line (call $fmt3 (call $c_compact_query_line) (call $get_text (local.get $m) (i32.const 40))
    (call $quote (call $text (i32.load offset=8 (local.get $plan)) (i32.const 2)))
    (call $get_text (local.get $m) (i32.const 48)))))

;; Metadata kind110: field name8, expected type16, exported tuple name24.
;; Intern strings by their full byte spans; embedded dots and Unicode are data.
(func $compact_field (param $name i32) (param $name_n i32) (param $type i32) (param $type_n i32) (result i32)
  (local $field i32)
  (local.set $field (global.get $compact_fields))
  (block $new (loop $find
    (br_if $new (i32.eqz (local.get $field)))
    (if (i32.and (call $eq (local.get $name) (local.get $name_n) (call $get_text (local.get $field) (i32.const 8)))
                 (call $eq (local.get $type) (local.get $type_n) (call $get_text (local.get $field) (i32.const 16))))
      (then (return (local.get $field))))
    (local.set $field (call $next (local.get $field))) (br $find)))
  (local.set $field (call $work_record (i32.const 110)))
  (call $set_text (local.get $field) (i32.const 8) (call $retain_text (local.get $name) (local.get $name_n)))
  (call $set_text (local.get $field) (i32.const 16) (call $retain_text (local.get $type) (local.get $type_n)))
  (call $set_text (local.get $field) (i32.const 24) (call $name_take (i32.load offset=16 (global.get $compact_module))
    (call $concat (call $c_compact_field) (call $decimal_i32 (global.get $compact_field_count)))))
  (global.set $compact_field_count (i32.add (global.get $compact_field_count) (i32.const 1)))
  (if (global.get $compact_fields_tail) (then (i32.store offset=4 (global.get $compact_fields_tail) (local.get $field)))
    (else (global.set $compact_fields (local.get $field))))
  (global.set $compact_fields_tail (local.get $field))
  (local.get $field))

(func $compact_context (param $m i32) (param $name i32) (param $name_n i32) (param $type i32) (param $type_n i32) (result i32 i32)
  (local $field i32) (local $p i32) (local $n i32)
  (local.set $field (call $compact_field (local.get $name) (local.get $name_n) (local.get $type) (local.get $type_n)))
  (if (result i32 i32) (i32.eq (local.get $m) (global.get $compact_module))
    (then (call $get_text (local.get $field) (i32.const 24)))
    (else (call $module_import (local.get $m) (call $c_compact_path) (call $get_text (local.get $field) (i32.const 24)) (i32.const 0))))
  (local.set $n) (local.set $p)
  (call $fmt3 (call $c_compact_context_call)
    (call $runtime_import (local.get $m) (call $c_compact_context) (i32.const 0))
    (call $get_text (local.get $m) (i32.const 40)) (local.get $p) (local.get $n)))

(func $compact_row_call (param $m i32) (param $plan i32) (result i32 i32)
  (call $fmt2 (call $c_compact_row_call)
    (call $module_import (local.get $m) (call $c_compact_path)
      (call $get_text (i32.load offset=76 (local.get $plan)) (i32.const 24)) (i32.const 0))
    (call $get_text (local.get $m) (i32.const 40))))

(func $compact_bindings (param $m i32) (param $plan i32)
  (local $field i32) (local $start i32) (local $count i32) (local $call i32) (local $call_n i32)
  (local.set $field (i32.load offset=48 (local.get $plan)))
  (block $named (loop $names
    (br_if $named (i32.eqz (local.get $field)))
    (call $set_text (local.get $field) (i32.const 72) (call $fmt1 (call $c_compact_param) (call $decimal_i32 (i32.load offset=64 (local.get $field)))))
    (i32.store offset=96 (local.get $field) (i32.const 0))
    (local.set $field (call $next (local.get $field))) (br $names)))
  (call $fmt2 (call $c_compact_bind_call)
    (call $module_import (local.get $m) (call $c_compact_path) (call $get_text (i32.load offset=72 (local.get $plan)) (i32.const 24)) (i32.const 0))
    (call $get_text (local.get $m) (i32.const 40))) (local.set $call_n) (local.set $call)
  (local.set $start (call $text_mark))
  (local.set $field (i32.load offset=48 (local.get $plan)))
  (block $listed (loop $list
    (br_if $listed (i32.eqz (local.get $field)))
    (if (local.get $count) (then (call $text_append (call $c_comma))))
    (call $text_append (call $get_text (local.get $field) (i32.const 72)))
    (local.set $count (i32.add (local.get $count) (i32.const 1)))
    (local.set $field (call $next (local.get $field))) (br $list)))
  (call $line (call $fmt2 (call $c_compact_destructure) (local.get $start) (i32.sub (call $text_mark) (local.get $start))
    (local.get $call) (local.get $call_n))))

(func $compact_emit_encoder (param $shape i32)
  (local $m i32) (local $field i32) (local $context i32) (local $context_n i32)
  (local $p i32) (local $n i32) (local $plan i32)
  (local.set $m (global.get $compact_module))
  (call $line (call $fmt4 (call $c_compact_encode_header) (call $get_text (local.get $shape) (i32.const 24))
    (call $get_text (local.get $shape) (i32.const 16)) (call $get_text (local.get $m) (i32.const 40))
    (call $runtime_import (local.get $m) (call $c_compact_query_type) (i32.const 1))))
  (call $indent) (call $line (call $c_compact_encode_return)) (call $indent)
  (local.set $field (i32.load offset=8 (local.get $shape)))
  (block $done (loop $fields
    (br_if $done (i32.eqz (local.get $field)))
    (call $compact_context (local.get $m) (call $get_text (local.get $field) (i32.const 16))
      (call $argument_type_text (local.get $field))) (local.set $context_n) (local.set $context)
    (if (result i32 i32) (i32.load offset=44 (local.get $field))
      (then
        (call $runtime_import (local.get $m) (call $c_encode_slice) (i32.const 0)) (local.set $n) (local.set $p)
        (call $fmt4 (call $c_compact_slice)
          (local.get $p) (local.get $n) (call $access (call $c_args) (call $get_text (local.get $field) (i32.const 16)))
          (call $encode_context (local.get $m) (local.get $field) (call $c_value) (local.get $context) (local.get $context_n))
          (local.get $context) (local.get $context_n)))
      (else (call $encode_context (local.get $m) (local.get $field)
        (call $access (call $c_args) (call $get_text (local.get $field) (i32.const 16)))
        (local.get $context) (local.get $context_n))))
    (local.set $n) (local.set $p)
    (call $line (call $concat (local.get $p) (local.get $n) (call $c_trailing_comma)))
    (local.set $field (call $next (local.get $field))) (br $fields)))
  (call $dedent) (call $line (call $c_compact_encode_end)) (call $dedent) (call $line (call $c_close_brace)) (call $line (call $c_empty)))

(func $compact_emit_decoder (param $shape i32)
  (local $m i32) (local $plan i32) (local $row_type i32) (local $row_type_n i32)
  (local $value i32) (local $value_n i32) (local $count i32) (local $i i32) (local $start i32)
  (local.set $m (global.get $compact_module))
  (local.set $plan (call $work_record (i32.const 106)))
  (i32.store offset=8 (local.get $plan) (i32.load offset=32 (local.get $shape)))
  (i32.store offset=52 (local.get $plan) (i32.load offset=8 (local.get $shape)))
  (if (result i32 i32) (i32.eq (global.get $gen_engine) (i32.const 1))
    (then
      (call $runtime_import (local.get $m) (call $drv_sqlite_value) (i32.const 1)) (local.set $value_n) (local.set $value)
      (local.set $count (call $field_count (i32.load offset=8 (local.get $shape))))
      (local.set $start (call $text_mark)) (call $text_byte (i32.const 91))
      (block $tuple_done (loop $tuple
        (br_if $tuple_done (i32.ge_u (local.get $i) (local.get $count)))
        (if (local.get $i) (then (call $text_append (call $c_comma))))
        (call $text_append (local.get $value) (local.get $value_n))
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $tuple)))
      (call $text_byte (i32.const 93)) (local.get $start) (i32.sub (call $text_mark) (local.get $start)))
    (else (if (result i32 i32) (i32.eq (global.get $opt_driver) (i32.const 3))
      (then (call $module_import (local.get $m) (call $opt_driver_specifier) (call $drv_row_packet) (i32.const 1)))
      (else (call $concat (call $c_unknown) (call $drv_empty_bindings))))))
  (local.set $row_type_n) (local.set $row_type)
  (call $line (call $fmt5 (call $c_compact_decode_header) (call $get_text (local.get $shape) (i32.const 24))
    (local.get $row_type) (local.get $row_type_n)
    (call $get_text (local.get $m) (i32.const 40))
    (call $runtime_import (local.get $m) (call $c_compact_query_type) (i32.const 1))
    (call $get_text (local.get $shape) (i32.const 16))))
  (call $indent) (call $driver_row (local.get $m) (local.get $plan)) (call $dedent)
  (call $line (call $c_close_brace)) (call $line (call $c_empty)))

(func $compact_emit
  (local $shape i32) (local $field i32) (local $m i32) (local $scratch i32)
  (if (i32.eqz (i32.or (global.get $compact_shapes) (global.get $compact_fields))) (then return))
  (local.set $m (global.get $compact_module))
  (call $module_begin (local.get $m))
  (global.set $compact_in_helper (i32.const 1))
  (local.set $shape (global.get $compact_shapes))
  (block $done (loop $shapes
    (br_if $done (i32.eqz (local.get $shape)))
    (local.set $scratch (call $text_mark))
    (call $emit_interface (local.get $m) (call $get_text (local.get $shape) (i32.const 16))
      (i32.load offset=8 (local.get $shape)) (i32.load offset=12 (local.get $shape)))
    (if (i32.eqz (global.get $opt_types_only)) (then
      (if (i32.load offset=12 (local.get $shape))
        (then (call $compact_emit_encoder (local.get $shape)))
        (else (call $compact_emit_decoder (local.get $shape))))))
    (call $text_reset (local.get $scratch))
    (local.set $shape (call $next (local.get $shape))) (br $shapes)))
  (local.set $field (global.get $compact_fields))
  (block $fields_done (loop $fields
    (br_if $fields_done (i32.eqz (local.get $field)))
    (call $line (call $fmt3 (call $c_compact_field_line) (call $get_text (local.get $field) (i32.const 24))
      (call $quote (call $get_text (local.get $field) (i32.const 8))) (call $quote (call $get_text (local.get $field) (i32.const 16)))))
    (local.set $field (call $next (local.get $field))) (br $fields)))
  (call $module_end (local.get $m))
  (global.set $compact_in_helper (i32.const 0)))
