;; Static TypeScript templates for drivers.wat. All control flow below is
;; hand-written WAT. These functions expose immutable pointer/length pairs;
;; they do not format text or allocate memory. Template slots are256bytes.
(data (i32.const 3096576) "[]")
(func $drv_empty_bindings (result i32 i32) (i32.const 3096576) (i32.const 2))
(data (i32.const 3096832) "return")
(func $drv_return (result i32 i32) (i32.const 3096832) (i32.const 6))
(data (i32.const 3097088) "rowsAffected")
(func $drv_rows_affected (result i32 i32) (i32.const 3097088) (i32.const 12))
(data (i32.const 3097344) "lastInsertId")
(func $drv_last_id (result i32 i32) (i32.const 3097344) (i32.const 12))
(data (i32.const 3097600) "bigint")
(func $drv_bigint (result i32 i32) (i32.const 3097600) (i32.const 6))
(data (i32.const 3097856) "number")
(func $drv_number (result i32 i32) (i32.const 3097856) (i32.const 6))
(data (i32.const 3098112) "number | string")
(func $drv_number_string (result i32 i32) (i32.const 3098112) (i32.const 15))
(data (i32.const 3098368) "string")
(func $drv_string (result i32 i32) (i32.const 3098368) (i32.const 6))
(data (i32.const 3098624) "undefined")
(func $drv_undefined (result i32 i32) (i32.const 3098624) (i32.const 9))
(data (i32.const 3098880) "true")
(func $drv_true (result i32 i32) (i32.const 3098880) (i32.const 4))
(data (i32.const 3099136) "false")
(func $drv_false (result i32 i32) (i32.const 3099136) (i32.const 5))
(data (i32.const 3099392) "integerResult")
(func $drv_integer_result (result i32 i32) (i32.const 3099392) (i32.const 13))
(data (i32.const 3099648) "withCodecContext")
(func $drv_with_context (result i32 i32) (i32.const 3099648) (i32.const 16))
(data (i32.const 3099904) "DriverParameters")
(func $drv_driver_parameters (result i32 i32) (i32.const 3099904) (i32.const 16))
(data (i32.const 3100160) "SqliteValue")
(func $drv_sqlite_value (result i32 i32) (i32.const 3100160) (i32.const 11))
(data (i32.const 3100416) "mysqlInsertId")
(func $drv_mysql_id (result i32 i32) (i32.const 3100416) (i32.const 13))
(data (i32.const 3100672) "mysqlInsertIdBigInt")
(func $drv_mysql_id_bigint (result i32 i32) (i32.const 3100672) (i32.const 19))
(data (i32.const 3100928) "ResultSetHeader")
(func $drv_result_header (result i32 i32) (i32.const 3100928) (i32.const 15))
(data (i32.const 3101184) "RowDataPacket")
(func $drv_row_packet (result i32 i32) (i32.const 3101184) (i32.const 13))
(data (i32.const 3101440) "await database.query({ text: %s, values: %s, rowMode: \22array\22 });")
(func $drv_pg_exec (result i32 i32) (i32.const 3101440) (i32.const 65))
(data (i32.const 3101696) "const result = await database.query({ text: %s, values: %s, rowMode: \22array\22 });")
(func $drv_pg_result (result i32 i32) (i32.const 3101696) (i32.const 80))
(data (i32.const 3101952) "const rows: unknown[][] = result.rows;")
(func $drv_pg_rows (result i32 i32) (i32.const 3101952) (i32.const 38))
(data (i32.const 3102208) "%s(result.rowCount ?? 0)")
(func $drv_pg_count (result i32 i32) (i32.const 3102208) (i32.const 24))
(data (i32.const 3102464) "await database.unsafe(%s, %s as %s);")
(func $drv_postgres_exec (result i32 i32) (i32.const 3102464) (i32.const 36))
(data (i32.const 3102720) "const rows = await database.unsafe(%s, %s as %s).values();")
(func $drv_postgres_values (result i32 i32) (i32.const 3102720) (i32.const 58))
(data (i32.const 3102976) "%s(rows.count)")
(func $drv_postgres_count (result i32 i32) (i32.const 3102976) (i32.const 14))
(data (i32.const 3103232) "return %s;")
(func $drv_return_value (result i32 i32) (i32.const 3103232) (i32.const 10))
(data (i32.const 3103488) "return { rowsAffected: %s, lastInsertId: null };")
(func $drv_return_pg_result (result i32 i32) (i32.const 3103488) (i32.const 48))
(data (i32.const 3103744) "return { rowsAffected: %s, lastInsertId: %s };")
(func $drv_return_result (result i32 i32) (i32.const 3103744) (i32.const 46))
(data (i32.const 3104000) "const result = await database.unsafe(%s, %s as %s).raw();")
(func $drv_postgres_raw (result i32 i32) (i32.const 3104000) (i32.const 57))
(data (i32.const 3104256) "if (result.columns.length !== %d) throw new TypeError(\22SQL result column count does not match generated query\22);")
(func $drv_raw_width (result i32 i32) (i32.const 3104256) (i32.const 112))
(data (i32.const 3104512) "const _sqlcColumnContexts = [%s];")
(func $drv_column_contexts (result i32 i32) (i32.const 3104512) (i32.const 33))
(data (i32.const 3104768) "const rows: unknown[][] = result.map((rawRow) => rawRow.map((value, index): unknown => {")
(func $drv_raw_map (result i32 i32) (i32.const 3104768) (i32.const 88))
(data (i32.const 3105024) "const column = result.columns[index];")
(func $drv_raw_column (result i32 i32) (i32.const 3105024) (i32.const 37))
(data (i32.const 3105280) "if (column === undefined) throw new TypeError(\22SQL driver omitted result column metadata\22);")
(func $drv_raw_missing (result i32 i32) (i32.const 3105280) (i32.const 91))
(data (i32.const 3105536) "if (value === null) return null;")
(func $drv_raw_null (result i32 i32) (i32.const 3105536) (i32.const 32))
(data (i32.const 3105792) "const text = value.toString(\22utf8\22);")
(func $drv_raw_text (result i32 i32) (i32.const 3105792) (i32.const 36))
(data (i32.const 3106048) "if (%s) return text;")
(func $drv_raw_array (result i32 i32) (i32.const 3106048) (i32.const 20))
(data (i32.const 3106304) "return %s(_sqlcColumnContexts[index], \22decode\22, () => column.parser ? column.parser(text) : text);")
(func $drv_raw_decode (result i32 i32) (i32.const 3106304) (i32.const 98))
(data (i32.const 3106560) "}));")
(func $drv_raw_end (result i32 i32) (i32.const 3106560) (i32.const 4))
(data (i32.const 3106816) "index === ")
(func $drv_index_equals (result i32 i32) (i32.const 3106816) (i32.const 10))
(data (i32.const 3107072) "if (rows.length !== 1) return %s;")
(func $drv_one_count (result i32 i32) (i32.const 3107072) (i32.const 33))
(data (i32.const 3107328) "const row = rows[0];")
(func $drv_first_row (result i32 i32) (i32.const 3107328) (i32.const 20))
(data (i32.const 3107584) "if (row === undefined) return %s;")
(func $drv_missing_row (result i32 i32) (i32.const 3107584) (i32.const 33))
(data (i32.const 3107840) "return rows.map((row): %s => {")
(func $drv_rows_map (result i32 i32) (i32.const 3107840) (i32.const 30))
(data (i32.const 3108096) "});")
(func $drv_map_end (result i32 i32) (i32.const 3108096) (i32.const 3))
(data (i32.const 3108352) "const stmt = database.prepare(%s);")
(func $drv_prepare (result i32 i32) (i32.const 3108352) (i32.const 34))
(data (i32.const 3108608) "const stmt = database.prepare(%s).safeIntegers();")
(func $drv_prepare_safe (result i32 i32) (i32.const 3108608) (i32.const 49))
(data (i32.const 3108864) "try {")
(func $drv_try (result i32 i32) (i32.const 3108864) (i32.const 5))
(data (i32.const 3109120) "stmt.safeIntegers();")
(func $drv_safe (result i32 i32) (i32.const 3109120) (i32.const 20))
(data (i32.const 3109376) "const row = stmt.raw().get(%s) as %s | undefined;")
(func $drv_sqlite_get (result i32 i32) (i32.const 3109376) (i32.const 49))
(data (i32.const 3109632) "const rows = stmt.raw().all(%s) as %s[];")
(func $drv_sqlite_all (result i32 i32) (i32.const 3109632) (i32.const 40))
(data (i32.const 3109888) "stmt.run(%s);")
(func $drv_run (result i32 i32) (i32.const 3109888) (i32.const 13))
(data (i32.const 3110144) "const result = stmt.run(%s);")
(func $drv_run_result (result i32 i32) (i32.const 3110144) (i32.const 28))
(data (i32.const 3110400) "BigInt(result.changes)")
(func $drv_big_changes (result i32 i32) (i32.const 3110400) (i32.const 22))
(data (i32.const 3110656) "BigInt(result.lastInsertRowid)")
(func $drv_big_last (result i32 i32) (i32.const 3110656) (i32.const 30))
(data (i32.const 3110912) "Number(result.lastInsertRowid)")
(func $drv_number_last (result i32 i32) (i32.const 3110912) (i32.const 30))
(data (i32.const 3111168) "} finally {")
(func $drv_finally (result i32 i32) (i32.const 3111168) (i32.const 11))
(data (i32.const 3111424) "stmt[Symbol.dispose]();")
(func $drv_dispose (result i32 i32) (i32.const 3111424) (i32.const 23))
(data (i32.const 3111680) "}")
(func $drv_end (result i32 i32) (i32.const 3111680) (i32.const 1))
(data (i32.const 3111936) "const [result] = ")
(func $drv_mysql_prefix_result (result i32 i32) (i32.const 3111936) (i32.const 17))
(data (i32.const 3112192) "const [rows] = ")
(func $drv_mysql_prefix_rows (result i32 i32) (i32.const 3112192) (i32.const 15))
(data (i32.const 3112448) "")
(func $drv_empty (result i32 i32) (i32.const 3112448) (i32.const 0))
(data (i32.const 3112704) "%sawait database.execute<%s>({")
(func $drv_mysql_execute (result i32 i32) (i32.const 3112704) (i32.const 30))
(data (i32.const 3112960) "sql: %s,")
(func $drv_mysql_sql (result i32 i32) (i32.const 3112960) (i32.const 8))
(data (i32.const 3113216) "values: %s,")
(func $drv_mysql_values (result i32 i32) (i32.const 3113216) (i32.const 11))
(data (i32.const 3113472) "rowsAsArray: %t,")
(func $drv_mysql_array (result i32 i32) (i32.const 3113472) (i32.const 16))
(data (i32.const 3113728) "supportBigNumbers: %t,")
(func $drv_mysql_big (result i32 i32) (i32.const 3113728) (i32.const 22))
(data (i32.const 3113984) "bigNumberStrings: %t,")
(func $drv_mysql_strings (result i32 i32) (i32.const 3113984) (i32.const 21))
(data (i32.const 3114240) "%s(result.affectedRows)")
(func $drv_mysql_changes (result i32 i32) (i32.const 3114240) (i32.const 23))
(data (i32.const 3114496) "%s(result.insertId, %t, %t, %s)")
(func $drv_mysql_last (result i32 i32) (i32.const 3114496) (i32.const 31))
(data (i32.const 3114752) "%s(result.insertId, %s)")
(func $drv_mysql_last_big (result i32 i32) (i32.const 3114752) (i32.const 23))
(data (i32.const 3115008) "{ query: %s, file: %s, field: %s, expectedType: %s }")
(func $drv_context (result i32 i32) (i32.const 3115008) (i32.const 52))
(data (i32.const 3115264) "if (row.length !== %d) throw new Error(\22SQL result column count does not match the generated query\22);")
(func $drv_row_width (result i32 i32) (i32.const 3115264) (i32.const 101))
(data (i32.const 3115520) "%s {")
(func $drv_row_start (result i32 i32) (i32.const 3115520) (i32.const 4))
(data (i32.const 3115776) "};")
(func $drv_row_end (result i32 i32) (i32.const 3115776) (i32.const 2))
(data (i32.const 3116032) "%s: {")
(func $drv_object_start (result i32 i32) (i32.const 3116032) (i32.const 5))
(data (i32.const 3116288) "},")
(func $drv_object_end (result i32 i32) (i32.const 3116288) (i32.const 2))
(data (i32.const 3116544) "row[%d]")
(func $drv_row_index (result i32 i32) (i32.const 3116544) (i32.const 7))
(data (i32.const 3116800) "%s: %s,")
(func $drv_row_field (result i32 i32) (i32.const 3116800) (i32.const 7))
(data (i32.const 3117056) "%s(%s, \22decode\22, () => %s)")
(func $drv_convert_result (result i32 i32) (i32.const 3117056) (i32.const 26))
(data (i32.const 3117312) ", ")
(func $drv_comma (result i32 i32) (i32.const 3117312) (i32.const 2))
(data (i32.const 3117568) ".")
(func $drv_dot (result i32 i32) (i32.const 3117568) (i32.const 1))
(data (i32.const 3117824) " || ")
(func $drv_condition_or (result i32 i32) (i32.const 3117824) (i32.const 4))

;; Contexts contain source metadata only. Quoting and type formatting complete
;; before fmt4 starts, so nested helper use cannot overwrite a live argument.
(func $driver_context (param $query i32) (param $name i32) (param $name_n i32)
  (param $type i32) (param $type_n i32) (result i32 i32)
  (call $fmt4 (call $drv_context)
    (call $quote (call $text_ptr (local.get $query) (i32.const 2)) (call $text_len (local.get $query) (i32.const 2)))
    (call $quote (call $text_ptr (local.get $query) (i32.const 7)) (call $text_len (local.get $query) (i32.const 7)))
    (call $quote (local.get $name) (local.get $name_n)) (call $quote (local.get $type) (local.get $type_n))))
(func $codec_context (param $m i32) (param $query i32) (param $field i32)
  (param $alias i32) (param $alias_n i32) (result i32 i32)
  (if (i32.eqz (i32.or (local.get $alias) (local.get $alias_n))) (then
    (call $get_text (local.get $field) (i32.const 16)) (local.set $alias_n) (local.set $alias)))
  (call $driver_context (local.get $query) (local.get $alias) (local.get $alias_n) (call $type_text (local.get $field))))
(func $argument_codec_context (param $m i32) (param $query i32) (param $field i32) (result i32 i32)
  (call $driver_context (local.get $query) (call $get_text (local.get $field) (i32.const 16))
    (call $argument_type_text (local.get $field))))
(func $field_count (param $fields i32) (result i32) (local $count i32) (local $children i32)
  (block $done (loop $fields_loop
    (br_if $done (i32.eqz (local.get $fields)))
    (local.set $children (i32.load offset=12 (local.get $fields)))
    (local.set $count (i32.add (local.get $count)
      (if (result i32) (local.get $children) (then (call $field_count (local.get $children))) (else (i32.const 1)))))
    (local.set $fields (call $next (local.get $fields))) (br $fields_loop))) (local.get $count))
(func $driver_convert_result (param $m i32) (param $plan i32)
  (param $name i32) (param $name_n i32) (param $type i32) (param $type_n i32)
  (param $expression i32) (param $expression_n i32) (result i32 i32)
  (call $fmt3 (call $drv_convert_result)
    (call $runtime_import (local.get $m) (call $drv_with_context) (i32.const 0))
    (call $driver_context (i32.load offset=8 (local.get $plan)) (local.get $name) (local.get $name_n) (local.get $type) (local.get $type_n))
    (local.get $expression) (local.get $expression_n)))

;; Each physical row cell consumes one index; an embedded result recurses and
;; carries a dotted property path into codec errors. Names in source objects
;; use property(), preserving quoted keys and the special __proto__ spelling.
(global $driver_row_index (mut i32) (i32.const 0))
(func $driver_row_fields (param $m i32) (param $plan i32) (param $fields i32) (param $prefix i32) (param $prefix_n i32)
  (local $children i32) (local $p i32) (local $n i32)
  (block $done (loop $loop
    (br_if $done (i32.eqz (local.get $fields)))
    (local.set $children (i32.load offset=12 (local.get $fields)))
    (if (local.get $children)
      (then
        (call $line (call $fmt1 (call $drv_object_start) (call $property (call $get_text (local.get $fields) (i32.const 16)))))
        (call $indent)
        (call $driver_row_fields (local.get $m) (local.get $plan) (local.get $children)
          (call $concat (call $concat (local.get $prefix) (local.get $prefix_n) (call $get_text (local.get $fields) (i32.const 16))) (call $drv_dot)))
        (call $dedent) (call $line (call $drv_object_end)))
      (else
        (call $decode_context (local.get $m) (local.get $fields)
          (call $fmt1 (call $drv_row_index) (call $decimal_i32 (global.get $driver_row_index)))
          (call $codec_context (local.get $m) (i32.load offset=8 (local.get $plan)) (local.get $fields)
            (call $concat (local.get $prefix) (local.get $prefix_n) (call $get_text (local.get $fields) (i32.const 16)))))
        (local.set $n) (local.set $p)
        (call $line (call $fmt2 (call $drv_row_field) (call $property (call $get_text (local.get $fields) (i32.const 16))) (local.get $p) (local.get $n)))
        (global.set $driver_row_index (i32.add (global.get $driver_row_index) (i32.const 1)))))
    (local.set $fields (call $next (local.get $fields))) (br $loop))))
(func $driver_row (param $m i32) (param $plan i32)
  (call $line (call $fmt1 (call $drv_row_width) (call $decimal_i32 (call $field_count (i32.load offset=52 (local.get $plan))))))
  (call $line (call $fmt1 (call $drv_row_start) (call $drv_return))) (call $indent)
  (global.set $driver_row_index (i32.const 0))
  (call $driver_row_fields (local.get $m) (local.get $plan) (i32.load offset=52 (local.get $plan)) (i32.const 0) (i32.const 0))
  (call $dedent) (call $line (call $drv_row_end)))
(func $driver_rows (param $m i32) (param $plan i32)
  (if (i32.eq (i32.load offset=12 (local.get $plan)) (i32.const 1)) (then
    (if (i32.ne (global.get $gen_engine) (i32.const 1)) (then (call $line (call $fmt1 (call $drv_one_count) (call $null_text)))))
    (call $line (call $drv_first_row)) (call $line (call $fmt1 (call $drv_missing_row) (call $null_text)))
    (call $driver_row (local.get $m) (local.get $plan)) (return)))
  (call $line (call $fmt1 (call $drv_rows_map) (call $get_text (local.get $plan) (i32.const 40))))
  (call $indent) (call $driver_row (local.get $m) (local.get $plan)) (call $dedent) (call $line (call $drv_map_end)))

;; Raw-array queries retain prepared contexts in each field's scratch words.
;; This avoids repeatedly copying an ever-growing text list. The second pass
;; only appends completed views, so helper output never enters the list twice.
(global $driver_array_count (mut i32) (i32.const 0))
(global $driver_join_count (mut i32) (i32.const 0))
(func $driver_prepare_contexts (param $m i32) (param $plan i32) (param $fields i32) (param $prefix i32) (param $prefix_n i32)
  (block $done (loop $loop
    (br_if $done (i32.eqz (local.get $fields)))
    (if (i32.load offset=12 (local.get $fields))
      (then (call $driver_prepare_contexts (local.get $m) (local.get $plan) (i32.load offset=12 (local.get $fields))
        (call $concat (call $concat (local.get $prefix) (local.get $prefix_n) (call $get_text (local.get $fields) (i32.const 16))) (call $drv_dot))))
      (else
        (call $set_text (local.get $fields) (i32.const 80)
          (call $codec_context (local.get $m) (i32.load offset=8 (local.get $plan)) (local.get $fields)
            (call $concat (local.get $prefix) (local.get $prefix_n) (call $get_text (local.get $fields) (i32.const 16)))))
        (i32.store offset=88 (local.get $fields) (global.get $driver_row_index))
        (global.set $driver_row_index (i32.add (global.get $driver_row_index) (i32.const 1)))
        (if (i32.gt_s (i32.load offset=40 (local.get $fields)) (i32.const 0))
          (then (global.set $driver_array_count (i32.add (global.get $driver_array_count) (i32.const 1)))))))
    (local.set $fields (call $next (local.get $fields))) (br $loop))))
(func $driver_join_contexts (param $fields i32) (param $conditions i32)
  (block $done (loop $loop
    (br_if $done (i32.eqz (local.get $fields)))
    (if (i32.load offset=12 (local.get $fields))
      (then (call $driver_join_contexts (i32.load offset=12 (local.get $fields)) (local.get $conditions)))
      (else
        (if (i32.or (i32.eqz (local.get $conditions)) (i32.gt_s (i32.load offset=40 (local.get $fields)) (i32.const 0))) (then
          (if (global.get $driver_join_count) (then
            (if (local.get $conditions) (then (call $text_append (call $drv_condition_or))) (else (call $text_append (call $drv_comma))))))
          (global.set $driver_join_count (i32.add (global.get $driver_join_count) (i32.const 1)))
          (if (local.get $conditions)
            (then (call $text_append (call $drv_index_equals)) (call $decimal_i32 (i32.load offset=88 (local.get $fields))) drop drop)
            (else (call $text_append (call $get_text (local.get $fields) (i32.const 80)))))))))
    (local.set $fields (call $next (local.get $fields))) (br $loop))))
(func $driver_has_arrays (param $fields i32) (result i32)
  (block $done (loop $loop
    (br_if $done (i32.eqz (local.get $fields)))
    (if (i32.load offset=12 (local.get $fields))
      (then (if (call $driver_has_arrays (i32.load offset=12 (local.get $fields))) (then (return (i32.const 1)))))
      (else (if (i32.gt_s (i32.load offset=40 (local.get $fields)) (i32.const 0)) (then (return (i32.const 1))))))
    (local.set $fields (call $next (local.get $fields))) (br $loop))) (i32.const 0))
(func $driver_postgres_raw (param $m i32) (param $plan i32) (param $bindings i32) (param $bindings_n i32)
  (param $sql i32) (param $sql_n i32) (param $parameters i32) (param $parameters_n i32) (local $start i32)
  (call $line (call $fmt3 (call $drv_postgres_raw) (local.get $sql) (local.get $sql_n) (local.get $bindings) (local.get $bindings_n) (local.get $parameters) (local.get $parameters_n)))
  (call $line (call $fmt1 (call $drv_raw_width) (call $decimal_i32 (call $field_count (i32.load offset=52 (local.get $plan))))))
  (global.set $driver_row_index (i32.const 0)) (global.set $driver_array_count (i32.const 0))
  (call $driver_prepare_contexts (local.get $m) (local.get $plan) (i32.load offset=52 (local.get $plan)) (i32.const 0) (i32.const 0))
  (local.set $start (global.get $txt_cursor)) (global.set $driver_join_count (i32.const 0))
  (call $driver_join_contexts (i32.load offset=52 (local.get $plan)) (i32.const 0))
  (call $line (call $fmt1 (call $drv_column_contexts) (local.get $start) (i32.sub (global.get $txt_cursor) (local.get $start))))
  (call $line (call $drv_raw_map)) (call $indent)
  (call $line (call $drv_raw_column)) (call $line (call $drv_raw_missing)) (call $line (call $drv_raw_null)) (call $line (call $drv_raw_text))
  (local.set $start (global.get $txt_cursor)) (global.set $driver_join_count (i32.const 0))
  (call $driver_join_contexts (i32.load offset=52 (local.get $plan)) (i32.const 1))
  (call $line (call $fmt1 (call $drv_raw_array) (local.get $start) (i32.sub (global.get $txt_cursor) (local.get $start))))
  (call $line (call $fmt1 (call $drv_raw_decode) (call $runtime_import (local.get $m) (call $drv_with_context) (i32.const 0))))
  (call $dedent) (call $line (call $drv_raw_end)))

;; The SQLite drivers share row conversion and write-result policy. Deno owns
;; and disposes the statement in finally; better-sqlite3 owns that lifetime.
(func $driver_sqlite (param $m i32) (param $plan i32) (param $bindings i32) (param $bindings_n i32)
  (param $sql i32) (param $sql_n i32) (param $deno i32)
  (local $cmd i32) (local $tuple i32) (local $tuple_n i32) (local $value i32) (local $value_n i32)
  (local $count i32) (local $i i32)
  (local.set $cmd (i32.load offset=12 (local.get $plan)))
  (if (local.get $deno)
    (then (call $line (call $fmt1 (call $drv_prepare) (local.get $sql) (local.get $sql_n)))
      (call $line (call $drv_try)) (call $indent) (call $line (call $drv_safe)))
    (else (call $line (call $fmt1 (call $drv_prepare_safe) (local.get $sql) (local.get $sql_n)))))
  (block $query_done
    (if (i32.le_u (i32.sub (local.get $cmd) (i32.const 1)) (i32.const 1)) (then
      (call $runtime_import (local.get $m) (call $drv_sqlite_value) (i32.const 1)) (local.set $value_n) (local.set $value)
      (local.set $count (call $field_count (i32.load offset=52 (local.get $plan))))
      (local.set $tuple (global.get $txt_cursor)) (call $text_byte (i32.const 91))
      (block $tuple_done (loop $tuple_loop
        (br_if $tuple_done (i32.ge_u (local.get $i) (local.get $count)))
        (if (local.get $i) (then (call $text_append (call $drv_comma))))
        (call $text_append (local.get $value) (local.get $value_n))
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $tuple_loop)))
      (call $text_byte (i32.const 93)) (local.set $tuple_n (i32.sub (global.get $txt_cursor) (local.get $tuple)))
      (if (i32.eq (local.get $cmd) (i32.const 1))
        (then (call $line (call $fmt2 (call $drv_sqlite_get) (local.get $bindings) (local.get $bindings_n) (local.get $tuple) (local.get $tuple_n)))
          (call $line (call $fmt1 (call $drv_missing_row) (call $null_text))) (call $driver_row (local.get $m) (local.get $plan)))
        (else (call $line (call $fmt2 (call $drv_sqlite_all) (local.get $bindings) (local.get $bindings_n) (local.get $tuple) (local.get $tuple_n)))
          (call $driver_rows (local.get $m) (local.get $plan)))) (br $query_done)))
    (if (i32.eq (local.get $cmd) (i32.const 3)) (then
      (call $line (call $fmt1 (call $drv_run) (local.get $bindings) (local.get $bindings_n))) (br $query_done)))
    (call $line (call $fmt1 (call $drv_run_result) (local.get $bindings) (local.get $bindings_n)))
    (if (i32.eq (local.get $cmd) (i32.const 4)) (then
      (call $line (call $fmt1 (call $drv_return_value)
        (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_rows_affected) (call $drv_bigint) (call $drv_big_changes)))) (br $query_done)))
    (if (i32.eq (local.get $cmd) (i32.const 5)) (then
      (if (i32.and (local.get $deno) (i32.eqz (global.get $opt_mode_native)))
        (then (call $line (call $fmt1 (call $drv_return_value)
          (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_last_id) (call $drv_number) (call $drv_number_last)))))
        (else (call $line (call $fmt1 (call $drv_return_value)
          (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_last_id) (call $drv_bigint) (call $drv_big_last)))))) (br $query_done)))
    (if (i32.eq (local.get $cmd) (i32.const 6)) (then
      (call $line (call $fmt2 (call $drv_return_result)
        (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_rows_affected) (call $drv_bigint) (call $drv_big_changes))
        (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_last_id) (call $drv_bigint) (call $drv_big_last)))))))
  (if (local.get $deno) (then
    (call $dedent) (call $line (call $drv_finally)) (call $indent) (call $line (call $drv_dispose)) (call $dedent) (call $line (call $drv_end)))))

(func $driver_mysql_unsigned (result i32 i32)
  (if (i32.lt_s (global.get $opt_mysql_insert_unsigned) (i32.const 0)) (then (return (call $drv_undefined))))
  (call $bool_text (global.get $opt_mysql_insert_unsigned)))
(func $driver_mysql (param $m i32) (param $plan i32) (param $bindings i32) (param $bindings_n i32) (param $sql i32) (param $sql_n i32)
  (local $cmd i32) (local $row_query i32) (local $type i32) (local $type_n i32)
  (local $prefix i32) (local $prefix_n i32) (local $conversion i32) (local $conversion_n i32)
  (local.set $cmd (i32.load offset=12 (local.get $plan)))
  (local.set $row_query (i32.le_u (i32.sub (local.get $cmd) (i32.const 1)) (i32.const 1)))
  (if (local.get $row_query)
    (then
      (call $concat (call $module_import (local.get $m) (call $opt_driver_specifier) (call $drv_row_packet) (i32.const 1)) (call $drv_empty_bindings))
      (local.set $type_n) (local.set $type)
      (call $drv_mysql_prefix_rows) (local.set $prefix_n) (local.set $prefix))
    (else
      (call $module_import (local.get $m) (call $opt_driver_specifier) (call $drv_result_header) (i32.const 1)) (local.set $type_n) (local.set $type)
      (call $drv_mysql_prefix_result) (local.set $prefix_n) (local.set $prefix)))
  (if (i32.eq (local.get $cmd) (i32.const 3)) (then (local.set $prefix_n (i32.const 0))))
  (call $line (call $fmt2 (call $drv_mysql_execute) (local.get $prefix) (local.get $prefix_n) (local.get $type) (local.get $type_n)))
  (call $indent)
  (call $line (call $fmt1 (call $drv_mysql_sql) (local.get $sql) (local.get $sql_n)))
  (call $line (call $fmt1 (call $drv_mysql_values) (local.get $bindings) (local.get $bindings_n)))
  (call $line (call $fmt1 (call $drv_mysql_array) (call $bool_text (local.get $row_query))))
  (call $line (call $fmt1 (call $drv_mysql_big) (call $bool_text (global.get $opt_mysql_support))))
  (call $line (call $fmt1 (call $drv_mysql_strings) (call $bool_text (global.get $opt_mysql_strings))))
  (call $dedent) (call $line (call $drv_map_end))
  (if (local.get $row_query) (then (call $driver_rows (local.get $m) (local.get $plan)) (return)))
  (if (i32.eq (local.get $cmd) (i32.const 4)) (then
    (call $line (call $fmt1 (call $drv_return_value)
      (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_rows_affected) (call $drv_bigint)
        (call $fmt1 (call $drv_mysql_changes) (call $runtime_import (local.get $m) (call $drv_integer_result) (i32.const 0)))))) (return)))
  (if (i32.eq (local.get $cmd) (i32.const 5)) (then
    (call $drv_number) (local.set $type_n) (local.set $type)
    (if (global.get $opt_mysql_support) (then
      (call $drv_number_string) (local.set $type_n) (local.set $type)
      (if (global.get $opt_mysql_strings) (then (call $drv_string) (local.set $type_n) (local.set $type)))))
    (call $line (call $fmt1 (call $drv_return_value)
      (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_last_id) (local.get $type) (local.get $type_n)
        (call $fmt4 (call $drv_mysql_last) (call $runtime_import (local.get $m) (call $drv_mysql_id) (i32.const 0))
          (call $bool_text (global.get $opt_mysql_support)) (call $bool_text (global.get $opt_mysql_strings)) (call $driver_mysql_unsigned))))) (return)))
  (if (i32.eq (local.get $cmd) (i32.const 6)) (then
    (call $runtime_import (local.get $m) (call $drv_integer_result) (i32.const 0)) (local.set $conversion_n) (local.set $conversion)
    (call $line (call $fmt2 (call $drv_return_result)
      (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_rows_affected) (call $drv_bigint)
        (call $fmt1 (call $drv_mysql_changes) (local.get $conversion) (local.get $conversion_n)))
      (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_last_id) (call $drv_bigint)
        (call $fmt2 (call $drv_mysql_last_big) (call $runtime_import (local.get $m) (call $drv_mysql_id_bigint) (i32.const 0)) (call $driver_mysql_unsigned))))))))

(func $emit_driver_query (param $m i32) (param $plan i32) (param $bindings i32) (param $bindings_n i32) (param $sql i32) (param $sql_n i32)
  (local $cmd i32) (local $parameters i32) (local $parameters_n i32)
  (local.set $cmd (i32.load offset=12 (local.get $plan)))
  (if (i32.eqz (local.get $bindings_n)) (then (call $drv_empty_bindings) (local.set $bindings_n) (local.set $bindings)))
  (if (i32.ge_u (global.get $opt_driver) (i32.const 4)) (then
    (call $driver_sqlite (local.get $m) (local.get $plan) (local.get $bindings) (local.get $bindings_n) (local.get $sql) (local.get $sql_n)
      (i32.eq (global.get $opt_driver) (i32.const 5))) (return)))
  (if (i32.eq (global.get $opt_driver) (i32.const 3)) (then
    (call $driver_mysql (local.get $m) (local.get $plan) (local.get $bindings) (local.get $bindings_n) (local.get $sql) (local.get $sql_n)) (return)))
  (if (i32.eq (global.get $opt_driver) (i32.const 1)) (then
    (if (i32.eq (local.get $cmd) (i32.const 3)) (then
      (call $line (call $fmt2 (call $drv_pg_exec) (local.get $sql) (local.get $sql_n) (local.get $bindings) (local.get $bindings_n))) (return)))
    (call $line (call $fmt2 (call $drv_pg_result) (local.get $sql) (local.get $sql_n) (local.get $bindings) (local.get $bindings_n)))
    (if (i32.le_u (i32.sub (local.get $cmd) (i32.const 1)) (i32.const 1)) (then
      (call $line (call $drv_pg_rows)) (call $driver_rows (local.get $m) (local.get $plan)) (return)))
    (if (i32.eq (local.get $cmd) (i32.const 4)) (then
      (call $line (call $fmt1 (call $drv_return_value)
        (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_rows_affected) (call $drv_bigint)
          (call $fmt1 (call $drv_pg_count) (call $runtime_import (local.get $m) (call $drv_integer_result) (i32.const 0)))))) (return)))
    (if (i32.eq (local.get $cmd) (i32.const 6)) (then
      (call $line (call $fmt1 (call $drv_return_pg_result)
        (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_rows_affected) (call $drv_bigint)
          (call $fmt1 (call $drv_pg_count) (call $runtime_import (local.get $m) (call $drv_integer_result) (i32.const 0)))))))) (return)))
  (if (i32.eq (global.get $opt_driver) (i32.const 2)) (then
    (call $runtime_import (local.get $m) (call $drv_driver_parameters) (i32.const 1)) (local.set $parameters_n) (local.set $parameters)
    (if (i32.eq (local.get $cmd) (i32.const 3)) (then
      (call $line (call $fmt3 (call $drv_postgres_exec) (local.get $sql) (local.get $sql_n) (local.get $bindings) (local.get $bindings_n) (local.get $parameters) (local.get $parameters_n))) (return)))
    (if (i32.and (i32.le_u (i32.sub (local.get $cmd) (i32.const 1)) (i32.const 1))
      (call $driver_has_arrays (i32.load offset=52 (local.get $plan)))) (then
      (call $driver_postgres_raw (local.get $m) (local.get $plan) (local.get $bindings) (local.get $bindings_n) (local.get $sql) (local.get $sql_n) (local.get $parameters) (local.get $parameters_n))
      (call $driver_rows (local.get $m) (local.get $plan)) (return)))
    (call $line (call $fmt3 (call $drv_postgres_values) (local.get $sql) (local.get $sql_n) (local.get $bindings) (local.get $bindings_n) (local.get $parameters) (local.get $parameters_n)))
    (if (i32.le_u (i32.sub (local.get $cmd) (i32.const 1)) (i32.const 1)) (then (call $driver_rows (local.get $m) (local.get $plan)) (return)))
    (if (i32.eq (local.get $cmd) (i32.const 4)) (then
      (call $line (call $fmt1 (call $drv_return_value)
        (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_rows_affected) (call $drv_bigint)
          (call $fmt1 (call $drv_postgres_count) (call $runtime_import (local.get $m) (call $drv_integer_result) (i32.const 0)))))) (return)))
    (if (i32.eq (local.get $cmd) (i32.const 6)) (then
      (call $line (call $fmt1 (call $drv_return_pg_result)
        (call $driver_convert_result (local.get $m) (local.get $plan) (call $drv_rows_affected) (call $drv_bigint)
          (call $fmt1 (call $drv_postgres_count) (call $runtime_import (local.get $m) (call $drv_integer_result) (i32.const 0)))))))))))
