;; Factories are ordinary emitted TypeScript functions. The WASM keeps only
;; their names and import spans, with no connection or statement runtime state.
(func $query_namespace (param $p i32) (param $n i32) (result i32 i32)
  (call $lower_first (call $declaration_name (call $without_ext (call $path_clean (local.get $p) (local.get $n) (i32.const 1))))))

(func $emit_query_factory (param $m i32) (param $plans i32) (result i32 i32)
  (local $name i32) (local $name_n i32) (local $database i32) (local $database_n i32)
  (local $args i32) (local $args_n i32) (local $scope i32)
  (local.set $scope (i32.load offset=16 (local.get $m)))
  (call $name_take (local.get $scope) (call $c_create_queries)) (local.set $name_n) (local.set $name)
  (call $name_take (local.get $scope) (call $c_private_database)) (local.set $database_n) (local.set $database)
  (call $name_take (local.get $scope) (call $c_private_args)) (local.set $args_n) (local.set $args)
  (call $line (call $fmt3 (call $c_factory_line) (local.get $name) (local.get $name_n) (local.get $database) (local.get $database_n) (call $database_type (local.get $m))))
  (call $indent) (call $line (call $c_return_object)) (call $indent)
  (block $done (loop $plans
    (br_if $done (i32.eqz (local.get $plans)))
    (call $line (call $fmt5 (call $c_factory_method)
      (if (result i32 i32) (call $eq (call $get_text (local.get $plans) (i32.const 16)) (call $c_proto_name))
        (then (call $c_proto_property)) (else (call $property (call $get_text (local.get $plans) (i32.const 16)))))
      (if (result i32 i32) (i32.load offset=36 (local.get $plans))
        (then (call $fmt2 (call $c_factory_params) (local.get $args) (local.get $args_n) (call $get_text (local.get $plans) (i32.const 32)))) (else (call $c_empty)))
      (call $get_text (local.get $plans) (i32.const 16)) (call $get_text (local.get $plans) (i32.const 16))
      (if (result i32 i32) (i32.load offset=36 (local.get $plans))
        (then (call $concat (local.get $database) (local.get $database_n) (call $concat (call $c_comma) (local.get $args) (local.get $args_n))))
        (else (local.get $database) (local.get $database_n)))))
    (local.set $plans (call $next (local.get $plans))) (br $plans)))
  (call $dedent) (call $line (call $c_end_object)) (call $dedent) (call $line (call $c_close_brace)) (call $line (call $c_empty))
  (local.get $name) (local.get $name_n))

(func $emit_root_factory (param $m i32)
  (local $database i32) (local $database_n i32) (local $group i32)
  (call $name_take (i32.load offset=16 (local.get $m)) (call $c_private_database)) (local.set $database_n) (local.set $database)
  (call $line (call $c_empty))
  (call $line (call $fmt2 (call $c_root_factory_line) (local.get $database) (local.get $database_n) (call $database_type (local.get $m))))
  (call $indent) (call $line (call $c_return_object)) (call $indent)
  (local.set $group (global.get $gen_groups))
  (block $done (loop $groups
    (br_if $done (i32.eqz (local.get $group)))
    (call $line (call $fmt3 (call $c_root_factory_method)
      (call $property (call $get_text (local.get $group) (i32.const 48)))
      (call $get_text (local.get $group) (i32.const 56)) (local.get $database) (local.get $database_n)))
    (local.set $group (call $next (local.get $group))) (br $groups)))
  (call $dedent) (call $line (call $c_end_object)) (call $dedent) (call $line (call $c_close_brace)))
