;; Output uses the final 16 MiB of the one fixed memory. These cursors describe
;; bytes being written; they do not request memory from a heap or grow memory.
;;
;; We finish ALL files before sending stdout. A validation failure therefore
;; leaves stdout empty. After validation, protobuf framing can be streamed from
;; the saved file spans, avoiding a second complete copy of the generated files.
(global $out_cursor (mut i32) (i32.const 50331648))
(global $out_indent (mut i32) (i32.const 0))
(global $file_count (mut i32) (i32.const 0))
(global $file_start (mut i32) (i32.const 50331648))
(global $file_name_p (mut i32) (i32.const 0))
(global $file_name_n (mut i32) (i32.const 0))
(global $file_table i32 (i32.const 32768000))
(global $err_query (mut i32) (i32.const 0))
(global $err_model_p (mut i32) (i32.const 0))
(global $err_model_n (mut i32) (i32.const 0))
(global $err_options (mut i32) (i32.const 0))

;; Root-owned short constants occupy the bottom 8 KiB. Other fragments keep
;; their literals outside this range.
(data (i32.const 0) "error generating output: ")
(data (i32.const 32) "\0a")
(data (i32.const 40) "// Code generated by sqlc. DO NOT EDIT.\0a\0a")
(data (i32.const 80) " (")
(data (i32.const 82) "): ")
(data (i32.const 96) "model ")
(data (i32.const 102) ": ")
(data (i32.const 128) "typescript options: ")

(func $error (param $p i32) (param $n i32)
  (call $write_all (i32.const 2) (i32.const 0) (i32.const 25))
  ;; Generate wraps options.Parse errors even when Parse already included the
  ;; same words. Preserve that public diagnostic instead of simplifying it.
  (if (global.get $err_options) (then (call $write_all (i32.const 2) (i32.const 128) (i32.const 20))))
  (if (global.get $err_query)
    (then
      (call $write_all (i32.const 2) (call $text (global.get $err_query) (i32.const 2)))
      (call $write_all (i32.const 2) (i32.const 80) (i32.const 2))
      (call $write_all (i32.const 2) (call $text (global.get $err_query) (i32.const 7)))
      (call $write_all (i32.const 2) (i32.const 82) (i32.const 3)))
    (else (if (global.get $err_model_n) (then
      (call $write_all (i32.const 2) (i32.const 96) (i32.const 6))
      (call $write_all (i32.const 2) (global.get $err_model_p) (global.get $err_model_n))
      (call $write_all (i32.const 2) (i32.const 102) (i32.const 2))))))
  (call $write_all (i32.const 2) (local.get $p) (local.get $n))
  (call $write_all (i32.const 2) (i32.const 32) (i32.const 1))
  (call $wasi_proc_exit (i32.const 2))
  unreachable)

(func $emit (param $p i32) (param $n i32)
  ;; Subtraction is checked before addition, so a large length cannot wrap.
  (if (i32.gt_u (local.get $n) (i32.sub (i32.const 67108864) (global.get $out_cursor)))
    (then (call $fail (i32.const 15))))
  (memory.copy (global.get $out_cursor) (local.get $p) (local.get $n))
  (global.set $out_cursor (i32.add (global.get $out_cursor) (local.get $n))))

(func $emit_byte (param $b i32)
  (if (i32.ge_u (global.get $out_cursor) (i32.const 67108864)) (then (call $fail (i32.const 15))))
  (i32.store8 (global.get $out_cursor) (local.get $b))
  (global.set $out_cursor (i32.add (global.get $out_cursor) (i32.const 1))))

(func $line (param $p i32) (param $n i32) (local $i i32)
  ;; Like tsast.Writer, indent the first line only. Embedded SQL/JSDoc newlines
  ;; already carry their intentional text and must not be rewritten here.
  (if (local.get $n) (then
    (local.set $i (i32.shl (global.get $out_indent) (i32.const 1)))
    (block $done (loop $spaces
      (br_if $done (i32.eqz (local.get $i)))
      (call $emit_byte (i32.const 32))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br $spaces)))
    (call $emit (local.get $p) (local.get $n))))
  (call $emit_byte (i32.const 10)))

(func $indent (global.set $out_indent (i32.add (global.get $out_indent) (i32.const 1))))
(func $dedent
  (if (i32.eqz (global.get $out_indent)) (then (call $fail (i32.const 14))))
  (global.set $out_indent (i32.sub (global.get $out_indent) (i32.const 1))))

(func $file_begin (param $p i32) (param $n i32)
  (global.set $file_name_p (local.get $p))
  (global.set $file_name_n (local.get $n))
  (global.set $file_start (global.get $out_cursor))
  (global.set $out_indent (i32.const 0)))

(func $file_record (param $index i32) (result i32)
  (i32.add (global.get $file_table) (i32.shl (local.get $index) (i32.const 5))))

;; Finish a file as two borrowed spans, sent prefix first. Both spans live in
;; completed output memory until response_write returns. Ordinary files use an
;; empty prefix; modules discover imports after writing their body. No rotation
;; or second body buffer is needed. Record stride is 32 bytes; the final eight
;; bytes are reserved. The fixed table permits 1,024 files.
(func $file_end_parts (param $prefix i32) (param $prefix_n i32)
  (param $body i32) (param $body_n i32) (local $r i32)
  (if (i32.ge_u (global.get $file_count) (i32.const 1024)) (then (call $fail (i32.const 16))))
  (local.set $r (call $file_record (global.get $file_count)))
  (i32.store (local.get $r) (global.get $file_name_p))
  (i32.store offset=4 (local.get $r) (global.get $file_name_n))
  (i32.store offset=8 (local.get $r) (local.get $body))
  (i32.store offset=12 (local.get $r) (local.get $body_n))
  (i32.store offset=16 (local.get $r) (local.get $prefix))
  (i32.store offset=20 (local.get $r) (local.get $prefix_n))
  (global.set $file_count (i32.add (global.get $file_count) (i32.const 1))))

(func $file_end
  (call $file_end_parts (i32.const 0) (i32.const 0) (global.get $file_start)
    (i32.sub (global.get $out_cursor) (global.get $file_start))))

;; Match module.source(): remove trailing LF characters, then append one LF.
;; The caller owns [start,out_cursor); bytes before start remain untouched.
(func $finish_line (param $start i32)
  (block $trimmed (loop $trim
    (br_if $trimmed (i32.le_u (global.get $out_cursor) (local.get $start)))
    (br_if $trimmed (i32.ne (i32.load8_u (i32.sub (global.get $out_cursor) (i32.const 1))) (i32.const 10)))
    (global.set $out_cursor (i32.sub (global.get $out_cursor) (i32.const 1))) (br $trim)))
  (call $emit_byte (i32.const 10)))

(func $varint_size (param $v i32) (result i32) (local $n i32)
  (local.set $n (i32.const 1))
  (block $done (loop $more
    (br_if $done (i32.lt_u (local.get $v) (i32.const 128)))
    (local.set $n (i32.add (local.get $n) (i32.const 1)))
    (local.set $v (i32.shr_u (local.get $v) (i32.const 7)))
    (br $more)))
  (local.get $n))

(func $store_varint (param $p i32) (param $v i32) (result i32)
  ;; Caller supplies six scratch bytes. All lengths are bounded below 64 MiB,
  ;; so this loop writes at most four bytes, even on the largest response.
  (block $done (loop $more
    (br_if $done (i32.lt_u (local.get $v) (i32.const 128)))
    (i32.store8 (local.get $p) (i32.or (i32.and (local.get $v) (i32.const 127)) (i32.const 128)))
    (local.set $p (i32.add (local.get $p) (i32.const 1)))
    (local.set $v (i32.shr_u (local.get $v) (i32.const 7)))
    (br $more)))
  (i32.store8 (local.get $p) (local.get $v))
  (i32.add (local.get $p) (i32.const 1)))

(func $response_write (local $i i32) (local $j i32) (local $a i32) (local $b i32)
  (local $x i64) (local $y i64) (local $z i64) (local $name_n i32) (local $body_n i32)
  (local $payload i32) (local $end i32)
  ;; Insertion sort needs no auxiliary array, is stable for equal names, and
  ;; bounds comparisons to the actual file count instead of reserved capacity.
  (local.set $i (i32.const 1))
  (block $sorted (loop $sort
    (br_if $sorted (i32.ge_u (local.get $i) (global.get $file_count)))
    (local.set $j (local.get $i))
    (block $placed (loop $back
      (br_if $placed (i32.eqz (local.get $j)))
      (local.set $b (call $file_record (local.get $j)))
      (local.set $a (i32.sub (local.get $b) (i32.const 32)))
      (br_if $placed (i32.le_s (call $compare (i32.load (local.get $a)) (i32.load offset=4 (local.get $a))
                                            (i32.load (local.get $b)) (i32.load offset=4 (local.get $b))) (i32.const 0)))
      (local.set $x (i64.load (local.get $a)))
      (local.set $y (i64.load offset=8 (local.get $a)))
      (local.set $z (i64.load offset=16 (local.get $a)))
      (memory.copy (local.get $a) (local.get $b) (i32.const 24))
      (i64.store (local.get $b) (local.get $x))
      (i64.store offset=8 (local.get $b) (local.get $y))
      (i64.store offset=16 (local.get $b) (local.get $z))
      (local.set $j (i32.sub (local.get $j) (i32.const 1)))
      (br $back)))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br $sort)))
  (local.set $i (i32.const 0))
  (block $sent (loop $files
    (br_if $sent (i32.ge_u (local.get $i) (global.get $file_count)))
    (local.set $a (call $file_record (local.get $i)))
    (local.set $name_n (i32.load offset=4 (local.get $a)))
    (local.set $body_n (i32.add (i32.load offset=12 (local.get $a)) (i32.load offset=20 (local.get $a))))
    ;; File = name key + length + bytes + contents key + length + bytes.
    (local.set $payload (i32.add (i32.const 2)
      (i32.add (i32.add (call $varint_size (local.get $name_n)) (local.get $name_n))
               (i32.add (call $varint_size (local.get $body_n)) (local.get $body_n)))))
    (i32.store8 (i32.const 10240) (i32.const 10))
    (local.set $end (call $store_varint (i32.const 10241) (local.get $payload)))
    (i32.store8 (local.get $end) (i32.const 10))
    (local.set $end (call $store_varint (i32.add (local.get $end) (i32.const 1)) (local.get $name_n)))
    (call $write_all (i32.const 1) (i32.const 10240) (i32.sub (local.get $end) (i32.const 10240)))
    (call $write_all (i32.const 1) (i32.load (local.get $a)) (local.get $name_n))
    (i32.store8 (i32.const 10240) (i32.const 18))
    (local.set $end (call $store_varint (i32.const 10241) (local.get $body_n)))
    (call $write_all (i32.const 1) (i32.const 10240) (i32.sub (local.get $end) (i32.const 10240)))
    (call $write_all (i32.const 1) (i32.load offset=16 (local.get $a)) (i32.load offset=20 (local.get $a)))
    (call $write_all (i32.const 1) (i32.load offset=8 (local.get $a)) (i32.load offset=12 (local.get $a)))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br $files))))
