;; A hand-written parser for the same declaration-free TypeScript type grammar
;; as the previous generator. No tokenizer, AST, or temporary string uses
;; a heap. Tokens are views into the caller's string. Formatting writes once to
;; a bounded scratch buffer, then copies the finished string into the text pool.
;;
;; Limits match the reference: 65,536 source bytes, 8,192 tokens, depth 128.
;; The lexer table starts at 31,457,280: {pointer,length,kind,padding}, 16 bytes.
;; Formatting scratch occupies 31,588,352..31,719,424. A failed parse publishes
;; an error view there; callers must consume it before the next parse_type call.
;; Grammar calls use bounded Wasm call-stack recursion, never linear-memory
;; stack frames or an allocator. Error code zero means success throughout.
(global $tx_count (mut i32) (i32.const 0))
(global $tx_index (mut i32) (i32.const 0))
(global $tx_depth (mut i32) (i32.const 0))
(global $tx_out (mut i32) (i32.const 31588352))
(global $tx_err (mut i32) (i32.const 0))
(global $tx_argp (mut i32) (i32.const 0))
(global $tx_argn (mut i32) (i32.const 0))
(global $tx_oldp (mut i32) (i32.const 0))
(global $tx_oldn (mut i32) (i32.const 0))
(global $tx_newp (mut i32) (i32.const 0))
(global $tx_newn (mut i32) (i32.const 0))
(global $type_error_p (mut i32) (i32.const 0))
(global $type_error_n (mut i32) (i32.const 0))

;; Constant slots are 128 bytes apart. NUL terminates static diagnostic text;
;; source tokens retain explicit lengths and may never rely on a terminator.
(data (i32.const 2900096) "type exceeds 65536 bytes\00")
(data (i32.const 2900224) "type contains invalid UTF-8\00")
(data (i32.const 2900352) "type exceeds 8192 tokens\00")
(data (i32.const 2900480) "unescaped control character in type literal\00")
(data (i32.const 2900608) "invalid escape in type literal\00")
(data (i32.const 2900736) "invalid hexadecimal escape in type literal\00")
(data (i32.const 2900864) "octal escape in type literal\00")
(data (i32.const 2900992) "unterminated type literal\00")
(data (i32.const 2901120) "leading zero in numeric type literal\00")
(data (i32.const 2901248) "missing exponent in numeric type literal\00")
(data (i32.const 2901376) "bigint type literal must be an integer\00")
(data (i32.const 2901504) "unsupported character \00")
(data (i32.const 2901632) "invalid ts_type: \00")
(data (i32.const 2901760) "invalid ts_type at token \00")
(data (i32.const 2901888) ": \00")
(data (i32.const 2902016) "; use a named imported type for complex types\00")
(data (i32.const 2902144) "unexpected token \00")
(data (i32.const 2902272) "type nesting exceeds 128 levels\00")
(data (i32.const 2902400) "expected a type\00")
(data (i32.const 2902528) "expected )\00")
(data (i32.const 2902656) "required tuple element follows an optional element\00")
(data (i32.const 2902784) "expected ]\00")
(data (i32.const 2902912) "expected numeric literal\00")
(data (i32.const 2903040) "expected type name\00")
(data (i32.const 2903168) "readonly requires an array or tuple type\00")
(data (i32.const 2903296) "reserved or unsupported type keyword \00")
(data (i32.const 2903424) "type keyword \00")
(data (i32.const 2903552) " cannot be qualified or take type arguments\00")
(data (i32.const 2903680) "expected qualified name\00")
(data (i32.const 2903808) "expected qualified type name, got \00")
(data (i32.const 2903936) "expected >\00")
(data (i32.const 2904064) "invalid indexed access type\00")
(data (i32.const 2904192) "unterminated object type\00")
(data (i32.const 2904320) "expected property name\00")
(data (i32.const 2904448) "expected property type\00")
(data (i32.const 2904576) "expected property separator\00")
(data (i32.const 2904704) "typeof requires a value name\00")
(data (i32.const 2904832) "typeof requires a qualified value name\00")
(data (i32.const 2904960) "invalid ts_type import alias \00")
(data (i32.const 2905088) " in ts_type\00")
(data (i32.const 2910000) "any\00unknown\00never\00void\00undefined\00null\00true\00false\00string\00number\00bigint\00boolean\00symbol\00object\00\00")
(data (i32.const 2910300) "infer\00unique\00asserts\00is\00satisfies\00keyof\00readonly\00typeof\00\00")
(data (i32.const 2910500) "keyof\00readonly\00typeof\00")

(func $tx_eq (param $p i32) (param $n i32) (param $q i32) (param $m i32) (result i32)
  (if (i32.ne (local.get $n) (local.get $m)) (then (return (i32.const 0))))
  (block $done (loop $loop
    (br_if $done (i32.eqz (local.get $n)))
    (if (i32.ne (i32.load8_u (local.get $p)) (i32.load8_u (local.get $q))) (then (return (i32.const 0))))
    (local.set $p (i32.add (local.get $p) (i32.const 1)))
    (local.set $q (i32.add (local.get $q) (i32.const 1)))
    (local.set $n (i32.sub (local.get $n) (i32.const 1))) (br $loop)))
  (i32.const 1))
(func $tx_zlen (param $p i32) (result i32) (local $n i32)
  (block $done (loop $loop
    (br_if $done (i32.eqz (i32.load8_u (i32.add (local.get $p) (local.get $n)))))
    (local.set $n (i32.add (local.get $n) (i32.const 1))) (br $loop))) (local.get $n))
(func $tx_list (param $p i32) (param $n i32) (param $list i32) (result i32) (local $m i32)
  (block $done (loop $loop
    (local.set $m (call $tx_zlen (local.get $list))) (br_if $done (i32.eqz (local.get $m)))
    (if (call $tx_eq (local.get $p) (local.get $n) (local.get $list) (local.get $m)) (then (return (i32.const 1))))
    (local.set $list (i32.add (local.get $list) (i32.add (local.get $m) (i32.const 1)))) (br $loop)))
  (i32.const 0))
(func $tx_append (param $p i32) (param $n i32)
  (if (i32.gt_u (local.get $n) (i32.sub (i32.const 31719424) (global.get $tx_out))) (then (call $fail (i32.const 14))))
  (memory.copy (global.get $tx_out) (local.get $p) (local.get $n))
  (global.set $tx_out (i32.add (global.get $tx_out) (local.get $n))))
(func $tx_byte (param $b i32)
  (if (i32.ge_u (global.get $tx_out) (i32.const 31719424)) (then (call $fail (i32.const 14))))
  (i32.store8 (global.get $tx_out) (local.get $b))
  (global.set $tx_out (i32.add (global.get $tx_out) (i32.const 1))))
(func $tx_literal (param $code i32) (local $p i32)
  (local.set $p (i32.add (i32.const 2899968) (i32.shl (local.get $code) (i32.const 7))))
  (call $tx_append (local.get $p) (call $tx_zlen (local.get $p))))
(func $tx_decimal (param $n i32)
  (if (i32.ge_u (local.get $n) (i32.const 10)) (then (call $tx_decimal (i32.div_u (local.get $n) (i32.const 10)))))
  (call $tx_byte (i32.add (i32.const 48) (i32.rem_u (local.get $n) (i32.const 10)))))
(func $tx_error (param $code i32)
  (if (i32.eqz (global.get $tx_err)) (then (global.set $tx_err (local.get $code)))))
(func $tx_error_arg (param $code i32) (param $p i32) (param $n i32)
  (if (i32.eqz (global.get $tx_err)) (then
    (global.set $tx_err (local.get $code)) (global.set $tx_argp (local.get $p)) (global.set $tx_argn (local.get $n)))))

;; Token access never reads past the fixed table. The synthetic EOF token has
;; pointer/length/kind zero, allowing punctuation probes without special cases.
(func $tx_token (param $i i32) (result i32)
  (i32.add (i32.const 31457280) (i32.shl (local.get $i) (i32.const 4))))
(func $tx_p (result i32)
  (if (result i32) (i32.lt_u (global.get $tx_index) (global.get $tx_count))
    (then (i32.load (call $tx_token (global.get $tx_index)))) (else (i32.const 0))))
(func $tx_n (result i32)
  (if (result i32) (i32.lt_u (global.get $tx_index) (global.get $tx_count))
    (then (i32.load offset=4 (call $tx_token (global.get $tx_index)))) (else (i32.const 0))))
(func $tx_kind (result i32)
  (if (result i32) (i32.lt_u (global.get $tx_index) (global.get $tx_count))
    (then (i32.load offset=8 (call $tx_token (global.get $tx_index)))) (else (i32.const 0))))
(func $tx_peek (param $b i32) (result i32)
  (i32.and (i32.eq (call $tx_n) (i32.const 1)) (i32.eq (i32.load8_u (call $tx_p)) (local.get $b))))
(func $tx_eat (param $b i32) (result i32)
  (if (call $tx_peek (local.get $b)) (then
    (global.set $tx_index (i32.add (global.get $tx_index) (i32.const 1))) (return (i32.const 1)))) (i32.const 0))
(func $tx_word (param $p i32) (result i32)
  (call $tx_eq (call $tx_p) (call $tx_n) (local.get $p) (call $tx_zlen (local.get $p))))
(func $tx_emit_token
  (call $tx_append (call $tx_p) (call $tx_n))
  (global.set $tx_index (i32.add (global.get $tx_index) (i32.const 1))))
(func $tx_emit_name (param $p i32) (param $n i32)
  (if (i32.and (i32.ne (global.get $tx_newn) (i32.const 0))
    (call $tx_eq (local.get $p) (local.get $n) (global.get $tx_oldp) (global.get $tx_oldn)))
    (then (call $tx_append (global.get $tx_newp) (global.get $tx_newn)))
    (else (call $tx_append (local.get $p) (local.get $n)))))
(func $tx_keyword (param $p i32) (param $n i32) (result i32)
  (call $tx_list (local.get $p) (local.get $n) (i32.const 2910000)))
(func $tx_name (param $p i32) (param $n i32) (result i32)
  (if (call $tx_keyword (local.get $p) (local.get $n)) (then (return (i32.const 1))))
  (if (call $tx_list (local.get $p) (local.get $n) (i32.const 2910300)) (then (return (i32.const 0))))
  (call $identifier (local.get $p) (local.get $n)))

;; Pratt-style precedence is unnecessary for three levels: union calls
;; intersection, which calls primary. Emit each separator only after consuming
;; its token. Parser errors retain the same token index as the Go reference.
(func $tx_union
  (call $tx_intersection)
  (block $done (loop $loop
    (br_if $done (global.get $tx_err)) (br_if $done (i32.eqz (call $tx_eat (i32.const 124))))
    (call $tx_byte (i32.const 32)) (call $tx_byte (i32.const 124)) (call $tx_byte (i32.const 32))
    (call $tx_intersection) (br $loop))))
(func $tx_intersection
  (call $tx_primary)
  (block $done (loop $loop
    (br_if $done (global.get $tx_err)) (br_if $done (i32.eqz (call $tx_eat (i32.const 38))))
    (call $tx_byte (i32.const 32)) (call $tx_byte (i32.const 38)) (call $tx_byte (i32.const 32))
    (call $tx_primary) (br $loop))))
(func $tx_primary
  (if (i32.ge_u (global.get $tx_depth) (i32.const 128)) (then (call $tx_error (i32.const 18)) (return)))
  (global.set $tx_depth (i32.add (global.get $tx_depth) (i32.const 1)))
  (call $tx_primary_body)
  (global.set $tx_depth (i32.sub (global.get $tx_depth) (i32.const 1))))
(func $tx_primary_body (local $p i32) (local $n i32) (local $kind i32)
  (local $optional i32) (local $first i32) (local $start i32) (local $readonly i32)
  (if (i32.ge_u (global.get $tx_index) (global.get $tx_count)) (then (call $tx_error (i32.const 19)) (return)))
  (block $suffix
    (if (call $tx_eat (i32.const 40)) (then
      (call $tx_byte (i32.const 40)) (call $tx_union) (if (global.get $tx_err) (then (return)))
      (if (i32.eqz (call $tx_eat (i32.const 41))) (then (call $tx_error (i32.const 20)) (return)))
      (call $tx_byte (i32.const 41)) (br $suffix)))
    (if (call $tx_eat (i32.const 123)) (then (call $tx_object) (br $suffix)))
    (if (call $tx_eat (i32.const 91)) (then
      (call $tx_byte (i32.const 91)) (local.set $first (i32.const 1))
      (block $tuple_done (loop $tuple
        (br_if $tuple_done (call $tx_peek (i32.const 93)))
        (if (i32.eqz (local.get $first)) (then (call $tx_byte (i32.const 44)) (call $tx_byte (i32.const 32))))
        (local.set $first (i32.const 0))
        (call $tx_union) (if (global.get $tx_err) (then (return)))
        (if (call $tx_eat (i32.const 63))
          (then (call $tx_byte (i32.const 63)) (local.set $optional (i32.const 1)))
          (else (if (local.get $optional) (then (call $tx_error (i32.const 21)) (return)))))
        (br_if $tuple_done (i32.eqz (call $tx_eat (i32.const 44)))) (br $tuple)))
      (if (i32.eqz (call $tx_eat (i32.const 93))) (then (call $tx_error (i32.const 22)) (return)))
      (call $tx_byte (i32.const 93)) (br $suffix)))
    (if (call $tx_eat (i32.const 45)) (then
      (if (i32.ne (call $tx_kind) (i32.const 110)) (then (call $tx_error (i32.const 23)) (return)))
      (call $tx_byte (i32.const 45)) (call $tx_emit_token) (br $suffix)))
    (local.set $p (call $tx_p)) (local.set $n (call $tx_n)) (local.set $kind (call $tx_kind))
    (if (i32.and (i32.ne (local.get $kind) (i32.const 105))
      (i32.and (i32.ne (local.get $kind) (i32.const 115)) (i32.ne (local.get $kind) (i32.const 110))))
      (then (call $tx_error (i32.const 24)) (return)))
    (global.set $tx_index (i32.add (global.get $tx_index) (i32.const 1)))
    (if (i32.ne (local.get $kind) (i32.const 105)) (then (call $tx_append (local.get $p) (local.get $n)) (br $suffix)))
    (local.set $readonly (call $tx_eq (local.get $p) (local.get $n) (i32.const 2910506) (i32.const 8)))
    (if (i32.or (local.get $readonly) (call $tx_eq (local.get $p) (local.get $n) (i32.const 2910500) (i32.const 5))) (then
      (call $tx_append (local.get $p) (local.get $n)) (call $tx_byte (i32.const 32))
      (local.set $start (global.get $tx_out)) (call $tx_primary)
      (if (i32.and (i32.eqz (global.get $tx_err)) (local.get $readonly)) (then
        (if (i32.and (i32.ne (i32.load8_u (local.get $start)) (i32.const 91))
          (i32.or (i32.lt_u (i32.sub (global.get $tx_out) (local.get $start)) (i32.const 2))
            (i32.ne (i32.load16_u (i32.sub (global.get $tx_out) (i32.const 2))) (i32.const 23899))))
          (then (call $tx_error (i32.const 25))))))
      (return)))
    (if (call $tx_eq (local.get $p) (local.get $n) (i32.const 2910515) (i32.const 6))
      (then (call $tx_type_query) (br $suffix)))
    (if (i32.eqz (call $tx_name (local.get $p) (local.get $n)))
      (then (call $tx_error_arg (i32.const 26) (local.get $p) (local.get $n)) (return)))
    (if (call $tx_keyword (local.get $p) (local.get $n)) (then
      (if (i32.or (call $tx_peek (i32.const 46)) (call $tx_peek (i32.const 60)))
        (then (call $tx_error_arg (i32.const 27) (local.get $p) (local.get $n)) (return)))
      (call $tx_append (local.get $p) (local.get $n)) (br $suffix)))
    (call $tx_emit_name (local.get $p) (local.get $n))
    (block $qualified_done (loop $qualified
      (br_if $qualified_done (i32.eqz (call $tx_eat (i32.const 46))))
      (if (i32.ne (call $tx_kind) (i32.const 105)) (then (call $tx_error (i32.const 29)) (return)))
      (if (i32.or (i32.eqz (call $tx_name (call $tx_p) (call $tx_n))) (call $tx_keyword (call $tx_p) (call $tx_n)))
        (then (call $tx_error_arg (i32.const 30) (call $tx_p) (call $tx_n)) (return)))
      (call $tx_byte (i32.const 46)) (call $tx_emit_token) (br $qualified)))
    (if (call $tx_eat (i32.const 60)) (then
      (call $tx_byte (i32.const 60))
      (block $args_done (loop $args
        (call $tx_union) (if (global.get $tx_err) (then (return)))
        (br_if $args_done (i32.eqz (call $tx_eat (i32.const 44))))
        (call $tx_byte (i32.const 44)) (call $tx_byte (i32.const 32)) (br $args)))
      (if (i32.eqz (call $tx_eat (i32.const 62))) (then (call $tx_error (i32.const 31)) (return)))
      (call $tx_byte (i32.const 62)))))
  (block $done (loop $array
    (br_if $done (global.get $tx_err)) (br_if $done (i32.eqz (call $tx_eat (i32.const 91))))
    (call $tx_byte (i32.const 91))
    (if (i32.eqz (call $tx_eat (i32.const 93))) (then
      (call $tx_union) (if (global.get $tx_err) (then (return)))
      (if (i32.eqz (call $tx_eat (i32.const 93))) (then (call $tx_error (i32.const 32)) (return)))))
    (call $tx_byte (i32.const 93)) (br $array))))

(func $tx_object (local $first i32) (local $p i32) (local $n i32) (local $kind i32) (local $save i32)
  (call $tx_byte (i32.const 123)) (call $tx_byte (i32.const 32)) (local.set $first (i32.const 1))
  (block $done (loop $fields
    (br_if $done (call $tx_peek (i32.const 125)))
    (if (i32.eqz (local.get $first)) (then (call $tx_byte (i32.const 32))))
    (local.set $first (i32.const 0))
    (if (i32.and (call $tx_word (i32.const 2910506))
      (i32.lt_u (i32.add (global.get $tx_index) (i32.const 1)) (global.get $tx_count))) (then
      (global.set $tx_index (i32.add (global.get $tx_index) (i32.const 1)))
      (if (i32.or (call $tx_peek (i32.const 58)) (call $tx_peek (i32.const 63)))
        (then (global.set $tx_index (i32.sub (global.get $tx_index) (i32.const 1))))
        (else (call $tx_append (i32.const 2910506) (i32.const 8)) (call $tx_byte (i32.const 32))))))
    (if (i32.ge_u (global.get $tx_index) (global.get $tx_count)) (then (call $tx_error (i32.const 33)) (return)))
    (local.set $kind (call $tx_kind))
    (call $tx_emit_token)
    (if (i32.and (i32.ne (local.get $kind) (i32.const 105))
      (i32.and (i32.ne (local.get $kind) (i32.const 115)) (i32.ne (local.get $kind) (i32.const 110))))
      (then (call $tx_error (i32.const 34)) (return)))
    (if (call $tx_eat (i32.const 63)) (then (call $tx_byte (i32.const 63))))
    (if (i32.eqz (call $tx_eat (i32.const 58))) (then (call $tx_error (i32.const 35)) (return)))
    (call $tx_byte (i32.const 58)) (call $tx_byte (i32.const 32))
    (call $tx_union) (if (global.get $tx_err) (then (return))) (call $tx_byte (i32.const 59))
    (if (i32.eqz (call $tx_eat (i32.const 59))) (then
      (if (i32.and (i32.eqz (call $tx_eat (i32.const 44))) (i32.eqz (call $tx_peek (i32.const 125))))
        (then (call $tx_error (i32.const 36)) (return)))))
    (br $fields)))
  (drop (call $tx_eat (i32.const 125))) (call $tx_byte (i32.const 32)) (call $tx_byte (i32.const 125)))
(func $tx_type_query
  (if (i32.or (i32.ne (call $tx_kind) (i32.const 105))
    (i32.or (i32.eqz (call $identifier (call $tx_p) (call $tx_n))) (call $tx_keyword (call $tx_p) (call $tx_n))))
    (then (call $tx_error (i32.const 37)) (return)))
  (call $tx_append (i32.const 2910515) (i32.const 6)) (call $tx_byte (i32.const 32))
  (call $tx_emit_name (call $tx_p) (call $tx_n))
  (global.set $tx_index (i32.add (global.get $tx_index) (i32.const 1)))
  (block $done (loop $qualified
    (br_if $done (i32.eqz (call $tx_eat (i32.const 46))))
    (if (i32.ne (call $tx_kind) (i32.const 105)) (then (call $tx_error (i32.const 38)) (return)))
    (call $tx_byte (i32.const 46)) (call $tx_emit_token) (br $qualified))))

;; Scan UTF-8 twice: first validate the whole source, then classify tokens. This
;; gives an invalid byte at the end the same precedence as the reference lexer,
;; even if an earlier character would otherwise produce a syntax error.
(data (i32.const 2910600) "'\22\5cbfnrtv0xu\00")
(data (i32.const 2910640) "|&<>()[]{}:;?,.-\00")
(func $tx_contains (param $p i32) (param $b i32) (result i32)
  (block $done (loop $loop
    (br_if $done (i32.eqz (i32.load8_u (local.get $p))))
    (if (i32.eq (i32.load8_u (local.get $p)) (local.get $b)) (then (return (i32.const 1))))
    (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $loop))) (i32.const 0))
(func $tx_digit (param $c i32) (result i32)
  (i32.le_u (i32.sub (local.get $c) (i32.const 48)) (i32.const 9)))
(func $tx_hex (param $c i32) (result i32)
  (i32.or (call $tx_digit (local.get $c))
    (i32.le_u (i32.sub (i32.or (local.get $c) (i32.const 32)) (i32.const 97)) (i32.const 5))))
(func $tx_lex (param $p i32) (param $n i32)
  (local $end i32) (local $check i32) (local $after i32) (local $r i32) (local $flags i32)
  (local $start i32) (local $kind i32) (local $c i32) (local $quote i32)
  (local $closed i32) (local $escape i32) (local $digits i32) (local $integer i32) (local $exp i32) (local $slot i32)
  (if (i32.gt_u (local.get $n) (i32.const 65536)) (then (call $tx_error (i32.const 1)) (return)))
  (local.set $end (i32.add (local.get $p) (local.get $n))) (local.set $check (local.get $p))
  (block $validated (loop $validate
    (br_if $validated (i32.ge_u (local.get $check) (local.get $end)))
    (call $rune (local.get $check) (local.get $end)) (local.set $r) (local.set $after)
    (if (i32.and (i32.eq (local.get $r) (i32.const 65533))
      (i32.eq (local.get $after) (i32.add (local.get $check) (i32.const 1))))
      (then (call $tx_error (i32.const 2)) (return)))
    (local.set $check (local.get $after)) (br $validate)))
  (block $done (loop $tokens
    (br_if $done (i32.ge_u (local.get $p) (local.get $end)))
    (call $rune (local.get $p) (local.get $end)) (local.set $r) (local.set $after)
    (local.set $flags (call $unicode_flags (local.get $r)))
    (if (i32.and (local.get $flags) (i32.const 32)) (then (local.set $p (local.get $after)) (br $tokens)))
    (if (i32.ge_u (global.get $tx_count) (i32.const 8192)) (then (call $tx_error (i32.const 3)) (return)))
    (local.set $start (local.get $p)) (local.set $kind (i32.const 112))
    (block $token_done
      (if (i32.or (i32.and (local.get $flags) (i32.const 1))
        (i32.or (i32.eq (local.get $r) (i32.const 95)) (i32.eq (local.get $r) (i32.const 36)))) (then
        (local.set $kind (i32.const 105)) (local.set $p (local.get $after))
        (block $identifier_done (loop $identifier
          (br_if $identifier_done (i32.ge_u (local.get $p) (local.get $end)))
          (call $rune (local.get $p) (local.get $end)) (local.set $r) (local.set $after)
          (br_if $identifier_done (i32.eqz (i32.or (i32.and (call $unicode_flags (local.get $r)) (i32.const 7))
            (i32.or (i32.eq (local.get $r) (i32.const 95)) (i32.eq (local.get $r) (i32.const 36))))))
          (local.set $p (local.get $after)) (br $identifier))) (br $token_done)))
      (if (i32.or (i32.eq (local.get $r) (i32.const 39)) (i32.eq (local.get $r) (i32.const 34))) (then
        (local.set $kind (i32.const 115)) (local.set $quote (local.get $r)) (local.set $closed (i32.const 0))
        (local.set $p (i32.add (local.get $p) (i32.const 1)))
        (block $string_done (loop $string
          (br_if $string_done (i32.ge_u (local.get $p) (local.get $end)))
          (local.set $c (i32.load8_u (local.get $p))) (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (if (i32.lt_u (local.get $c) (i32.const 32)) (then (call $tx_error (i32.const 4)) (return)))
          (if (i32.eq (local.get $c) (local.get $quote)) (then (local.set $closed (i32.const 1)) (br $string_done)))
          (if (i32.eq (local.get $c) (i32.const 92)) (then
            (if (i32.or (i32.ge_u (local.get $p) (local.get $end))
              (i32.eqz (call $tx_contains (i32.const 2910600) (i32.load8_u (local.get $p)))))
              (then (call $tx_error (i32.const 5)) (return)))
            (local.set $escape (i32.load8_u (local.get $p)))
            (local.set $p (i32.add (local.get $p) (i32.const 1))) (local.set $digits (i32.const 0))
            (if (i32.eq (local.get $escape) (i32.const 120)) (then (local.set $digits (i32.const 2))))
            (if (i32.eq (local.get $escape) (i32.const 117)) (then (local.set $digits (i32.const 4))))
            (block $hex_done (loop $hex
              (br_if $hex_done (i32.eqz (local.get $digits)))
              (if (i32.or (i32.ge_u (local.get $p) (local.get $end))
                (i32.eqz (call $tx_hex (i32.load8_u (local.get $p)))))
                (then (call $tx_error (i32.const 6)) (return)))
              (local.set $p (i32.add (local.get $p) (i32.const 1)))
              (local.set $digits (i32.sub (local.get $digits) (i32.const 1))) (br $hex)))
            (if (i32.and (i32.eq (local.get $escape) (i32.const 48))
              (i32.and (i32.lt_u (local.get $p) (local.get $end)) (call $tx_digit (i32.load8_u (local.get $p)))))
              (then (call $tx_error (i32.const 7)) (return)))))
          (br $string)))
        (if (i32.eqz (local.get $closed)) (then (call $tx_error (i32.const 8)) (return))) (br $token_done)))
      (if (call $tx_digit (local.get $r)) (then
        (local.set $kind (i32.const 110)) (local.set $integer (i32.const 1))
        (local.set $p (i32.add (local.get $p) (i32.const 1)))
        (block $integer_done (loop $integer
          (br_if $integer_done (i32.ge_u (local.get $p) (local.get $end)))
          (br_if $integer_done (i32.eqz (call $tx_digit (i32.load8_u (local.get $p)))))
          (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $integer)))
        (if (i32.and (i32.gt_u (i32.sub (local.get $p) (local.get $start)) (i32.const 1))
          (i32.eq (i32.load8_u (local.get $start)) (i32.const 48)))
          (then (call $tx_error (i32.const 9)) (return)))
        (if (i32.and (i32.lt_u (local.get $p) (local.get $end)) (i32.eq (i32.load8_u (local.get $p)) (i32.const 46))) (then
          (local.set $integer (i32.const 0)) (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (block $decimal_done (loop $decimal
            (br_if $decimal_done (i32.ge_u (local.get $p) (local.get $end)))
            (br_if $decimal_done (i32.eqz (call $tx_digit (i32.load8_u (local.get $p)))))
            (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $decimal)))))
        (if (i32.and (i32.lt_u (local.get $p) (local.get $end))
          (i32.eq (i32.or (i32.load8_u (local.get $p)) (i32.const 32)) (i32.const 101))) (then
          (local.set $integer (i32.const 0)) (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (if (i32.and (i32.lt_u (local.get $p) (local.get $end))
            (i32.or (i32.eq (i32.load8_u (local.get $p)) (i32.const 43)) (i32.eq (i32.load8_u (local.get $p)) (i32.const 45))))
            (then (local.set $p (i32.add (local.get $p) (i32.const 1)))))
          (local.set $exp (local.get $p))
          (block $exponent_done (loop $exponent
            (br_if $exponent_done (i32.ge_u (local.get $p) (local.get $end)))
            (br_if $exponent_done (i32.eqz (call $tx_digit (i32.load8_u (local.get $p)))))
            (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $exponent)))
          (if (i32.eq (local.get $exp) (local.get $p)) (then (call $tx_error (i32.const 10)) (return)))))
        (if (i32.and (i32.lt_u (local.get $p) (local.get $end)) (i32.eq (i32.load8_u (local.get $p)) (i32.const 110))) (then
          (if (i32.eqz (local.get $integer)) (then (call $tx_error (i32.const 11)) (return)))
          (local.set $p (i32.add (local.get $p) (i32.const 1))))) (br $token_done)))
      (if (call $tx_contains (i32.const 2910640) (local.get $r)) (then (local.set $p (local.get $after)) (br $token_done)))
      (call $tx_error_arg (i32.const 12) (local.get $p) (i32.sub (local.get $after) (local.get $p))) (return))
    (local.set $slot (call $tx_token (global.get $tx_count)))
    (i32.store (local.get $slot) (local.get $start))
    (i32.store offset=4 (local.get $slot) (i32.sub (local.get $p) (local.get $start)))
    (i32.store offset=8 (local.get $slot) (local.get $kind))
    (global.set $tx_count (i32.add (global.get $tx_count) (i32.const 1))) (br $tokens))))

;; Diagnostic quoting deliberately does not interpret backslash escapes already
;; present in source. They describe the original token, not a decoded JS value.
(func $tx_quote (param $p i32) (param $n i32) (param $quote i32)
  (local $resultp i32) (local $resultn i32) (local $r i32)
  (if (i32.eq (local.get $quote) (i32.const 39))
    (then
      (call $rune (local.get $p) (i32.add (local.get $p) (local.get $n))) (local.set $r) drop
      (call $go_quote_rune (local.get $r)) (local.set $resultn) (local.set $resultp))
    (else (call $go_quote (local.get $p) (local.get $n)) (local.set $resultn) (local.set $resultp)))
  (call $tx_append (local.get $resultp) (local.get $resultn)))
(func $tx_format_error
  (global.set $tx_out (i32.const 31588352))
  (if (i32.le_u (global.get $tx_err) (i32.const 12))
    (then (call $tx_literal (i32.const 13)))
    (else (if (i32.ne (global.get $tx_err) (i32.const 39)) (then
      (call $tx_literal (i32.const 14)) (call $tx_decimal (i32.add (global.get $tx_index) (i32.const 1)))
      (call $tx_literal (i32.const 15))))))
  (call $tx_literal (global.get $tx_err))
  (if (i32.or (i32.or (i32.eq (global.get $tx_err) (i32.const 12)) (i32.eq (global.get $tx_err) (i32.const 17)))
    (i32.or (i32.or (i32.eq (global.get $tx_err) (i32.const 26)) (i32.eq (global.get $tx_err) (i32.const 27)))
      (i32.or (i32.eq (global.get $tx_err) (i32.const 30)) (i32.eq (global.get $tx_err) (i32.const 39)))))
    (then (call $tx_quote (global.get $tx_argp) (global.get $tx_argn)
      (if (result i32) (i32.eq (global.get $tx_err) (i32.const 12)) (then (i32.const 39)) (else (i32.const 34))))))
  (if (i32.eq (global.get $tx_err) (i32.const 12)) (then (call $tx_literal (i32.const 40))))
  (if (i32.eq (global.get $tx_err) (i32.const 27)) (then (call $tx_literal (i32.const 28))))
  (if (i32.and (i32.ge_u (global.get $tx_err) (i32.const 17)) (i32.ne (global.get $tx_err) (i32.const 39)))
    (then (call $tx_literal (i32.const 16))))
  (global.set $type_error_p (i32.const 31588352))
  (global.set $type_error_n (i32.sub (global.get $tx_out) (i32.const 31588352))))

(func $parse_type (param $p i32) (param $n i32) (param $oldp i32) (param $oldn i32)
  (param $newp i32) (param $newn i32) (result i32 i32 i32)
  (local $resultp i32) (local $resultn i32)
  (global.set $tx_count (i32.const 0)) (global.set $tx_index (i32.const 0))
  (global.set $tx_depth (i32.const 0)) (global.set $tx_err (i32.const 0))
  (global.set $tx_argp (i32.const 0)) (global.set $tx_argn (i32.const 0))
  (global.set $type_error_p (i32.const 0)) (global.set $type_error_n (i32.const 0))
  (global.set $tx_out (i32.const 31588352))
  (global.set $tx_oldp (local.get $oldp)) (global.set $tx_oldn (local.get $oldn))
  (global.set $tx_newp (local.get $newp)) (global.set $tx_newn (local.get $newn))
  (call $tx_lex (local.get $p) (local.get $n))
  (if (i32.eqz (global.get $tx_err)) (then
    (if (i32.and (i32.ne (i32.or (local.get $oldn) (local.get $newn)) (i32.const 0))
      (i32.eqz (call $identifier (local.get $newp) (local.get $newn))))
      (then (call $tx_error_arg (i32.const 39) (local.get $newp) (local.get $newn))))))
  (if (i32.eqz (global.get $tx_err)) (then
    (call $tx_union)
    (if (i32.and (i32.eqz (global.get $tx_err)) (i32.ne (global.get $tx_index) (global.get $tx_count)))
      (then (call $tx_error_arg (i32.const 17) (call $tx_p) (call $tx_n))))))
  (if (global.get $tx_err) (then (call $tx_format_error) (return (i32.const 0) (i32.const 0) (i32.const 0))))
  (call $text_copy (i32.const 31588352) (i32.sub (global.get $tx_out) (i32.const 31588352)))
  (local.set $resultn) (local.set $resultp)
  (i32.const 1) (local.get $resultp) (local.get $resultn))
